### PR TITLE
OWNERS for tests/tests/legacy_kustomizations

### PR DESCRIPTION
**Pull request by Bobgy**
**Which issue is resolved by this Pull Request:**
Resolves https://github.com/kubeflow/manifests/pull/1210#issuecomment-637235442

**Description of your changes:**
Add me to test snapshot OWNERES, so I can approve pipeline related changes by myself.

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by Bobgy** [comment]
/assign @jlewi 
Did I add it to the right place?
I also saw there's another folder `tests/legacy_kustomizations` that's almost the same.

**Comment by krishnadurai** [comment]
@Bobgy do you want to add yourself to this file instead?
https://github.com/kubeflow/manifests/blob/master/tests/OWNERS

**Comment by jlewi** [comment]
Use /tests/OWERS otherwise you won't be an owner of all the generated files.

**Comment by Bobgy** [comment]
Got it, thanks!
I'll update

**Comment by Bobgy** [comment]
I'll open a new PR instead.

**Pull request closed without merging**
