### PR TITLE
Re-add registration flow to centraldashboard via stacks 

### PR DESCRIPTION
**Pull request by tumido**
**Which issue is resolved by this Pull Request:**
~~Resolves #~~

**Description of your changes:**

1. Reintroduce `REGISTRATION_FLOW` environment variable for the `centraldashboard`  via stacks.
2. Adds a new Openshift stack with this value set to `false`

**Checklist:**
- [x] Unit tests have been rebuilt:
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by tumido** [comment]
@googlebot I signed it!

**Comment by PatrickXYS** [comment]
> Nope, this is pulling some unrelated changes and failing even when run against master branch

Please make sure you have kustomize <= 3.2.1 as described in the README

https://github.com/kubeflow/manifests/blob/master/README.md

**Comment by tumido** [comment]
@PatrickXYS done, thanks! :+1:

**Comment by DavidSpek** [comment]
@PatrickXYS The README states that kustomize <= 3.2.1 needs to be used until https://github.com/kubeflow/manifests/issues/538 is fixed. Given that the issue is closed, shouldn't the latest Kustomize work and should the README then be updated? If there is still an issue with using the latest Kustomize an issue should be created so this can be addressed and fixed (upstream).

**Comment by tumido** [comment]
Replaced by https://github.com/kubeflow/manifests/pull/1783

**Pull request closed without merging**
