### PR TITLE
Add model registry sync script

### PR DESCRIPTION
**Pull request by lampajr**
**Which issue is resolved by this Pull Request:**
Resolves https://github.com/kubeflow/manifests/issues/2631

**Description of your changes:**

- Added script to automatically fetch model-registry manifests, followed the same approach that has been done for other components
- Updated README adding model-registry row, since there is no version yet I linked `main` branch

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 5.2.1+**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by lampajr** [comment]
There are a couple of open points:
- Updating the https://github.com/kubeflow/manifests/blob/master/example/kustomization.yaml for the example but I am not sure if we want to do it as part of this PR or not.
- Include `apps/model-registry/upstream` folder with `main` branch manifests in this PR or if we want to wait the first release.

**Comment by rimolive** [comment]
Thank you @lampajr for your contribution!

cc @juliusvonkohout 

I believe components in alpha release aren't eligible to be part of the core manifests, correct?

**Comment by juliusvonkohout** [comment]
/hold

please the existing scripts into account. THhy all have the same format.

> Thank you @lampajr for your contribution!
> 
> cc @juliusvonkohout
> 
> I believe components in alpha release aren't eligible to be part of the core manifests, correct?

Just add this to the Agenda of the next Manifests WG meeting. Seldon should be a similar effort.

**Comment by juliusvonkohout** [comment]
> As discussed in the last Kubeflow Manifest WG meeting (2024-04-18) I am working on filling the requirements that are stated https://github.com/kubeflow/manifests/blob/master/proposals/20220926-contrib-component-guidelines.md#component-requirements.
> 
> For easier management we decided to add missing files, like manifests README and OWNERS, directly in the Kubeflow Model Registry repository (see [kubeflow/model-registry#69](https://github.com/kubeflow/model-registry/pull/69)). Thus, I think that this PR could be considered as ready for review as it simply adds the script to sink the manifest folder from Kubeflow Model Registry.

Are you sure that you also satisfy 

* All pods must run according to the offical Kubernetes [podsecuritystandards restricted set](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted). This means explicitly no root containers and dropping all capabilities in your pods securitycontexts.
* Running with Istio sidecars
* Namespace isolation / multi tenancy (except for the ml-metadata backend which is tackled in phase 2)

**Comment by lampajr** [comment]
> Are you sure that you also satisfy
> 
> * All pods must run according to the offical Kubernetes [podsecuritystandards restricted set](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted). This means explicitly no root containers and dropping all capabilities in your pods securitycontexts. You can easily test it with a namespace annotation.
> * Running with Istio sidecars
> * Namespace isolation / multi tenancy (except for the ml-metadata backend which is tackled in phase 2)

This is still an ongoing task to ensure those things.
At the moment with this PR and the other one on KFMR we should add all (or most of) missing files and setup the manifest sync automation.

@tarilabs @rimolive fyi

**Comment by juliusvonkohout** [comment]
/lgtm
/approve

then we discuss the details when synchronizing

**Comment by juliusvonkohout** [comment]
@lampajr please sign the google CLA

**Comment by juliusvonkohout** [comment]
@lampajr do you also need a networkpolicy for the manifest repository? Otherwise there wont be incoming traffic to the Kubeflow namespace for your pods. Please check https://github.com/kubeflow/manifests/tree/master/common/networkpolicies

**Comment by lampajr** [comment]
> @lampajr do you also need a networkpolicy for the manifest repository? 

We will discuss about this in the next KFMR bi-weekly meeting (next Monday)

> Otherwise there wont be incoming traffic to the Kubeflow namespace for your pods.

I am not sure I get this sentence, based on the https://github.com/kubeflow/manifests/tree/master/common/networkpolicies it looks like more an optional, second line of defence and especially for those pods that are not secured by Istio. So I don't get why you are saying a generic "there won't be incoming traffic". Do you mean just for those not protected by Istio? Or am I missing something else? :thinking:

**Comment by tarilabs** [comment]
I have the same questions as @lampajr (thanks btw for contributing to this work).

As the Model Registry registers with Istio: https://github.com/kubeflow/model-registry/tree/main/manifests/kustomize/options/istio
is that enough not to require a network policy to be defined (according to [this sentence](https://github.com/kubeflow/manifests/tree/master/common/networkpolicies#:~:text=that%20are%20not%20protected%20by%20Istio)); can that be confirmed please?

**Comment by juliusvonkohout** [comment]
> I have the same questions as @lampajr (thanks btw for contributing to this work).
> 
> As the Model Registry registers with Istio: https://github.com/kubeflow/model-registry/tree/main/manifests/kustomize/options/istio is that enough not to require a network policy to be defined (according to [this sentence](https://github.com/kubeflow/manifests/tree/master/common/networkpolicies#:~:text=that%20are%20not%20protected%20by%20Istio)); can that be confirmed please?

If you have any kind of webhook or service in the Kubeflow namespace that needs access from other namespaces or the apiserver (webhook) you need a networkpolicy, because that is blocked by default. But i can create one if 5 Minutes if I see your deployment ports.

**Comment by tarilabs** [comment]
thanks for the quick feedback @juliusvonkohout , let's keep posted 👍

**Pull request merged**
