### PR TITLE
documentation(ray): fix typo

### PR DESCRIPTION
**Pull request by wadhah101**
**Which issue is resolved by this Pull Request:**

**Description of your changes:**

**Checklist:**
- [x] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
@wadhah101 are you interested in working on ray Istio support? Because currently it is unprotected and accessible by other users due to lack of istio and networkpolicies

**Comment by wadhah101** [comment]
@juliusvonkohout seems interesting , any issues tracker or somewhere i can start ? you can find me on slack [wadhah.mahroug@qantev.com](mailto:wadhah.mahroug@qantev.com)

**Comment by juliusvonkohout** [comment]
@wadhah101 I cannot find you by email. You have to join the "ray" channel on slack https://kubeflow.slack.com/archives/C047L4B34KZ and check https://github.com/ray-project/kuberay/issues/1005. There you can collaborate with @Yicheng-Lu-llll qnd @kevin85421

**Review by juliusvonkohout — APPROVED** [review]

**Pull request merged**
