### PR TITLE
Cherry-pick of 'Update Knative to 0.14.3' (#1617) to v1.2-branch

### PR DESCRIPTION
**Pull request by pvaneck**
This cherry-picks #1617 into v1.2-branch

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by PatrickXYS** [comment]
@pvaneck You may need to cherry-pick this PR in advance https://github.com/kubeflow/kfctl/pull/439

**Comment by pvaneck** [comment]
@PatrickXYS Ah, okay. Let me do that.

**Pull request merged**
