### PR TITLE
v3 versions of default-install, kubeflow-roles, and spartakus

### PR DESCRIPTION
**Pull request by jlewi**
* Convert default-install and spartakus to v3.

* For default-install we need to change the name of the configmap to match
  the configmap that will be generated by kfctl.

* Modify spartakus to work with v3 and stacks; we need to change the
  config map name to match the config map generated by kfctl with
  application parameters.

* To fix the tests we need to change the name of the config maps.

Related to #1062

### CODE REVIEW

**Comment by jlewi** [comment]
Need to move metadata into its own PR before merging this.

**Comment by jlewi** [comment]
/assign @kunmingg 

@johnugeorge @kunmingg metadata was merged in #1098 so this is ready for review.

**Comment by jlewi** [comment]
@krishnadurai Could you re LGTM please?

**Comment by discordianfish** [comment]
@jlewi It looks like this only works with your personal fork in `https://github.com/jlewi/manifests/archive/stacks.tar.gz`. If I change the repos reference in kfctl_gcp_stacks.experimental.yaml to use https://github.com/kubeflow/manifests/archive/master.tar.gz instead, it fails with:
```
# /kfctl apply -d -f kfctl_gcp_stacks.experimental.yaml
2020/05/19 10:06:26 absolute path error in '/tmp/kftest/.cache/manifests/manifests-stacks/istio/gcp-1-1-6' : evalsymlink failure on '/tmp/kftest/.cache/manifests/manifests-stacks/istio/gcp-1-1-6' : lstat /tmp/kftest/.cache/manifests/manifests-stacks: no such file or directory
ERRO[0002] Error evaluating kustomization manifest for istio-stack: accumulating resources: accumulating resources from '../../.cache/manifests/manifests-stacks/istio/gcp-1-1-6': open /tmp/kftest/.cache/manifests/manifests-stacks/istio/gcp-1-1-6: no such file or directory  filename="kustomize/kustomize.go:155"
```

Is this intended? Is there a timeline when there will be a experimental stack based deployment here in master?

**Comment by jlewi** [comment]
That's odd the path looks like it exists.

You can track the respective issues for the platform you are interested in e.g.
#1062 Uber issue for all KFDefs.
#1096 IBM
#1095 AWS

For GCP its likely we will use blueprints and not provide a KFDef.
See #1063

**Pull request merged**
