### PR TITLE
Create overlay allowing the Load Balancer to be created with HTTPS wi…

### LINKED ISSUE #652: HTTPS for AWS ingress without auth
Create overlay for the **aws-alb-ingress-controller** allowing the Load Balancer to be created with HTTPS with it performing no auth. 

This is one set of changes to switch from using cognito on the ALB to using the oidc-authservice because in the current setup the users come through without any identity (anonymous). 
See https://github.com/devgrok/kubeflow-manifests/blob/aws-istio-oidc-cognito/kfdef/kfctl_aws_cognito.yaml for the desired final result.

### PR DESCRIPTION
**Pull request by devgrok**
**Which issue is resolved by this Pull Request:**
Resolves #652 

**Description of your changes:**
* Create overlay for the aws-alb-ingress-controller allowing the Load Balancer to be created with HTTPS with it performing no auth.
* Additionally making the scheme (internet facing/internal) configurable and adding external-dns annotation for clusters with it installed. 
* Cleaned up some duplicated annotations as well between the different overlays.
I couldn't get the tests to do it, but the oidc & cognito layers could piggy back off the secure one... though that may be more complex than the code it saves.

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/653)

### CODE REVIEW

**Comment by Jeffwan** [comment]
@animeshsingh Can you help approve this change?

**Comment by Jeffwan** [comment]
em.. Looks like it's Junit test of katib, not related..

/test kubeflow-manifests-presubmit

**Comment by jlewi** [comment]
Merging manually since test failures are unrelated and should be fixed on master.

**Pull request merged**
