### PR TITLE
feat: Reintroduce REGISTRATION_FLOW variable for central dashboard

### PR DESCRIPTION
**Pull request by tumido**
**Which issue is resolved by this Pull Request:**
Replaces: https://github.com/kubeflow/manifests/pull/1736 (I need to keep the original branch of the previous PR since I'm deploying from it, hence I'm creating a new PR, sorry)

**Description of your changes:**
Add the `REGISTRATION_FLOW` for central dashboard and makes the flag available in stacks

**Checklist:**
- [ ] Unit tests pass:  I'm unable to execute the `make generate-changes-only` due to `Error: accumulating resources: accumulating resources from '../../../pipeline/pipelines-ui/overlays/istio/virtual-service.yaml': open /home/tcoufal/Programming/AI-CoE/kubeflow/manifests/pipeline/pipelines-ui/overlays/istio/virtual-service.yaml: no such file or directory`, the tests were not yet adjusted to the new directory schema probably.

### CODE REVIEW

**Comment by DavidSpek** [comment]
I think you are looking for this: https://github.com/kubeflow/kubeflow/blob/98fc2dcb57fe0a5311abed28510a4df58a506971/components/centraldashboard/manifests/base/kustomization.yaml#L59

**Comment by tumido** [comment]
@DavidSpek you are 100% correct! Does that mean that this spec will get sync here as part of https://github.com/kubeflow/manifests/issues/1775 so it is available to be used in stacks?

**Comment by DavidSpek** [comment]
Yes, the upstream repositories are responsible for their manifests. This repository will just pull from the upstream ones, so if something is not correct in a manifest it needs to be addressed in the upstream repository.

**Comment by tumido** [comment]
Thank you @DavidSpek for your explanation. Learning something new every day. :+1:

That means this PR can be closed then :smile:

**Pull request closed without merging**
