### PR TITLE
Revert to 3e85b3c

### PR DESCRIPTION
**Pull request by kkasravi**
**Which issue is resolved by this Pull Request:**
Resolves #

command to revert:
git revert e97671c..019d532

**Description of your changes:**

**Checklist:**
- [ ] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/428)

### CODE REVIEW

**Comment by kunmingg** [comment]
Do we want to revert https://github.com/kubeflow/manifests/pull/342 as well?

**Comment by swiftdiaries** [comment]
@kunmingg Yeah I believe so

**Comment by kunmingg** [comment]
https://github.com/kubeflow/manifests/pull/427

**Comment by kkasravi** [comment]
i thought it was inclusive
so `git revert e97671c..019d532`
takes us back to 403

**Comment by kkasravi** [comment]
hmm it looks like #427 is correct - i can close this one. 
thanks @kunmingg

**Comment by jlewi** [comment]
Doesn't look like #342 got reverted.
Looking at 
application/application/overlays/application/application.yaml

It looks like name is still set to $(generateName) which I think is from #342

**Comment by kkasravi** [comment]
yes, kunming's is correct #427

**Pull request closed without merging**
