### PR TITLE
CentralDashboard Image for kubeflow/kubeflow#3933

### PR DESCRIPTION
**Pull request by avdaredevil**
CentralDashboard image made for https://github.com/kubeflow/kubeflow/pull/3933

### Meta
/area centraldashboard
/area front-end
/priority p1
/assign @avdaredevil
/cc @prodonjs

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/282)

### CODE REVIEW

**Comment by prodonjs** [comment]
@avdaredevil - I think you need to update https://github.com/kubeflow/manifests/blob/51d32474022eeb6b89a121d7d944efc843187307/tests/centraldashboard-base_test.go#L178 with the new image tag to have presubmit tests pass.

**Comment by kunmingg** [comment]
@avdaredevil 
You can run `make generate` & `make test` under `test` to update tests and verify locally.

**Pull request merged**
