### PR TITLE
update OWNERS

### PR DESCRIPTION
**Pull request by thesuperzapper**
As I end up touching so much of this repo (given how many pieces the notebook working group controls), its probably easier if I am added to the root OWNERS files.

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@PatrickXYS can you approve this?

For example, I cant approve, unless I am added to this OWNERS: https://github.com/kubeflow/manifests/pull/1654

**Comment by PatrickXYS** [comment]
@thesuperzapper Besides adding you into root OWNER, I'd like to keep more fine-grained ownership to add you into [test folder owner ](https://github.com/kubeflow/manifests/blob/master/tests/OWNERS#L1)and create OWNERs file with yourself listed in [common/centraldashboard folder](https://github.com/kubeflow/manifests/tree/master/common/centraldashboard
)

**Comment by thesuperzapper** [comment]
@PatrickXYS I have done this, and also added @kimwnasptd, who is also a lead of the Notebook WG

**Comment by PatrickXYS** [comment]
Thanks @thesuperzapper 

/lgtm
/approve

**Pull request merged**
