### PR TITLE
Update Alibi image for kfserving 0.3.0

### PR DESCRIPTION
**Pull request by cliveseldon**
**Which issue is resolved by this Pull Request:**
Resolves #
https://github.com/kubeflow/kfserving/issues/859

**Description of your changes:**
Updates Alibi image for KFServing 0.3.0

**Checklist:**
- [ *] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by cliveseldon** [comment]
@yuzisun

**Comment by yuzisun** [comment]
@cliveseldon seems still same issue?
```
  - containerID: docker://e3ceae91c6007b85edbcc281b7fbd2fa2d5658f0aa47633d491404c9a2fdf84c
    image: sha256:c12057a8aef08bb266be154e5b6c0ef86df414c62ab8e7667b9137278bda7e39
    imageID: docker-pullable://seldonio/kfserving-alibiexplainer@sha256:06a6d158d757ddf7c64c120cc2a43f4b5d76778f49840568da01bd78d1d0fb78
    lastState:
      terminated:
        containerID: docker://aec8ebe68b5d5fff31004d0182be573c48d3e58df433fa5648a55ff26dc6ac75
        exitCode: 1
        finishedAt: "2020-06-06T19:51:58Z"
        message: |
          [I 200606 19:51:57 __main__:116] Extra args: {}
          [I 200606 19:51:57 storage:35] Copying contents of /mnt/models to local
          [I 200606 19:51:57 __main__:125] Loading Alibi model
          Traceback (most recent call last):
            File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
              "__main__", mod_spec)
            File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
              exec(code, run_globals)
            File "/alibiexplainer/alibiexplainer/__main__.py", line 126, in <module>
              alibi_model = dill.load(f)
            File "/usr/local/lib/python3.7/site-packages/dill/_dill.py", line 270, in load
              return Unpickler(file, ignore=ignore, **kwds).load()
            File "/usr/local/lib/python3.7/site-packages/dill/_dill.py", line 472, in load
              obj = StockUnpickler.load(self)
            File "/usr/local/lib/python3.7/site-packages/dill/_dill.py", line 462, in find_class
              return StockUnpickler.find_class(self, module, name)
          AttributeError: Can't get attribute 'TabularSampler' on <module 'alibi.explainers.anchor_tabular' from '/usr/local/lib/python3.7/site-packages/alibi/explainers/anchor_tabular.py'>
        reason: Error
        startedAt: "2020-06-06T19:51:54Z"
```

**Comment by yuzisun** [comment]
tested with alibi 0.3 saved explainer and it works, so for KFServing 0.3.0 user need to use alibi 0.3 saved explainer, worth to document this.

/unhold
/lgtm

**Comment by yuzisun** [comment]
@animeshsingh Can you help approve this?

**Pull request merged**
