### PR TITLE
Upgrading istio to v1.18.7

### PR DESCRIPTION
**Pull request by biswajit-9776**
# Pull Request Template for Kubeflow manifests Issues

- Please include a summary of changes and the related issue. 
- List any dependencies that are required for this change. 
- Please delete the options that are not relevant.
- The following checklist will help you to satisfy the requirements.

  
## ✅ Unit Test Checklist
  
  - [ ] 🛠️ Make sure you have installed kustomize == 5.2.1+     
  - [ ] ✍️ Have you written new tests for your core changes, as applicable?      
  - [ ] 🔄 Have you successfully run existing tests with your changes ?    
  - [ ] 🚀 Have you successfully run existing and new tests with your changes ?

## ✅ Contributor checklist
  - [ ] All the commits have been _signed-off_  (To pass the `DCO` check)
  - [ ] Submit the [Contributor License Agreements](https://cla.developers.google.com/clas) (To pass the `cla/google` check)

---     
 
>You can join our slack channel **wg-manifests** [here](https://www.kubeflow.org/docs/about/community/). This link also contains our meeting schedule.

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
TODO:

- Update istio-cni as well
- delete the istio 1.17 folders
- Update the readme
- Transform the readme into a script as we have it in /hack to upgrade synchronize istio manifestsin an automated manner next time
- use the script to update to in several PRs to 1.19, then 1.20, then 1.21 and 1.22

**Comment by rimolive** [comment]
I'm not sure if the TODO items are missing work items for this PR, but if the tests passed I think we're good to move on. I'll lgtm but will hold to merge until @juliusvonkohout approves.

/lgtm
/hold

**Comment by juliusvonkohout** [comment]
> TODO:
> 
>     * Update istio-cni to 1.18.7 as well
> 
>     * delete the istio 1.17 folders
> 
>     * fix all tests
> 
>     * Update the readme
> 
>     * Transform the readme into a script as we have it in /hack to upgrade synchronize istio manifests in an automated manner next time
> 
>     * For istio-cni we need a script as well
> 
>     * use the script to update to in several PRs to 1.19, then 1.20, then 1.21 and 1.22 for istio and istio-cni

@biswajit-9776 lets continue this in a new PR then such that we can cut RC.1

**Pull request merged**
