### PR TITLE
Update kserve manifests from v0.11.2

### PR DESCRIPTION
**Pull request by rimolive**
Update kserve/kserve manifests from v0.11.2

**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 5.0.3**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
I tried the asme and the diff is zero, so

/LGTM

**Comment by juliusvonkohout** [comment]
@rimolive  this must be merged to master as well. Usually we do it the other way around.

**Review by juliusvonkohout — APPROVED** [review]

**Comment by juliusvonkohout** [comment]
@rimolive i need acces to your branch to sign my commits. You can also sign them if you want.

**Comment by rimolive** [comment]
I cannot sign others commits, let me give you permissions

**Pull request merged**
