### PR TITLE
Add tedhtchang to Feast OWNERS

### PR DESCRIPTION
**Pull request by woop**
**Description of your changes:**
@tedhtchang, adding you to the OWNERS file so that we can move a bit faster.

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by tedhtchang** [comment]
@woop Thanks!

**Review by animeshsingh — APPROVED** [review]
/lgtm

**Comment by PatrickXYS** [comment]
>tedhtchang
User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.

@tedhtchang  You need to be kubeflow member prior to become an OWNER of kubeflow/manifests repo

**Comment by tedhtchang** [comment]
@PatrickXYS 
> @tedhtchang You need to be kubeflow member prior to become an OWNER of kubeflow/manifests repo

I created a PR https://github.com/kubeflow/internal-acls/pull/457 to become a member.

**Pull request merged**
