### PR TITLE
update jupyter config with tolerations/selectors

### PR DESCRIPTION
**Pull request by thesuperzapper**
**Description of your changes:**

Updates the default `spawner_ui_config.yaml` with new sections for the tolerations/selectors feature.

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@Jeffwan can you review? (this needs to get into Kubeflow 1.2)

**Comment by Jeffwan** [comment]
I see the other PR on the image tag update.

**Review by Jeffwan — APPROVED** [review]

**Comment by Bobgy** [comment]
@thesuperzapper can you inform me what do platform owners need to do with this config?

**Comment by thesuperzapper** [comment]
@Bobgy if your stack has a copy of the `spawner_ui_config.yaml` file, you probably want to update it to include the new config fields:  `spawnerFormDefaults.affinityConfig` and `spawnerFormDefaults.tolerationGroup` 

You can simply use the value of the default one: https://github.com/kubeflow/manifests/blob/master/jupyter/jupyter-web-app/base/configs/spawner_ui_config.yaml

**Comment by Bobgy** [comment]
Thanks, GCP is directly using base_v3, I believe it's fine then.

**Pull request merged**
