### PR TITLE
Automated cherry pick of #949: Adds kfserving ingressgateway for Istio 1.1.6 Modifies Cherry pick of #949 on v1.0-branch. #949: Adds kfserving ingressgateway for Istio 1.1.6 Modifies

### PR DESCRIPTION
**Pull request by krishnadurai**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/1017)

### CODE REVIEW

**Comment by krishnadurai** [comment]
@richardsliu it looks like the test pipeline is breaking during initiating.

**Comment by richardsliu** [comment]
Do we still need this now that #1027 is merged?

**Comment by krishnadurai** [comment]
@richardsliu this is not needed, thanks.

/close

**Pull request closed without merging**
