### PR TITLE
Add Feast to Kubeflow

### PR DESCRIPTION
**Pull request by woop**
### **Overview**
As part of the [Kubeflow Feature Store SIG](https://github.com/kubeflow/community/tree/master/sig-feature-store) we have been working towards making a feature store available to Kubeflow users. Feast is the feature store we intend to integrate into Kubeflow to address the first set of operational ML use cases. 

Feast is already a Kubeflow component, but it its [installation is still separate](https://www.kubeflow.org/docs/components/feature-store/getting-started/) from Kubeflow. Kubeflow stacks don't ship with Feast yet. 

This pull request is a straw man proposal to integrate Feast into Kubeflow. The idea is that the Kubeflow community can kick the tires of Feast on Kubeflow and try it out, and then agree on the requirements that need to be met in order to finish this PR and have it merged in.

### **Value prop**

Feast provides specific value for operational machine learning use cases today.

- **Serving features at scale**: Feast provides a means to build training datasets from offline/batch sources scalably using Spark. In the case of this PR, we have specifically added support for Kubeflow's built in Spark Operator. The operator is used to join data from sources like S3, GCS, BigQuery into a complete training dataset which can then be used to train models in KF Pipelines. Additionally, Feast also provides a low latency feature serving API (Feast Online Serving) which allows teams to enrich entities (users, drivers, products, etc) with feature values that are stored in an online store (Redis in this case). We also support Redis cluster for teams that need to scale out to larger data  sets.
- **Consistency between training and serving**: Feast decouples models from data infrastructure by providing a consistent interface to which teams can develop their feature retrieval code. Instead of teams having to interface directly with a SQL or online database, they now query the Feast APIs with a list of entities and features, and will receive either a training dataset or online features. This allows teams to standardize their production environment by only shipping model binaries and feature lists into production, instead of custom code that re-engineers features.
- **Point-in-time correctness**: Feast ensures point in time correctness when building training datasets. We build queries that join entities to features in a way that is representative of how those features were served in production. We currently leverage Spark for this "as-of" join. A note here: We require teams to persist their data with a specific format in order to leverage point-in-time correctness (for example they need timestamp columns and entity keys in their table sources).

The above points are our initial value proposition, but we have multiple areas of active development where we are planning to extend Feast. We are also working towards solving feature sharing/reuse through our APIs and a UI (driven by Gojek) and we are also extending Feast to integrate with data quality and validation tools. There are also active discussions today on how transformations can be incorporated into Feast, and we're looking forward to hearing more from Kubeflow users on their needs.

### **Contents of this PR**
This pull request contains a Kustomize installation for Feast in the `feast/` folder. This installation is based off of our Helm chart (we have modeled our logic on the Seldon installation).

**Components**

- Feast Core: The feature registry where schemas are registered and managed.
- Feast Online Serving: The online serving API, used to retrieve feature values in production.
- Feast Job Service (Optional): Acts as a gateway to launching jobs (ingestion into online store, training dataset creation). The Job Service automates the process of provisioning streaming ingestion jobs and also acts as a gateway for Feast SDK users to launch new jobs, without granting infrastructural credentials to end users. It is optional because users can also launch their own jobs directly from the Feast SDK if they have the correct credentials.
- Redis: Used as the online serving store.
- Postgres: Used to store metadata/state for Feast Core.

We'd love feedback from the Kubeflow community on whether the above components make sense for installation, or where there are opportunities to leverage existing components within the Kubeflow ecosystem.

### **Installation and demo notebook**
This PR modifies the [kfdef/kfctl_k8s_istio.v1.2.0.yaml](https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_k8s_istio.v1.2.0.yaml) kfdef in order to make Feast a part of an open source stack. As mentioned above, this PR will need to go through some refinement before being merged. The proposed kfdef points to my personal `manifests` repo which makes it possible to test the installation prior to merging it in.

**How to get started:**
1. Start Minikube
2. Install Kubeflow with Feast
```
kfctl apply -V -f kfctl_k8s_istio.v1.2.0.yaml
```
3. Open the Kubeflow dashboard and create both a namespace and a Jupyter notebook
4. Create a Spark service account (this step will be removed later)
```
kubectl create serviceaccount spark -n kubeflow
```
5. Add role bindings for both the Spark service account and the Jupyter user/namespace (this step will be removed later)
kubectl edit clusterrolebinding spark-operatorsparkoperator-crb
```
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole 
  name: spark-operatoroperator-cr 
subjects: 
- kind: ServiceAccount 
  name: spark-operatoroperator-sa 
  namespace: kubeflow 
- kind: ServiceAccount 
  name: default-editor 
  namespace: willem
- kind: ServiceAccount 
  name: spark
  namespace: kubeflow
```
Please use the name of your namespace above, not `willem`.

6. Upload and run the Feast on Kubeflow notebook
We've created a [notebook over here](https://github.com/feast-dev/feast-kubeflow-demo-notebook/blob/main/Feast%20on%20Kubeflow%20Notebook.ipynb) that folks can run through in order to test Feast on Kubeflow. This notebook allows you to 
1. Register feature definitions with Feast
2. Build a training dataset using the SparkOp
3. Ingest data into the online store (Redis Cluster) 
4. Serve online feature values to models using the online serving API

### **Next Steps**

We'd love to get feedback on the PR! Is there anything missing? Anything you'd like to change? We'd love to kick off a discussion!

### CODE REVIEW

**Comment by PatrickXYS** [comment]
/cc @kubeflow/wg-manifests-leads 

I think this needs to be discussed in wg-manifests, and after we have majority of WG-manifest ACK, we can move forward

**Comment by animeshsingh** [comment]
This is a great and welcome addition to Kubeflow. The dependency to Spark Operator is concerning to me though, as I am not clear if anyone is actively maintaining that integration....

/lgtm

**Comment by woop** [comment]
> This is a great and welcome addition to Kubeflow. The dependency to Spark Operator is concerning to me though, as I am not clear if anyone is actively maintaining that integration....
> 
> /lgtm

Thanks @animeshsingh 

I think we'd be happy to take maintain the Spark operator if Feast relies on it. We've been pleasantly surprised by how easy it is to use (compared to Dataproc and EMR), but of course there may be some devil in the details.

**Comment by woop** [comment]
In the Manifests working group we discussed this PR today. The outcome was that
1. This PR should target the contrib folder as part of the new folder re-org (#1739). Once targeted, we can go ahead and merge it.
2. The Feature Store SIG team (and Feast contributors) can work with stack owners to have the component included in their stacks.

**Comment by animeshsingh** [comment]
@woop - from your perspective is this ready to be merged based on the ask from manifests group?

**Comment by woop** [comment]
@animeshsingh yes, the ask from the wg-manifests group was only to move the target to the `contrib` folder. Adoption of Feast into specific distribution is up to the owners of said distributions. This implementation has _**not**_ solved security concerns yet, so there is still some work to be done. However, I believe that it makes sense to merge it and to then iterate on the implementation in place incrementally.

**Comment by woop** [comment]
Also, please note that the PR in question is now over here: https://github.com/kubeflow/manifests/pull/1755

**Pull request closed without merging**
