### PR TITLE
Synchronize kserve manifests v0.14.0

### PR DESCRIPTION
**Pull request by juliusvonkohout**
@tarekabouzeid @rimolive for a /lgtm

### CODE REVIEW

**Comment by tarekabouzeid** [comment]
@juliusvonkohout  can you restart failed pipelines ?

**Comment by juliusvonkohout** [comment]
> @juliusvonkohout can you restart failed pipelines ?

Yes, now also the update script with the version in the readme should be fixed

**Comment by juliusvonkohout** [comment]
Kserve crds are now so big, that they do not work with client-side apply anymore... But this is now the case for many projects...

**Pull request merged**
