### PR TITLE
Synchronize kubeflow model registry manifests v0.2.9

### PR DESCRIPTION
**Pull request by Al-Pragliola**
# Pull Request Template for Kubeflow manifests Issues

## ✅ Contributor checklist
  - Make sure you have tested with kustomize. See [Installation Prerequisites](https://github.com/kubeflow/manifests#prerequisites)
  - All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

---     
 
> You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### CODE REVIEW

**Review by tarilabs — COMMENTED** [review]
many thanks @Al-Pragliola 

/lgtm

cc @lampajr could you kindly also 👀 ?

**Review by lampajr — APPROVED** [review]
/lgtm as well!

**Comment by Al-Pragliola** [comment]
cc @juliusvonkohout , kindly ask if you can take a look at the PR, thanks

**Pull request merged**
