### PR TITLE
fix mysql deployment strategy (#1562)

### PR DESCRIPTION
**Pull request by thesuperzapper**
(cherry picked from commit 6c4f2653abd13e6f866ef78f2fbd63adb1c89a49)

See PR:#1562

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@PatrickXYS can you review?

**Comment by PatrickXYS** [comment]
```
===== ACTUAL END ==========================================
  EXPECTED                                                                                 ACTUAL
  --------                                                                                 ------
  apiVersion: apps/v1                                                                      apiVersion: apps/v1
  kind: Deployment                                                                         kind: Deployment
  metadata:                                                                                metadata:
    labels:                                                                                  labels:
      app: katib                                                                               app: katib
      app.kubernetes.io/component: katib                                                       app.kubernetes.io/component: katib
      app.kubernetes.io/name: katib-controller                                                 app.kubernetes.io/name: katib-controller
      component: mysql                                                                         component: mysql
    name: katib-mysql                                                                        name: katib-mysql
    namespace: kubeflow                                                                      namespace: kubeflow
  spec:                                                                                    spec:
    replicas: 1                                                                              replicas: 1
    selector:                                                                                selector:
      matchLabels:                                                                             matchLabels:
        app: katib                                                                               app: katib
        app.kubernetes.io/component: katib                                                       app.kubernetes.io/component: katib
        app.kubernetes.io/name: katib-controller                                                 app.kubernetes.io/name: katib-controller
        component: mysql                                                                         component: mysql
X    template:                                                                                strategy:
X      metadata:                                                                                type: Recreate
X        annotations:                                                                         template:
X          sidecar.istio.io/inject: "false"                                                     metadata:
X        labels:                                                                                  annotations:
X          app: katib                                                                               sidecar.istio.io/inject: "false"
X          app.kubernetes.io/component: katib                                                     labels:
X          app.kubernetes.io/name: katib-controller                                                 app: katib
```

Unit test failed, can you regenerate tests? @thesuperzapper

**Pull request merged**
