### PR TITLE
Add Feast to Kubeflow Contrib

### PR DESCRIPTION
**Pull request by woop**
**Description of your changes:**
For some reason #1733 was closed after I rebased. I'm reopening the same PR.

### CODE REVIEW

**Comment by woop** [comment]
@googlebot I signed it!

**Comment by animeshsingh** [comment]
/lgtm

cc @pvaneck @yanniszark any last glitches?

**Review by pvaneck — COMMENTED** [review]
Looks good to me, though I'm not sure if the `do-not-merge/invalid-owners-file` label will prevent merging. May have to remove oavdeev from the OWNERS file.

**Comment by woop** [comment]
> Looks good to me, though I'm not sure if the `do-not-merge/invalid-owners-file` label will prevent merging. May have to remove oavdeev from the OWNERS file.

Done.

**Comment by yanniszark** [comment]
@woop thanks a lot for the awesome contribution!

**Pull request merged**
