### PR TITLE
update instance label for metadata

### LINKED ISSUE #480: update application overlay for metadata

### PR DESCRIPTION
**Pull request by kkasravi**
**Which issue is resolved by this Pull Request:**
Resolves #480

**Description of your changes:**
rebased from master, ran tests

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/523)

### CODE REVIEW

**Comment by richardsliu** [comment]
@kkasravi There are a lot of non-metadata related changes in this PR, are these intended?

**Comment by kkasravi** [comment]
@richardsliu looks like this can be merged

**Pull request merged**
