### PR TITLE
#2775 describe how to change default password from secret

### PR DESCRIPTION
**Pull request by tsadimas**
# Pull Request Template for Kubeflow manifests Issues
- Describe how to change the default user password using the dex-password secret

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
@tsadimas you need to sign the DCO and rebase

**Comment by diegolovison** [comment]
Ok. I am good if we have documented the two ways:
* How to change the password before creating the cluster
* How to change the password after creating the cluster

**Comment by rimolive** [comment]
@tsadimas Can you sign-off the commits?

**Pull request closed without merging**
