### PR TITLE
Update generated kfdefs

### PR DESCRIPTION
**Pull request by Bobgy**
**Which issue is resolved by this Pull Request:**
Part of https://github.com/kubeflow/kubeflow/issues/4803

**Description of your changes:**
Update generated kfdefs from kfdef source

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

/assign @richardsliu @jlewi

### CODE REVIEW

**Comment by jlewi** [comment]
Did you manually edit these files or did you run make in manifests/kfctl?
https://github.com/kubeflow/manifests/tree/master/kfdef/source

How will we make it easy to keep the release branch in sync?

#1083 changed master which is the base for the v1.0.0 and v1.0.1 packages which "breaks" them; i.e. if you run make you will end up including the user-spec manifest in the manifest for v1.0.0 and v1.0.1 which is not what we want since we don't want those to change.

Since those configs are finalized and checked into manifests we could just uncouple them from the Makefile so that they would no longer be regenerated.

**Comment by Bobgy** [comment]
@jlewi I ran `hack/build_kfdef_specs.py` and restored changes to published manifests.

**Comment by Bobgy** [comment]
Yes, I agree with `Since those configs are finalized and checked into manifests we could just uncouple them from the Makefile so that they would no longer be regenerated.`

**Pull request merged**
