### PR TITLE
Document recommendation of kustomize version

### PR DESCRIPTION
**Pull request by Bobgy**
**Which issue is resolved by this Pull Request:**
Resolves https://github.com/kubeflow/manifests/issues/1217

**Description of your changes:**
Add kustomize version recommendation in README

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by Bobgy** [comment]
/assign @jlewi 
Because it's kind of hard to find the right version (I tried to use kustomize v3.5, but it doesn't work with manifests), I'd like to document it here.

**Comment by jlewi** [comment]
@Bobgy Do you want to cite: kubeflow/manifests#538 once that is fixed newer versions of kustomize should work

**Comment by Bobgy** [comment]
@jlewi sure, thanks for sharing related context
added the reference

**Pull request merged**
