### PR TITLE
Cherry pick of #969 and #997: fix pipeline default sa

### PR DESCRIPTION
**Pull request by Bobgy**
**Which issue is resolved by this Pull Request:**
Part of https://github.com/kubeflow/kubeflow/issues/4803

**Description of your changes:**
Cherry pick of https://github.com/kubeflow/manifests/commit/ad38b41ae5dce1fd5c77a6c5f69d499c9c157718 and 
https://github.com/kubeflow/manifests/commit/9e6ef8681003c195560fb7b3b75211830c19b7a0

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

/assign @richardsliu @jlewi

### CODE REVIEW

**Comment by Bobgy** [comment]
@googlebot I consent

**Comment by jlewi** [comment]
I don't think this will resolve kubeflow/kubeflow#4803 as I believe we will need a new manifests release to make this available. I would suggest leaving the issue open until the release has been cut and the fix verified.

**Comment by Bobgy** [comment]
@jlewi I see, sounds good to me.

**Pull request merged**
