### PR TITLE
[Test] Remove stale ksonnet code

### LINKED ISSUE #1608: Remove use of ksonnet in tests
ksonnet was deprecated over a year ago the tests should no longer be using ksonnet to define tests.

Related to #774

### LINKED ISSUE #1708: [Test] Current test status in kubeflow/manifests repo
This issue serves as a summary and the main issue to talk about current test status.

**Summary**
Currently, kubeflow/manifests exist with 2 types of general-purpose tests, unit test and E2E test. 

1. Unit test: uses deprecated ksonnet to generate unit test Argo workflow (https://github.com/kubeflow/manifests/blob/master/prow_config.yaml#L9-L15)
2. E2E test: uses python generated E2E test Argo workflow (https://github.com/kubeflow/manifests/blob/master/prow_config.yaml#L16-L57)

More specific, 

1. Unit test's abstraction model: 
```
make tests
```
Detailed code here (https://github.com/kubeflow/manifests/blob/master/tests/scripts/run-tests.sh)

2. E2E test's abstraction model (same as kfctl):
```
1. Create EKS cluster
2. Deploy Kubeflow by kfctl
3. Test individual component's status
4. Only a few component's functionality check
5. Report test status and clean up
```
Detailed code here (https://github.com/kubeflow/kfctl/blob/master/py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py)

**TODO List:**
- [x] Create another section for kubeflow/manifests README called Test, which will introduce current test status and development.
- [ ] Migrate ksonnet unit test to python unit test

### PR DESCRIPTION
**Pull request by PatrickXYS**
**Which issue is resolved by this Pull Request:**
Resolves #1608
Resolves #1708 

**Description of your changes:**
1. Remove stale ksonnet unit test code and replace with Github Actions.
2. Generate doc organization by doctoc, which can help us find desired content in README efficiently.

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

##
###  Reason for using Github Actions for simple unit tests

Let's use Github Action for simple unit tests, and optional-test-infra is for E2E tests. We can benefits from this testing model by:

1. Simple Unit Tests: has nothing to do with container, only a set of syntax check and simple functionality check in bare-metal machine. Thus, it does not have to be running in container/pod.
2. E2E tests: optional-test-infra provide enough resources to make sure no PR will get queued, and also provide predined CI/CD workflow to make users easier to use. The pain point we want to solve is making sure that Kubeflow as a complex MLOps System works properly.

### CODE REVIEW

**Comment by PatrickXYS** [comment]
/hold

Hold until fine-tune tests

**Comment by PatrickXYS** [comment]
Go build failed for running out of memory

**Comment by PatrickXYS** [comment]
OOMKilled, let's do it in the nighttime

**Comment by PatrickXYS** [comment]
Let's use Github Action for simple unit tests, and optional-test-infra is for E2E tests. We can benefits from this testing model by:

1. Simple Unit Tests: has nothing to do with container, only a set of syntax check and simple functionality check in bare-metal machine. Thus, it does not have to be running in container/pod.
2. E2E tests: optional-test-infra provide enough resources to make sure no PR will get queued, and also provide predined CI/CD workflow to make users easier to use. The pain point we want to solve is making sure that Kubeflow as a complex MLOps System works properly.

**Review by theofpa — COMMENTED** [review]
thanks @PatrickXYS
/lgtm
/approve

**Comment by PatrickXYS** [comment]
@theofpa Can you help lgtm? Seems like reviewing with lgtm doesn't help

**Pull request merged**
