### PR TITLE
Change the Role verbs of a Profile user to prevent the user from getting a Profile

### LINKED ISSUE #52: Change the Role verbs of a Profile user to prevent the user from getting a Profile
The Role should be

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2019-05-05T15:25:10Z"
  labels:
    app.kubernetes.io/name: experiments
    kustomize.component: profiles
  name: profiles-role
  namespace: experiments
  resourceVersion: "3645969"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/experiments/roles/profiles-role
  uid: f8a2dd93-6f49-11e9-9bef-42010a8a01ef
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - profiles
  verbs:
  - create
  - watch
  - list
```

### PR DESCRIPTION
**Pull request by kkasravi**
fixes #52

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/76)

### CODE REVIEW

**Comment by jlewi** [comment]
Do we want users to be able to see all profiles?
I would normally do

```
kubectl create -f profile.yaml
kubectl get profiles
```

If users can't list profiles will that lead to a frustrating UX?

i.e. if a user forgets what they called their profile how would they do a list to see what it is?

**Comment by jlewi** [comment]
Why not get as well?

**Comment by kunmingg** [comment]
Shall we make it a ClusterRole since Profile is cluster-scope CRD?
And we can use a name like `profile-default` to indicate what it does?

**Pull request merged**
