### PR TITLE
Update kubeflow/kfp-tekton manifests from v2.0.3

### PR DESCRIPTION
**Pull request by yhwang**
**Description of your changes:**
To align with kfp 2.0.3, also update kfp-tekton to 2.0.3

**Checklist:**
- [x] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Review by Tomcli — COMMENTED** [review]
/lgtm

**Comment by yhwang** [comment]
@danisla, want to make sure this could be included in the final release. Do you know who could approve this before you cut the release?

**Comment by DnPlas** [comment]
hey @yhwang this will be included in the upcoming release. we just need @kimwnasptd's approval.

**Comment by yhwang** [comment]
> hey @yhwang this will be included in the upcoming release. we just need @kimwnasptd's approval.

Thanks for the confirmation.
The reason I want to double-check with you is that we already put kfp-tekton 2.0.3 in the release blog post. So I want to make sure this will be included in the v1.8.

**Pull request merged**
