### PR TITLE
Example of regenerating all tests

### PR DESCRIPTION
**Pull request by Bobgy**
**Which issue is resolved by this Pull Request:**
Example of problem met in https://github.com/kubeflow/manifests/pull/712

**Description of your changes:**
I ran
* `cd manifests/tests`
* `make generate`
* `make test`

I regenerate test cases for https://github.com/kubeflow/manifests/blob/9aae81d93b78b3fe802527b084530672f39e2b1a/metadata/base/metadata-envoy-deployment.yaml, but some metadata tests are generated differently than in master and the tests fail.
```
--- FAIL: TestMetadataBase (0.01s)
    metadata-base_test.go:325: Err: env source files: [grpc-params.env]: cannot read file "/manifests/metadata/base/grpc-params.env"
=== RUN   TestMetadataOverlaysApplication
--- FAIL: TestMetadataOverlaysApplication (0.01s)
    metadata-overlays-application_test.go:382: Err: accumulating resources: recursed accumulation of path '../../base': env source files: [grpc-params.env]: cannot read file "/manifests/metadata/base/grpc-params.env"
=== RUN   TestMetadataOverlaysDb
--- FAIL: TestMetadataOverlaysDb (0.01s)
    metadata-overlays-db_test.go:508: Err: accumulating resources: recursed accumulation of path '../../base': env source files: [grpc-params.env]: cannot read file "/manifests/metadata/base/grpc-params.env"
=== RUN   TestMetadataOverlaysIbmStorageConfig
--- FAIL: TestMetadataOverlaysIbmStorageConfig (0.01s)
    metadata-overlays-ibm-storage-config_test.go:335: Err: accumulating resources: recursed accumulation of path '../../base': env source files: [grpc-params.env]: cannot read file "/manifests/metadata/base/grpc-params.env"
=== RUN   TestMetadataOverlaysIstio
--- FAIL: TestMetadataOverlaysIstio (0.01s)
    metadata-overlays-istio_test.go:387: Err: accumulating resources: recursed accumulation of path '../../base': env source files: [grpc-params.env]: cannot read file "/manifests/metadata/base/grpc-params.env"
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/716)

### CODE REVIEW

**Comment by Bobgy** [comment]
@jlewi I want to change metadata manifests too in https://github.com/kubeflow/manifests/pull/712.

How should I workaround this issue? By manually editing generated tests?

**Comment by jlewi** [comment]
@Bobgy Could you explain why generating the tests for the metadata manifests produces tests that don't pass?

if that's not generating tests then we need to fix it. Manually editing the tests doesn't seem sustainable.

**Comment by Bobgy** [comment]
I don't know. It seems tests in master is no longer in sync with generated one.

**Comment by jlewi** [comment]
@Bobgy can you explain what the test failure is? What is the expected and actual value in the test failure? 

Is the expected value incorrect? What should the expected value be and what is it?

**Comment by Bobgy** [comment]
Error messages in https://github.com/kubeflow/manifests/pull/716#issue-364636246 seem to tell `/manifests/metadata/base/grpc-params.env` is expected to exist during the test.

Looking at generated test difference, the line that creates grpc-params.env is deleted when regenerating tests:
https://github.com/kubeflow/manifests/pull/716/files#diff-2120380e7a612782255ef2e9d2bfd2bfL305

That seems to be the root cause.

@jlewi who is owner for test generator? Either I used an outdated test generator version, or there is a bug in it.

**Comment by Bobgy** [comment]
@jlewi friendly ping, who can I talk to for the test generator issue?

**Comment by Bobgy** [comment]
/close
Superceded by https://github.com/kubeflow/manifests/pull/804

**Pull request closed without merging**
