### PR TITLE
Add optional Knative eventing component

### LINKED ISSUE #1256: Should the Knative component also include eventing as an optional overlay?
/questions
KFServing has use cases for drift and outlier detection that utilize Knative eventing. Should we also maintain the eventing deployment as overlay, so it's align with the our Knative setup?

### PR DESCRIPTION
**Pull request by Tomcli**
**Which issue is resolved by this Pull Request:**
Resolves #1256 

**Description of your changes:**
Add Knative eventing component as an option because there are several KFServing logger use cases that require Knative eventing to trigger the message dumper.

To add Knative eventing as part of the Kubeflow deployment, simply add the `knative/installs/eventing` as part of the kfdef. It also can work for kustomize v3 as well.

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by cliveseldon** [comment]
@Tomcli This is great.
I don't see any tests in changed files. Did you run generate tests?
Apart from that looks good.

**Comment by Tomcli** [comment]
@cliveseldon Thanks. I forgot to update the test kustomization for the knative eventing. I added the tests now in my latest commit.

**Comment by cliveseldon** [comment]
@Tomcli You might need to get someone else to approve as not sure I can

**Pull request merged**
