### PR TITLE
kustomize 5.2.1

### PR DESCRIPTION
**Pull request by juliusvonkohout**
@rimolive 

https://github.com/kubeflow/manifests/pull/2653

### CODE REVIEW

**Comment by diegolovison** [comment]
I saw that you put a hold comment
Just a reminder

If we are going to start supporting kustomize 5.x.x from this PR, I would like to ask to change:

https://github.com/kubeflow/manifests/blob/master/tests/gh-actions/install_kustomize.sh
https://github.com/kubeflow/manifests#prerequisites
https://github.com/kubeflow/manifests/blob/master/.github/pull_request_template.md

**Comment by juliusvonkohout** [comment]
> I saw that you wrote a hold comment Just a reminder
> 
> If we are going to start supporting kustomize 5.x.x from this PR, I would like to ask to change:
> 
> https://github.com/kubeflow/manifests/blob/master/tests/gh-actions/install_kustomize.sh https://github.com/kubeflow/manifests#prerequisites https://github.com/kubeflow/manifests/blob/master/.github/pull_request_template.md

yes, i am closing this one.

**Comment by juliusvonkohout** [comment]
@AndersBennedsgaard [manifests/common/knative/README.md](https://github.com/kubeflow/manifests/blob/68652a1b0262378e823f58b1d07bfb8d7a8be006/common/knative/README.md?plain=1#L40) should be updated in your PR. Yes go is not needed it seems, but i used the version form kubeflow/pipelines

**Comment by juliusvonkohout** [comment]
CC @kubeflow/release-team
@kubeflow/release-managers 

/hold

**Review by AndersBennedsgaard — APPROVED** [review]

**Review by diegolovison — APPROVED** [review]

**Comment by rimolive** [comment]
/lgtm

Let's sync with the WGs that the new dependency version for kustomize is 5.2.1

**Pull request merged**
