### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tiansiyuan**
**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**

Put the answer of the 2ed question of FAQ into a separate line.

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 5.0.3**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
CC @diegolovison

**Review by diegolovison — APPROVED** [review]

**Comment by juliusvonkohout** [comment]
I think this was fixed in master in another PR recently.

**Comment by juliusvonkohout** [comment]
This is already updated in the master and neither CLA nor DCO are signed.

**Comment by juliusvonkohout** [comment]
@tiansiyuan 
Please join the slack channel wg-manifests and our regaular meetings (tomorrow as well) if you want to propose new things

https://www.kubeflow.org/docs/about/community/

**Pull request closed without merging**
