### PR TITLE
Add Abhilash to MPIJob manifests maintainers

### PR DESCRIPTION
**Pull request by terrytangyuan**
**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**
/cc @stpabhi @swiftdiaries 

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by Jeffwan** [comment]
This is used for tracking application owners. User there still can not approve PRs. I am not sure you just want to track that or need fine grain control.

**Comment by terrytangyuan** [comment]
@Jeffwan Thanks for the note! My initial thought was just to track the contact information in case there are any maintenance requests in the future and others know how/who to reach out to.

**Comment by Jeffwan** [comment]
@terrytangyuan Yeah, Got you. Then the PR is good enough.

/retest
/lgtm

**Pull request merged**
