### PR TITLE
Copy istio to its own package

### LINKED ISSUE #115: move istio components into their own package
since istio can be installed w/o a platform we should move the istio components into an istio package

### PR DESCRIPTION
**Pull request by lluunn**
**Which issue is resolved by this Pull Request:**
First step for #115

**Description of your changes:**
Move istio to its own package (from gcp)

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

/cc @jlewi @kkasravi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/205)

### CODE REVIEW

**Comment by johnugeorge** [comment]
Shouldn't this PR be required for 0.6 release ?

**Comment by lluunn** [comment]
The test cannot pass since I need to update the config in kubeflow/kubeflow at the same time...
https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/base/kfctl_default.yaml

**Comment by jlewi** [comment]
@lluunn Can you break this into multiple PRs

1. PR create ISTIO package in the new location
1. Update kubeflow/kubeflow
1. Delete old package

**Comment by lluunn** [comment]
updated, thanks

**Pull request merged**
