### PR TITLE
Update kubeflow/model-registry manifests from v0.2.0-alpha

### PR DESCRIPTION
**Pull request by rimolive**
**Which issue is resolved by this Pull Request:**
Supersedes #2694

**Description of your changes:**

**Checklist:**
- [x] Unit tests pass:
  **Make sure you have installed kustomize == 5.2.1+**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
We should update the model registry synchronization script in line with https://github.com/kubeflow/manifests/pull/2698

**Comment by lampajr** [comment]
Thanks @rimolive, note that the manifests README and OWNERS files that have been added with https://github.com/kubeflow/model-registry/pull/69 were not included in `v0.2.0-alpha` tag yet (as the PR has been merged yesterday).

As temporary solution, if really needed, we could add them manually as part of this PR. Wdyt?

**Comment by rimolive** [comment]
@lampajr Done

**Review by lampajr — APPROVED** [review]

**Comment by rimolive** [comment]
/hold

Found an issue in the sync script.

**Comment by rimolive** [comment]
cc @juliusvonkohout

**Pull request merged**
