### PR TITLE
Remove Jupyterhub kustomize manifest

### LINKED ISSUE #116: Delete JupyterHub kustomize manifest
It looks like
https://github.com/kubeflow/manifests/tree/master/jupyter/jupyter

is providing a manifest for jupyterhub.

But jupyterhub was removed in 0.5.

I suggest deleting that manifest to avoid confusion about whether jupyterhub is supported or not.

@ashahba Interested?

### PR DESCRIPTION
**Pull request by whiletruelearn**
**Which issue is resolved by this Pull Request:**
Resolves #116

**Description of your changes:** Removing the entire `jupyter/jupyter` directory

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

@jlewi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/234)

### CODE REVIEW

**Comment by whiletruelearn** [comment]
I signed it!

**Comment by whiletruelearn** [comment]
@jlewi the build seems to have failed. Any pointers for fix ?

**Comment by kkasravi** [comment]
do a rebase with master, there is an error in istio-base_test.go

git fetch upstream master
git rebase -i upstream/master
cd tests
make generate
make test 
git commit -a
git push

**Comment by jlewi** [comment]
@whiletruelearn The commit history on this PR looks messed up. Not sure why 130 files are being listed as changed.

I think you need to do a rebase on master and only include your changes.

**Comment by jlewi** [comment]
@whiletruelearn would be great to get this fixed and merged.

**Comment by whiletruelearn** [comment]
@jlewi , i am not quite sure how to fix the PR issue. I am going to close this PR and raise another one with the fix. sorry for the delay

**Pull request closed without merging**
