### PR TITLE
Add katib ClusterRoles for notebooks

### PR DESCRIPTION
**Pull request by hougangliu**
**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**

**Checklist:**
- [ ] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/471)

### CODE REVIEW

**Comment by johnugeorge** [comment]
Is this duplicate of #448?

**Comment by hougangliu** [comment]
> Is this duplicate of #448?

Yes, duplicated

**Pull request closed without merging**
