### PR TITLE
Fix a typo in the overlay of metadata's external-mysql

### PR DESCRIPTION
**Pull request by axelborja**
**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**
Fix typo

**Checklist:**
- [ ] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by axelborja** [comment]
Any news on this one ?

**Comment by axelborja** [comment]
@Jeffwan what do you think?

**Comment by PatrickXYS** [comment]
@axelborja Any reason we have to patch it in v1.0-branch, I have no objection on it, just wondering why not we fix master instead?

**Comment by axelborja** [comment]
We are currently using manifest from the `v1.0-branch`, that's why I patched it in v1 branch.

**Comment by PatrickXYS** [comment]
@axelborja Given no one is maintaining v1.0-branch, I would suggest to first merge it in master and then cherry-pick into v1.0-branch.

**Comment by axelborja** [comment]
Ok : 👌

**Comment by axelborja** [comment]
I just opened the following PR: https://github.com/kubeflow/manifests/pull/1702 (based on master)

I am closing this one.

**Pull request closed without merging**
