### PR TITLE
Updates Istio to 1.2.5 release

### LINKED ISSUE #283: Upgrade Istio to 1.2+
/area manifests
/priority p1

Istio manifests in master branch are at 1.1.6. It would be good to upgrade them to 1.2.4 so that few issues get resolved:

kiali/kiali#1154

/assign @lluunn 
/assign @krishnadurai 

Related Issues:
#281

### PR DESCRIPTION
**Pull request by krishnadurai**
**Which issue is resolved by this Pull Request:**
Resolves #283 

**Description of your changes:**
Updating Istio to its latest version.

TODO:
- [x] Update CRDs
- [x] Update Istio-Install
- [x] Update unit tests
- [x] Manual tests for Istio impacted features

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

/hold

/cc @lluunn 
/assign @krishnadurai

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/323)

### CODE REVIEW

**Comment by krishnadurai** [comment]
/cc @kkasravi 

I'm looking to update Istio to 1.2.5.
PTAL.

**Comment by krishnadurai** [comment]
I'll remove the WIP label as soon as I test this manually for GCP multi-user workflows.

**Comment by krishnadurai** [comment]
Unable to access the centraldashboard through GKE IAP envoy-ingress. Looks like the backend service is failing for istio-ingress gateway.
CentralDashboard is accessible on an on-premise server. Notebooks and Profile are working.

**Comment by krishnadurai** [comment]
> Unable to access the centraldashboard through GKE IAP envoy-ingress. Looks like the backend service is failing for istio-ingress gateway.

Centraldashboard is now accessible for GKE IAP. Tested this against master's kfctl_gcp_iap.yaml.

TODO:
- [ ] MultiUser Profiles and Notebooks test

**Comment by krishnadurai** [comment]
@lluunn and @kkasravi I've tested this PR with all known Istio affected scenarios manually. Could you see if this is ready for an upgrade?

**Comment by krishnadurai** [comment]
@lluunn @kkasravi I'm circling back in here to see if this can be merged soon before the 0.7 release. Can you please review this once?

**Comment by lluunn** [comment]
thanks!

**Comment by kkasravi** [comment]
@krishnadurai @jlewi @lluunn 

I believe we're going to revert this - Krishna and I are seeing some presubmit failures. For #355 the unit test for istio-install-base_test.go isn't generated. 

I've opened an issue on the error in generating unit-test #356

**Pull request merged**
