### PR TITLE
Istio 1.22.1

### PR DESCRIPTION
**Pull request by juliusvonkohout**
# Pull Request Template for Kubeflow manifests Issues

- Please include a summary of changes and the related issue. 
- List any dependencies that are required for this change. 
- Please delete the options that are not relevant.
- The following checklist will help you to satisfy the requirements.

## ✏️ A brief description of the changes
Istio 1.22.1

  
## ✅ Unit Test Checklist
  
  - [x] 🛠️ Make sure you have installed kustomize == 5.2.1+     
  - [ ] ✍️ Have you written new tests for your core changes, as applicable?      
  - [x] 🔄 Have you successfully run existing tests with your changes ?    
  - [x] 🚀 Have you successfully run existing and new tests with your changes ?

## ✅ Contributor checklist
  - [ ] All the commits have been _signed-off_  (To pass the `DCO` check)
  - [x] Submit the [Contributor License Agreements](https://cla.developers.google.com/clas) (To pass the `cla/google` check)

---     
 
> You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
Cc @rimolive

/approve

**Comment by rimolive** [comment]
There are merge conflicts. Would you mind rebase?

**Comment by juliusvonkohout** [comment]
@rimolive rebase is done

**Pull request merged**
