### PR TITLE
Update oauth2-proxy readme for Keycloak

### PR DESCRIPTION
**Pull request by juliusvonkohout**
# Pull Request Template for Kubeflow manifests Issues

https://github.com/kubeflow/manifests/issues/2931#issuecomment-2544252821

## ✅ Contributor checklist
  - Make sure you have tested with kustomize. See [Installation Prerequisites](https://github.com/kubeflow/manifests#prerequisites)
  - All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

---     
 
> You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
https://cloud-native.slack.com/archives/C073W572LA2/p1733818844895669
Hailey are you sure about
skip_auth_routes = [
      "^/oauth2/callback",
    ]
? Please test again and review / comment on https://github.com/kubeflow/manifests/pull/2934

**Comment by juliusvonkohout** [comment]
CC @kromanow94

**Comment by juliusvonkohout** [comment]
"[@Julius von Kohout](https://cloud-native.slack.com/team/U06LW431SJF)
 I tried removing that line but it still worked. When I first tried without this, I couldn't access to the dashboard, but this time I could without it. I'm not sure it is the thing that really matters. I figured I should find other factors."

**Comment by kromanow94** [comment]
Just a hunch - maybe it was connected to Istio where it needs some time to refresh it's settings from the cache and populate to the istio-proxy containers (or istio-cni). This action is done by `istiod`. I usually give it like 10 seconds before testing changes in configuration.

**Pull request closed without merging**
