### PR TITLE
Update jupyter web app image tag for Azure Stack

### PR DESCRIPTION
**Pull request by berndverst**
**Which issue is resolved by this Pull Request:**
Resolves #1645

**Description of your changes:**
Updates hardcoded image tag for Jupyter Web App in Azure Stack

**Checklist:**
- [X] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@berndverst you might want to consider just not defining it in your `kustomization.yaml`, and instead delegating to the `base_v3`, so that you don't get out of sync in the future.

**Comment by Jeffwan** [comment]
> @berndverst you might want to consider just not defining it in your `kustomization.yaml`, and instead delegating to the `base_v3`, so that you don't get out of sync in the future.

@thesuperzapper Agree. If platform like to do that way, they will need to be responsible for the reliability. As WG owners, it's hard to understand what version platform owners want. It's possible user want more reliable version. :D

**Comment by Jeffwan** [comment]
@berndverst Do you need this in v1.2-branch? If so, can you help cherry-pick the changes?

**Pull request merged**
