### PR TITLE
Automated cherry pick of #949: Adds kfserving ingressgateway for Istio 1.1.6 Modifies Cherry pick of #949 on v1.0-branch. #949: Adds kfserving ingressgateway for Istio 1.1.6 Modifies

### PR DESCRIPTION
**Pull request by richardsliu**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/1027)

### CODE REVIEW

**Comment by richardsliu** [comment]
@krishnadurai Please verify consent for this PR.

**Comment by krishnadurai** [comment]
@googlebot I consent.

**Pull request merged**
