### PR TITLE
readme: Use verify=false for the one-liner

### PR DESCRIPTION
**Pull request by kimwnasptd**
Refs https://github.com/kubeflow/manifests/issues/2133#issuecomment-1040428877

We should remove the `--validate=false` flag once https://github.com/kubeflow/pipelines/pull/7311 is merged and the KFP manfiests are updated to include the fix

cc @juliusvonkohout

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
It is already merged so you should rather go for a straight fix.

**Comment by chensun** [comment]
> It is already merged so you should rather go for a straight fix.

Yes, the change was merged and released in KFP 1.8.0: https://github.com/kubeflow/pipelines/releases/tag/1.8.0

**Comment by kimwnasptd** [comment]
Thanks for the update!

@chensun then does this mean I can also use the newest `1.8.0` tag for KFP? I've been using the `1.8.0-rc.2` in the manifests repo until this point.

**Comment by chensun** [comment]
> Thanks for the update!
> 
> @chensun then does this mean I can also use the newest `1.8.0` tag for KFP? I've been using the `1.8.0-rc.2` in the manifests repo until this point.

Yes, please do test out KFP 1.8.0.

**Comment by kimwnasptd** [comment]
Closing this PR then, in favor of updating to `1.8.0` tag

**Pull request closed without merging**
