### PR TITLE
Adds Azure Stack Tests

### PR DESCRIPTION
**Pull request by berndverst**
**Which issue is resolved by this Pull Request:**
Follow up from #1633 which was merged without tests 🤷‍♂️ 

**Description of your changes:**
This slightly refactors an optional overlay of the Azure stack so that test generation succeeds. All tests now pass.
This PR also adds all Azure stacks tests.

**Checklist:**
- [X] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by berndverst** [comment]
@pvaneck I finally got the tests all added and working.

**Review by pvaneck — APPROVED** [review]
Thanks!

**Comment by berndverst** [comment]
@Jeffwan would you mind approving this PR as an owner of kfdef and tests?

The kfdef didn't change other than a folder rename.
Tests were auto generated successfully and now all work (unlike head of master).

Thanks!

**Pull request merged**
