### PR TITLE
Automated cherry pick of #1335: added support for registration flow env variable Cherry pick of #1335 on v1.1-branch. #1335: added support for registration flow env variable

### PR DESCRIPTION
**Pull request by lalithvaka**

### CODE REVIEW

**Comment by lalithvaka** [comment]
@maganaluis Can you please provide your consent by commenting on these pull request with "@googlebot I consent".

**Comment by maganaluis** [comment]
@lalithvaka Thank you, I was checking the version of the image tag and it's using vmaster-gf39279c0 which was created prior my PR. We would need this to use vmaster-g1e0cf04b which is the latest image created on June. Could we incorporate that into your PR?

**Comment by lalithvaka** [comment]
@maganaluis , I followed the cherry pick process by specifying the upstream release name(upstream/v1.1-branch) and the PR number. Beyond that, I don't think we can control or specify which image.

**Comment by maganaluis** [comment]
@jlewi We need to update the central dashboard image to use the latest tag ```vmaster-g1e0cf04b```, do we need to submit a separate PR and cherry pick that as well?

**Comment by jlewi** [comment]
Images should be auto-updated and built

1. Was the change to the source code cherry-picked onto the 1.1 branch of kubeflow/kubeflow?
1.  Once it is that should trigger an auto-update PR
https://github.com/kubeflow/kubeflow/pulls?q=is%3Apr+author%3Akubeflow-bot+is%3Aclosed

**Comment by maganaluis** [comment]
@googlebot I consent

**Comment by jlewi** [comment]
/hold

@lalithvaka Does the image need to be updated before this PR is merged?

**Comment by lalithvaka** [comment]
> Images should be auto-updated and built
> 
> 1. Was the change to the source code cherry-picked onto the 1.1 branch of kubeflow/kubeflow?
> 2. Once it is that should trigger an auto-update PR
>    https://github.com/kubeflow/kubeflow/pulls?q=is%3Apr+author%3Akubeflow-bot+is%3Aclosed

@jlewi  Yes - I have submitted a [cherry pick](https://github.com/kubeflow/kubeflow/pull/5120) to the source code on kubeflow/kubeflow - pending approval. Can you please help approve that as well?

**Comment by jlewi** [comment]
@lalithvaka please keep an eye on that PR and check whether the image is auto-rebuilt and then approve the PR before merging this PR.

**Comment by lalithvaka** [comment]
@jlewi , per @maganaluis this is good to move forward. Can you please unblock this cherry pick to merge? Thank you.

**Comment by yanniszark** [comment]
Image is updated with PR: https://github.com/kubeflow/manifests/pull/1378
/hold cancel
/approve
/lgtm

**Comment by lalithvaka** [comment]
@maganaluis , not sure what failed here. Can you please check?

**Comment by maganaluis** [comment]
@lalithvaka Can you revert the latest commit on your fork?

**Comment by maganaluis** [comment]
@lalithvaka Looks good now, no conflicts and all tests passed. Needs the lgtm label again.

**Pull request merged**
