### PR TITLE
Add User Management Scripts documentation

### PR DESCRIPTION
**Pull request by choudhryfrompak**
# Pull Request Template for Kubeflow manifests Issues

## ✅ Contributor checklist
  - [x] Make sure you have tested with kustomize. See [Installation Prerequisites](https://github.com/kubeflow/manifests#prerequisites)
    - This PR only modifies documentation and does not affect kustomize configurations.
  - [x] All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)
    - I confirm that I have signed off all commits in this PR.

---     
 
> You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### CODE REVIEW

**Comment by choudhryfrompak** [comment]
This pull request is related to a recent pull request from this account. Following the guidelines provided by @juliusvonkohout

**Comment by juliusvonkohout** [comment]
Hello, we will not link to the scripts in your private repository. We will also not add stuff that is a large maintenance burden. You should instead use a proper oidc provider with DEX as mentioned before.

**Comment by choudhryfrompak** [comment]
@juliusvonkohout  This is an optional add-on or plugin designed for users deploying Kubeflow on-premise within an organization. We are also utilizing it within our own organization. It facilitates the local creation of user accounts for team members in such environments.

While your reasoning is valid, I have decided to maintain it as a separate repository to keep things organized.

Thank you for your consideration.

**Comment by choudhryfrompak** [comment]
@juliusvonkohout  This is an optional add-on or plugin designed for users deploying Kubeflow on-premise within an organization. We are also utilizing it within our own organization. It facilitates the local creation of user accounts for team members in such environments.

While your reasoning is valid, I have decided to maintain it as a separate repository to keep things organized.

Thank you for your consideration.

**Comment by juliusvonkohout** [comment]
Do you want to work on Dex integration documnetation then?

**Comment by juliusvonkohout** [comment]
superseded by https://github.com/kubeflow/manifests/pull/2911

**Pull request closed without merging**
