### PR TITLE
Unpin from GKE 1.14.6-gke.2; 1.14.6 is no longer a valid master.

### PR DESCRIPTION
**Pull request by jlewi**
Related to kubeflow/manifests#508

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/577)

### CODE REVIEW

**Comment by jlewi** [comment]
I verified that using a 1.14.7 cluster gcloud auth list works

Output of running `gcloud auth list` in a notebook

```
                    Credentialed Accounts
ACTIVE  ACCOUNT
*       kftest-1025-151315-user@jlewi-dev.iam.gserviceaccount.com
```


Using

```
Kubeflow/kubeflow: v0.7.0-rc.6
kubeflow/manifests:  fix_kfserving@4c066f1c7a56c5adeeb329794241ceb256fc46c4
```
  
Confirmation about the cluster.

```
Cluster is 1.14.7
kftest-1025-151315  us-east1-d  1.14.7-gke.14   34.73.151.99    n1-standard-8  1.14.7-gke.14  2          RUNNING
```

**Comment by lluunn** [comment]
should we cherrypick this?

**Comment by lluunn** [comment]
seems 0.7 has the fix:
https://github.com/kubeflow/manifests/blob/v0.7-branch/gcp/deployment_manager_configs/cluster-kubeflow.yaml#L34

**Pull request merged**
