### PR TITLE
Cherry Pick of KF 1.3 on Openshift (#1811)

### PR DESCRIPTION
**Pull request by LaVLaS**
* KF 1.3 on Openshift

* Adding fixes for pipeline portal and istio permissions

* Adding no auth to jupyter webapp and work around for Could not find CSRF

* Adding openshift istio-1-9-0

* Adding Virtual Service for pipelines

* Adding k8sapi for pipeline

* Updates to katib and kfdef

* Adding Katib

* Adding kfdef

* Fixing uri in kfptekton kfdef

* Addind gprc for pipeline

* Adding note for profile image

* Adding Volume

* Adding volumes web app

* Adding Volume

* Adding no auth to get rid of no user detected

* Fixing dep name

* Fixing dep name

* Fixing volume-web-app

* Adding Volume

* Adding KFP Tekton

* Adding scc for kf-tekton

* Rearranging apps in example kfdef

* Adding the env to eliminate double menu

* Adding owners

**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by yanniszark** [comment]
@LaVLaS could you amend the commit message and remove this line: `Co-authored-by: Juana Nakfour <nakfour>`
The cla bot is malfunctioning a lot lately.

**Comment by yanniszark** [comment]
@LaVLaS we need @nakfour to comment `@googlebot I consent.`
Alternatively, you can use `git commit --amend --author="Author Name <email@address.com>"` (replacing the author details with yours) in order to bypass the cla bot.

**Comment by LaVLaS** [comment]
@yanniszark Updated the commit and PR description just in case.

@nakfour You may need to sign off on this

**Comment by nakfour** [comment]
@googlebot I consent.

**Pull request merged**
