### PR TITLE
Hardware Prerequisites

### PR DESCRIPTION
**Pull request by diegolovison**
**Which issue is resolved by this Pull Request:**
Information about the minimum hardware to run Kubeflow locally

**Description of your changes:**
Information about the minimum hardware to run Kubeflow locally

**Checklist:**
- [ x ] Unit tests pass:
  **Make sure you have installed kustomize == 5.2.1+**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
Can you add "Recommended" ?

**Comment by juliusvonkohout** [comment]
you need to sign the DCO Otherwise
/lgtm

**Comment by diegolovison** [comment]
@juliusvonkohout I did a rebase and a force push

**Pull request merged**
