### PR TITLE
fix application specs

### PR DESCRIPTION
**Pull request by thesuperzapper**
**Description of your changes:**
* ensure descriptor field is correctly set
* ensure addOwnerRef=true

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@krishnadurai I don't really understand what is failing

**Comment by thesuperzapper** [comment]
@krishnadurai can you please review?

**Comment by thesuperzapper** [comment]
@krishnadurai @johnugeorge these very basic bugs are still in the YAML, can we please get this merged to fix these?

The current YAML structure is simply incorrect, (in addition to the missing `addOwnerRef`).

**Comment by thesuperzapper** [comment]
@Jeffwan @krishnadurai gentle ping, this bug is really simple, I would really appreciate if you can review it.

**Review by krishnadurai — APPROVED** [review]
/lgtm
/approve

**Comment by thesuperzapper** [comment]
@jeffwan only waiting on you now :)

**Comment by thesuperzapper** [comment]
@terrytangyuan you can also approve the final remaining change because you are in `mpi-job/OWNERS`

**Review by terrytangyuan — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
