### PR TITLE
Also use hashFromEnv for oauth2-proxy overlay

### PR DESCRIPTION
**Pull request by codablock**
**Description of your changes:**
Same as cd991e6010a8c694a729d2978f4c8be597669fff

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 5.2.1+**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by kromanow94** [comment]
I deployed this on kind + WSL on my local environment. I confirm  the `dex` is working properly.

Thanks for taking care of this.

**Comment by juliusvonkohout** [comment]
/hold 

CC @diegolovison since we might need to update the main readme.md documentation.

**Comment by diegolovison** [comment]
Hi. I am not familiar with that code change. In the readme there are 3 entries with `12341234`

What exactly this code is changing?

**Comment by kromanow94** [comment]
@diegolovison it's about referencing the same value from env instead of providing as plaintext. It's more secure. Please see:

[common/dex/base/dex-passwords.yaml](https://github.com/kubeflow/manifests/blob/master/common/dex/base/dex-passwords.yaml)

**Comment by diegolovison** [comment]
The values match. I don't see any changes in the readme

**Comment by juliusvonkohout** [comment]
https://github.com/kubeflow/manifests/commit/cd991e6010a8c694a729d2978f4c8be597669fff helped a lot with the decision :-D

/lgtm
/approve

**Pull request merged**
