### PR TITLE
change ray version and enable auto scaling

### PR DESCRIPTION
**Pull request by hansinikarunarathne**
# Pull Request Template for Kubeflow manifests Issues

## ✅ Contributor checklist
  - Make sure you have tested with kustomize. See [Installation Prerequisites](https://github.com/kubeflow/manifests#prerequisites)
  - All the commits have been _signed-off_  (To pass the `DCO` check)
  - Submit the [Contributor License Agreements](https://cla.developers.google.com/clas) (To pass the `cla/google` check)

---     
 
> You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
There could be more outdated stuff that we should replace with upstream stuff.

For example this looks interesting. Maybe busybox is outdated.
```
        - name: init
          image: busybox:1.36
          # Change the cluster postfix if you don't have a default setting
          command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for K8s Service $RAY_IP; sleep 2; done"]
```

**Comment by juliusvonkohout** [comment]
I think 

Ray seems to have documentation for istio support now https://github.com/ray-project/ray/pull/44801
https://github.com/ray-project/kuberay/issues/1005
https://github.com/ray-project/kuberay/pull/2117

Istio is something for a second PR. lets do a thorough cleanup here first and merge

**Comment by hansinikarunarathne** [comment]
> There could be more outdated stuff that we should replace with upstream stuff.
> 
> For example this looks interesting. Maybe busybox is outdated.
> 
> ```
>         - name: init
>           image: busybox:1.36
>           # Change the cluster postfix if you don't have a default setting
>           command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for K8s Service $RAY_IP; sleep 2; done"]
> ```

can you elobrate on this comment more. It is little confusing

**Comment by hansinikarunarathne** [comment]
> There could be more outdated stuff that we should replace with upstream stuff.
> 
> For example this looks interesting. Maybe busybox is outdated.
> 
> ```
>         - name: init
>           image: busybox:1.36
>           # Change the cluster postfix if you don't have a default setting
>           command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for K8s Service $RAY_IP; sleep 2; done"]
> ```

Can we update the ray cluster yaml as this with using a headless service?
https://docs.ray.io/en/latest/cluster/kubernetes/k8s-ecosystem/istio.html#step-4-create-the-raycluster

I started to go through the documents but did not find any clue as to what you were saying.

**Comment by juliusvonkohout** [comment]
yes, just try something out :-)

**Pull request merged**
