### PR TITLE
[Central-Dashboard v2] Stable Release - Version and Profile-Server fixes

### PR DESCRIPTION
**Pull request by avdaredevil**
## About
Updated version to include fixes from correct versioning and profile communication

### Meta
/area centraldashboard
/area front-end
/priority p1
/assign @avdaredevil
/cc @prodonjs @gabrielwen @abhi-g

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/310)

### CODE REVIEW

**Comment by avdaredevil** [comment]
@jlewi @abhi-g The Prow job keeps getting stuck with no output, please advise. I'm waiting for this to get merged so @gabrielwen can make the cherrypick to `v0.6-branch`

**Comment by abhi-g** [comment]
Failure looks unrelated to the PR:
 Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kus
tomize:  (kubeflow.error): Code 500 with message: couldn't create resources from seldon-core-operator Error: StatefulSet in version "v1"
cannot be handled as a StatefulSet: v1.StatefulSet.Spec: v1.StatefulSetSpec.VolumeClaimTemplates: []v1.PersistentVolumeClaim: decode slic
e: expect [ or n, but found {, error found in #10 byte of ...|mplates":{"metadata"|..., bigger context ...|bhook-server-secret"}}]}},"vol
umeClaimTemplates":{"metadata":{"labels":{"app.kubernetes.io/component|...
util.py                     71 INFO     Usage:
util.py                     71 INFO     kfctl apply [all(=default)|k8s|platform] [flags]
util.py                     71 INFO
util.py                     71 INFO     Flags:
util.py                     71 INFO     -h, --help      help for apply
util.py                     71 INFO     -V, --verbose   verbose output default is false
util.py                     71 INFO
util.py                     71 INFO     couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:
  (kubeflow.error): Code 500 with message: couldn't create resources from seldon-core-operator Error: StatefulSet in version "v1" cannot
be handled as a StatefulSet: v1.StatefulSet.Spec: v1.StatefulSetSpec.VolumeClaimTemplates: []v1.PersistentVolumeClaim: decode slice: expe
ct [ or n, but found {, error found in #10 byte of ...|mplates":{"metadata"|..., bigger context ...|bhook-server-secret"}}]}},"volumeClai
mTemplates":{"metadata":{"labels":{"app.kubernetes.io/component|...
generated xml file: /mnt/test-data-volume/kubeflow-manifests-presubmit-kfctl-go-310-b1946cc-4128-5635/output/artifacts/junit_kfctl-build-
testiap-istio.xml

**Pull request merged**
