### PR TITLE
Updating istio to v1.11 to support Kubernetes 1.22

### LINKED ISSUE #1979: Manifests not ready for K8s 1.22
/kind bug

With the new Kubernetes 1.22 release, some APIs have been removed: https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/

Many manifests in this repository are still using some of these APIs and won't work for this release. 

For example, the following CRDs are still using `apiextensions.k8s.io/v1beta1` and are causing issues with the Charmed Kubeflow distribution:
```
authcodes.dex.coreos.com
sparkapplications.sparkoperator.k8s.io
```

### PR DESCRIPTION
**Pull request by nakfour**
**Which issue is resolved by this Pull Request:**
Resolves #1979

**Description of your changes:**
This updates istio to v1.11.0 in an effort to get. Kubeflow to install on Kubernetes 1.22 that limits apiVersion to v1.

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by chingandy** [comment]
@nakfour I tried to deploy kubeflow with your fork and the branch "updating-to-istio-1.11", but I couldn't deploy it successfully. I keep getting this error message. 

`error validating “STDIN”: error validating data: ValidationError(EnvoyFilter.spec.configPatches[0]): unknown field “listener” in io.istio.networking.v1alpha3.EnvoyFilter.spec.configPatches;`

Do you have any idea what this is about and how I can resolve this?

**Comment by nakfour** [comment]
@chingandy this looks similar to this issue: https://github.com/istio/istio/issues/34219
I have not seen this error. I will test again with different Kubernetes versions

**Comment by MatthiasCarnein** [comment]
@chingandy I believe this will be fixed by #2073 or #1990

**Comment by kimwnasptd** [comment]
@nakfour thank you for the PR! But, the files introduced in it are not following the instructions we had.

I ended up merging #2090 though, which placed the files in the correct places, so we have Istio 1.11! 

I think we can close this PR

**Comment by nakfour** [comment]
@kimwnasptd yes sounds good, thank you

**Pull request closed without merging**
