### PR TITLE
Bump KFP to 0.5.0

### PR DESCRIPTION
**Pull request by eedorenko**
Resolves https://github.com/kubeflow/pipelines/issues/3441
                https://github.com/kubeflow/pipelines/issues/2237
                https://github.com/kubeflow/manifests/issues/984

Bump Kubeflow pipeline version to 0.5.0

### CODE REVIEW

**Comment by Bobgy** [comment]
@eedorenko in addition to bumping the version, you also need to mirror non-refactoring changes in https://github.com/kubeflow/pipelines/commits/master/manifests/kustomize to here.

**Comment by eedorenko** [comment]
Could you please clarify what non-refactoring changes you mean?

**Comment by Bobgy** [comment]
Hi @eedorenko , FYI KFP 1.0.0-rc.2 has been integrated with kubeflow in https://github.com/kubeflow/manifests/pull/1248.

**Comment by Jeffwan** [comment]
@Bobgy This is different source from the PR for 1.0.0. Not all boostrap tool are using stacks I think. This is still worth to merge it

**Comment by Bobgy** [comment]
@Jeffwan problem is, this PR didn't include all upstream manifest changes to support a proper KFP manifest update, some features might be broken.

If you tested this branches work for you, I don't have any objections.

but KFP team will only keep maintain the stacks because of the manifest syncing cost. Would you consider making a wrapper `pipeline/installs/base/kustomization.yaml` file which includes `pipeline/installs/generic` so that the stacks manifest could be used with kfctl too (not sure on details, but it sounds doable)?

**Comment by eedorenko** [comment]
@Bobgy what upstream manifest changes do you think should be included?
This branch has been tested. We've been working with it since May 1st.

**Comment by Bobgy** [comment]
I briefly went through all changes between 0.2.5 and 0.5.0.

I think you need https://github.com/kubeflow/pipelines/commit/f882f361cc705580261128e33523fe80d781b30f#diff-17145b7d84b2980d3edd18ba00b95d0e.
Also, KFP caching servers were added in 0.5.0, but they are not included in manifests here.

This is the best I can help, you will need to troubleshoot and maintain this deployment by yourselves.

**Comment by Bobgy** [comment]
Also, I'm not sure we should merge this to v1.0-branch. There won't be kubeflow 1.0.3 release, because everyone is planning on 1.1.

**Comment by Jeffwan** [comment]
@Bobgy  Agree. We won't have v1.0.3 release,

@eedorenko v1.1.0 will be officially released next week. Are you ok to migrate to v1.1.0? If so, we can close this PR

**Comment by eedorenko** [comment]
@Jeffwan Yes, I am Ok with migrating to  v1.1.0.
So, if v1.0.3 doesn't happen I am closing this PR.

**Pull request closed without merging**
