### PR TITLE
fix(gcp): Remove gcp distribution from manifests: store this directory in kubeflow/gcp-blueprints

### LINKED ISSUE #1791: gcp: Remove distribution/gcp folder from kubeflow/manifest
We need to move the distribution/gcp folder to `kubeflow/gcp-blueprint`, so this `kubeflow/manifests` only contain the platform-agnostic content of each app.

### PR DESCRIPTION
**Pull request by zijianjoy**
**Which issue is resolved by this Pull Request:**
Resolves #1791

**Description of your changes:**
This folder will be moved to `kubeflow/gcp-blueprint.git`, we need to remove the upstream folder to avoid confusion.

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by yanniszark** [comment]
Thanks a lot @zijianjoy! These are still a couple of kustomizations under `common/istio`:
- `gcp-1-1-6`
- `iap-gateway`

Should we remove those as well?

**Comment by Bobgy** [comment]
Yes, we should remove those as well

**Comment by yanniszark** [comment]
@zijianjoy could you also add:

> gcp-1-1-6
> iap-gateway

to the PR? We can make it 2 PRs, but it seems like a very small change, so why not get it in?

**Comment by zijianjoy** [comment]
Sounds good, thank you Yuan and Yannis! I will remove those two folders in this PR.

**Comment by zijianjoy** [comment]
@Bobgy @yanniszark PR is updated with gcp-1-1-6 and iap-gateway removal.

**Pull request merged**
