### PR TITLE
Adding more examples

### PR DESCRIPTION
**Pull request by missingcharacter**
**Which issue is resolved by this Pull Request:**
Resolves  None that I'm aware

**Description of your changes:**

- Rename folder `example` to `examples`
- Rename current example to `examples/all-included`
- Created new example called `external-dbs`

I recently stood up kubeflow in multiple environments and noticed
I would have had spent less time standing up kubeflow if I had seen
more examples.

I thought the project would benefit from having different examples
that people can learn from.

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only` 
    2. `make test`

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by juliusvonkohout** [comment]
Please put this on the agenda of the next manifest wg meeting in two weeks and join us for a discussion

**Comment by juliusvonkohout** [comment]
And you need to fix the merge conflict first.

**Comment by juliusvonkohout** [comment]
/close

since there is no response since August 25.

**Comment by missingcharacter** [comment]
I am ok with closing this
@juliusvonkohout, sorry, I don't have free time to continue maintaining this fork. Thanks for the consideration

**Pull request closed without merging**
