### PR TITLE
refactor ml-pipeline component for kustomize5 compatibility

### LINKED ISSUE #2548: Refactor ml-pipeline component for kustomize5
Part of the larger https://github.com/kubeflow/manifests/issues/2388 initiative to refactor Kubeflow apps for `kustomize5`. 
This Issue should address fixes for the deprecated fields for the `manifests/apps/pipeline/` component.

#### Warnings thrown before this PR:
```sh
$ kustomize build apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user/  

# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesJson6902' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
2023/10/12 15:10:41 well-defined vars that were never replaced: kfp-app-name,kfp-app-version
```

Expected behaviour after refactoring the resources for `kustomize`  is to obtain healthy set of manifests without any warnings.

#### Remaining Warnings (**Work in progress**):
```
 Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesJson6902' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
2023/10/12 15:50:46 well-defined vars that were never replaced: kfp-app-version,kfp-app-name
```

After couple more commits I am expecting to have also refactored the remaining `vars` and `patchesJson6902` deprecations from the rest of the resources. 

Looking for feedback and a review! (@juliusvonkohout @annajung)

### PR DESCRIPTION
**Pull request by rawc0der**
**Which issue is resolved by this Pull Request:**
Resolves #2548

**Description of your changes:**
This PR fixes the deprecated fields for `manifests/apps/pipeline/` component.

The deprecated fields in `kustomize5` to refactor: 
- `bases` -> `resources` 
- `patchesStrategicMerge ` -> `patches`
- `patchesJson6902` -> `patchces`
- `vars` -> `replacements` 

For a complete description, please check Issue https://github.com/kubeflow/manifests/issues/2548.

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by annajung** [comment]
Hi @rawc0der Thanks for your help with https://github.com/kubeflow/manifests/issues/2388 effort

For any components that exist within `/apps`, the changes must be made to the corresponding repo, not manifest. For pipelines, the PR needs to be made to the [github.com/kubeflow/pipelines](https://github.com/kubeflow/pipelines) and merged by the pipeline WG. 

Then, we can sync the changes back to manifest repo. If we merge here, it will be replaced by the upstream pipeline manifest when we complete a manifest sync in the future.

**Comment by rawc0der** [comment]
Hi @annajung,

I see, no worries. Am also figuring out the whole Manifests WG setup.  
So if I understand it right, the correct place for these manifests in https://github.com/kubeflow/pipelines/ should be inside this folder: `manifests/kustomize`?

Will make the changes there then.

**Comment by annajung** [comment]
That's correct, if you take a look at https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize, it should be the same as the one you see in the Manifest repo.

**Comment by rawc0der** [comment]
Closing this one and tracking issue in https://github.com/kubeflow/pipelines/issues/10053.

**Pull request closed without merging**
