### PR TITLE
Add arm64 support to istio node selectors

### PR DESCRIPTION
**Pull request by MrXinWang**
Current istio manifests do not have architecture support for arm64 in nodeSelectorTerms. This commit adds the related arm64 supports.

Signed-off-by: Henry Wang <<Henry.Wang@arm.com>>

### CODE REVIEW

**Comment by jlewi** [comment]
/assign @krishnadurai 

@krishnadurai looks like the active OWNER of the ISTIO configs so he should probably review these changes

/unassign @jlewi
/unassign @Bobgy

**Comment by MrXinWang** [comment]
Thanks @jlewi :)

**Pull request closed without merging**
