### PR TITLE
#2775 describe how to change default password from secret

### PR DESCRIPTION
**Pull request by tsadimas**
# Pull Request Template for Kubeflow manifests Issues

- Please include a summary of changes and the related issue. 
- List any dependencies that are required for this change. 
- Please delete the options that are not relevant.
- The following checklist will help you to satisfy the requirements.

  
## ✅ Unit Test Checklist
  
  - [ ] 🛠️ Make sure you have installed kustomize == 5.2.1+     
  - [ ] ✍️ Have you written new tests for your core changes, as applicable?      
  - [ ] 🔄 Have you successfully run existing tests with your changes ?    
  - [ ] 🚀 Have you successfully run existing and new tests with your changes ?

## ✅ Contributor checklist
  - [ ] All the commits have been _signed-off_  (To pass the `DCO` check)
  - [ ] Submit the [Contributor License Agreements](https://cla.developers.google.com/clas) (To pass the `cla/google` check)

---     
 
> You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### CODE REVIEW

**Comment by diegolovison** [comment]
What was described before was: how to change before the deploy
What was changed in the PR: how to change the pwd after the deploy

Imho, it will be good have the two steps documented

**Comment by juliusvonkohout** [comment]
> What was described: how to change before the deploy What was changed in the PR: how to change the pwd after the deploy
> 
> Imho, it will be good have the two steps documented

I am also glad if it just works. We have to merge it this week for 1.9.

**Comment by jaffe-fly** [comment]
add a new user, after create `Profile` ，
```
  owner:
    kind: User
    name: admin@example.com
```

and  create `ClusterRoleBinding`
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-profile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin@example.com
```

you need to `kubectl edit cm -n auth dex -o yaml` in `staticPasswords` add new user,example
```
staticPasswords:
    - email: user@example.com
      hashFromEnv: DEX_USER_PASSWORD
      username: user
      userID: "15841185641784"
    - email: admin@example.com
      hashFromEnv: DEX_USER_PASSWORD  
    # hash: xxxxxxxxxxxxxx
      username: admin
      userID: "15841185641785"
```

you can use `python3 -c 'from passlib.hash import bcrypt; import getpass; print(bcrypt.using(rounds=12, ident="2y").hash(getpass.getpass()))'`get you hash password

**then delete dex pod and writing for  auto restart pod**

thus you can login from Dashboard 

CC 
@Diego Lovison

**Comment by juliusvonkohout** [comment]
@jaffe-fly. Yes we should document how to add users and admins :-)

**Comment by juliusvonkohout** [comment]
Please incorporate https://github.com/kubeflow/kubeflow/pull/7582

**Comment by juliusvonkohout** [comment]
I think this was solved in https://github.com/kubeflow/manifests/pull/2799

**Pull request closed without merging**
