### PR TITLE
Update jupyter web-app image

### PR DESCRIPTION
**Pull request by abhi-g**
To keep in sync with https://github.com/kubeflow/kubeflow/pull/3510

/cc @yanniszark @kimwnasptd

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/165)

### CODE REVIEW

**Comment by kimwnasptd** [comment]
Hi @abhi-g, regarding the presubmit job I think you need to [regenerate the unit tests](https://github.com/kubeflow/manifests/pull/138#issuecomment-502951966) and make another commit.

Also a small heads up, the [new UI](https://github.com/kubeflow/kubeflow/pull/3448) is just around the corner. I'm waiting for the tests to finish and merge it. Also, I've updated the config.yaml in #163 that works with the new UI, but will not work with the current.

Once the new get's merged I'll also update the tag here.

**Comment by abhi-g** [comment]
thanks @kimwnasptd . Updating..

**Pull request merged**
