### PR TITLE
Update oidc-authservice

### PR DESCRIPTION
**Pull request by yhwang**
Use the newer image of oidc-authservice, add mandatary
parameter(AUTHSERVICE_URL_PREFIX) and change to
`istio/base_v3`.

Signed-off-by: Yihong Wang <yh.wang@ibm.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by yhwang** [comment]
@yanniszark can you review this and see if it's good to pump up the oidc-authservice to the following:
> newName: gcr.io/arrikto/oidc-authservice
> newTag: 087a340
Then it will enable the id-token authentication

**Comment by yanniszark** [comment]
@yhwang thanks for the ping! I will make a note to address this after the current steps of wg-manifests for 1.3:
https://github.com/kubeflow/manifests/issues/1735

**Comment by yhwang** [comment]
@yanniszark hope this could be included in v1.3. thanks!

**Comment by HassanOuda** [comment]
Will this be included for 1.3?

**Comment by yanniszark** [comment]
I would love to include this, but doing so will break the logout button for CentralDashboard:
https://github.com/kubeflow/kubeflow/blob/876016a57a33cb27c21562aa8ec6c0a514382cb7/components/centraldashboard/public/components/main-page.pug#L83-L84

In later versions, oidc-authservice changed the logout method to account for CSRF attacks:
https://github.com/arrikto/oidc-authservice/blob/master/docs/csrf.md#logout-csrf

**Comment by alembiewski** [comment]
Fix for the logout button for Central Dashboard: https://github.com/kubeflow/kubeflow/pull/6609

**Pull request closed without merging**
