### PR TITLE
Removing unnecessary configs from Pytorch operator 

### PR DESCRIPTION
**Pull request by johnugeorge**
v1beta2 support is removed. 
ConfigMap is not needed any more.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/431)

### CODE REVIEW

**Comment by richardsliu** [comment]
Are the corresponding tests updated? Will we have test failures because v1beta2 is deprecated?

**Comment by johnugeorge** [comment]
@richardsliu which tests are you referring to?

**Pull request merged**
