### PR TITLE
chore: delete kubeflow/metadata manifests

### PR DESCRIPTION
**Pull request by Bobgy**
**Which issue is resolved by this Pull Request:**
Part of #1740 

**Description of your changes:**
Remove kubeflow/metadata manifests, MLMD manifests should come from KFP's upstream manifests now.

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Review by PatrickXYS — APPROVED** [review]
/lgtm
/approve

/hold 
Hold for others to review

**Comment by Bobgy** [comment]
@yanniszark can you confirm this change for manifest WG?

**Comment by elikatsis** [comment]
Hi @Bobgy,

I'm a bit concerned with purging this manifests in favor of standalone KFP ones. The reason why is that KF distributions have been deploying using these ones which come with a distinct and dedicated database (`overlays/db/` kustomization) whereas the KFP manifests use the MySQL backing KFP itself.

So if we remove these manifests, users that upgrade their clusters will lose their data.

**Comment by Bobgy** [comment]
That's a fair point.

Do you have any suggestions? Move these to KFP upstream?

**Comment by Bobgy** [comment]
@yanniszark @elikatsis with the manifests moved to upstream, shall we proceed with this PR?

**Comment by yanniszark** [comment]
Yes, thank you @Bobgy !
/lgtm
/approve

**Pull request merged**
