### PR TITLE
Update katib images to v0.7.0 tag

### PR DESCRIPTION
**Pull request by johnugeorge**
**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/563)

### CODE REVIEW

**Comment by swiftdiaries** [comment]
Looks the deployment manager test failed

**Comment by johnugeorge** [comment]
/hold
as test changes are added

**Pull request closed without merging**
