### PR TITLE
Adding self to OWNERS

### PR DESCRIPTION
**Pull request by krishnadurai**
/assign @kkasravi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/666)

### CODE REVIEW

**Comment by jlewi** [comment]
@krishnadurai Instead of adding yourself to root OWNERS how about adding yourself to the packages you should be an admin/owner of? 

This will help better assign reviewers.

**Comment by krishnadurai** [comment]
@jlewi I'm doing this with a view that most PRs are now spanning across manifests and having a sub-directory approve right isn't helping to push PRs forward.

**Comment by jlewi** [comment]
@krishnadurai Could you provide an example of PRs spanning across directories?

My expectation would be that the bulk of the PRs would be affecting individual applications (e.g Jupyter vs. KFServing). Each of those applications would have different owners and PRs should be reviewed by the respective owners.

**Comment by krishnadurai** [comment]
@jlewi Here are a few PRs I faced a problem in.
#622 #633

**Comment by jlewi** [comment]
Please open a new PR if this is still relevant.

**Pull request closed without merging**
