### PR TITLE
feat: Add a Makefile for quick installation of Kubeflow.

### PR DESCRIPTION
**Pull request by shalousun**
# Pull Request Template for Kubeflow manifests Issues

## ✏️ A brief description of the changes
1.  Add a Makefile for quick installation of Kubeflow.
2. Different open-source projects may have inconsistent requirements for the kustomize version. Using a standalone kustomize version in the Makefile will not affect the user's default installed kustomize version.

## ✅ Contributor checklist
  - Make sure you have tested with kustomize. See [Installation Prerequisites](https://github.com/kubeflow/manifests#prerequisites)
  - All the commits have been _signed-off_  (To pass the `DCO` check)
  - Submit the [Contributor License Agreements](https://cla.developers.google.com/clas) (To pass the `cla/google` check)

---     
 
> You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
Hello, what is the benefit of this PR ?

**Comment by juliusvonkohout** [comment]
We support kustomize 5.2.1+

**Comment by shalousun** [comment]
> Hello, what is the benefit of this PR ?

Adding a Makefile can make installing Kubeflow with manifests simpler and more convenient.

**Comment by shalousun** [comment]
> We support kustomize 5.2.1+

I know that manifests support kustomize 5.2.1 and above. In some of my development scenarios, different operators from various open-source communities have different dependencies on kustomize versions. Therefore, using a Makefile to install kustomize into the `bin` directory of the current project means it won't affect the global kustomize version. Users don't need to switch between different kustomize versions for various open-source projects. This is a similar approach adopted in operators generated by kubebuilder.

**Comment by juliusvonkohout** [comment]
Alright I will close this, but maybe you want to tackle another documentation PR or improve our cicd tests

**Pull request closed without merging**
