### PR TITLE
fixes knative for kustomize 5. Especially only one patch per file

### LINKED ISSUE #2421: Fix kustomize 5 warning for /common/knative/knative-serving/overlays/gateways
Part of https://github.com/kubeflow/manifests/issues/2388 to support kustomize 5 without warnings. Fix the use of deprecated fields in `manifests/common/knative/knative-serving/overlays/gateways`

#### Steps To Reproduce
1. Download [kustomize 5.0.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.0.0)

2. Run `kustomize build` using version kustomize 5.0.0 to see the warning
```
git clone https://github.com/kubeflow/manifests.git
cd manifests/common/knative/knative-serving/overlays/gateways
kustomize build . > tmp.yaml
```

#### Current Behavior
Step 2 produces the following warning
```
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
```

#### Expected Behavior
Step 2 completes **without** a warning and produces the same yaml as before the changes

#### Helpful links:
- https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/
- https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/resource/
- https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/

#### Where does the fix belong?
`/common` directory is managed by the Manifest WG, PR should be made to the manifests repo

/help
/good-first-issue

### PR DESCRIPTION
**Pull request by juliusvonkohout**
**Which issue is resolved by this Pull Request:**
Resolves #2421 

@annajung @kimwnasptd

### CODE REVIEW

**Comment by kimwnasptd** [comment]
@juliusvonkohout to make sure my understanding is accurate, this PR:
* Updates kustomize to use `patches` instead of `patchesStrategicMerge` to reduce warnings
* Add aggregation rules for Knative, so that Pods in user namespaces can manipulates Knative resources 

right?

**Comment by juliusvonkohout** [comment]
@kimwnasptd actually it should produce exactly the same manifests. I have used `kustomize edit fix` and had to split files up. The new patches functionality only allows one patch per file it seems.

There is no functionality added, I only removed the warnings. Just kustomize build and we should see no changes in the manifests.

**Comment by annajung** [comment]
verified that contents are identical and no error is produced 

/lgtm

**Pull request merged**
