### PR TITLE
KFServing and KNative manifests Owners files

### PR DESCRIPTION
**Pull request by animeshsingh**

### CODE REVIEW

**Comment by animeshsingh** [comment]
@adrian555 @Tomcli @yuzisun please lgtm

additionally @yuzisun do we want to add someone else from bloomberg?

**Comment by animeshsingh** [comment]
thanks @krishnadurai for pointing that

didn't see that before - but I don't expect these files to be duplicate of OWNERS file in actual application repos - the focus here is folks who would be focussing on "integration" and "integration-testing" with Kubeflow as opposed to development of application itself.

cc @yuzisun

**Comment by animeshsingh** [comment]
on that note, ideally @krishnadurai you should be in KNative owners file as well, if you don't mind to be added

**Comment by krishnadurai** [comment]
@animeshsingh go ahead to add my name.

**Pull request merged**
