### PR TITLE
Fix volumeClaimTemplate for Seldon

### PR DESCRIPTION
**Pull request by cliveseldon**
Needed for https://github.com/kubeflow/kubeflow/pull/3608

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/202)

### CODE REVIEW

**Comment by yanniszark** [comment]
@cliveseldon 

You'll need to regenerate the unit tests
cd manifests/tests
make generate
make test

@kkasravi we should probably put these steps in a PR template.

**Comment by cliveseldon** [comment]
If I do as you suggest I get lots of deleted files:

```
On branch seldon_manifests
Your branch is up-to-date with 'origin/seldon_manifests'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    tests/ambassador-base_test.go
	deleted:    tests/api-service-base_test.go
	deleted:    tests/application-base_test.go
	deleted:    tests/application-crds-base_test.go
	deleted:    tests/application-overlays-application_test.go
	deleted:    tests/application-overlays-debug_test.go
	deleted:    tests/argo-base_test.go
	deleted:    tests/argo-overlays-istio_test.go
	deleted:    tests/basic-auth-base_test.go
	deleted:    tests/basic-auth-ingress-base_test.go
	deleted:    tests/basic-auth-overlays-istio_test.go
	deleted:    tests/bootstrap-base_test.go
	deleted:    tests/centraldashboard-base_test.go
	deleted:    tests/centraldashboard-overlays-application_test.go
	deleted:    tests/centraldashboard-overlays-istio_test.go
	deleted:    tests/cert-manager-base_test.go
	deleted:    tests/cert-manager-crds-base_test.go
	deleted:    tests/cloud-endpoints-base_test.go
	deleted:    tests/gpu-driver-base_test.go
	deleted:    tests/iap-ingress-base_test.go
	deleted:    tests/istio-base_test.go
	deleted:    tests/istio-crds-base_test.go
	deleted:    tests/jupyter-base_test.go
	deleted:    tests/jupyter-overlays-minikube_test.go
	deleted:    tests/jupyter-web-app-base_test.go
	deleted:    tests/jupyter-web-app-overlays-application_test.go
	deleted:    tests/jupyter-web-app-overlays-istio_test.go
	deleted:    tests/katib-controller-base_test.go
	deleted:    tests/katib-db-base_test.go
	deleted:    tests/katib-manager-base_test.go
	deleted:    tests/katib-ui-base_test.go
	deleted:    tests/katib-ui-overlays-istio_test.go
	deleted:    tests/kubebench-base_test.go
	deleted:    tests/kubebench-overlays-istio_test.go
	deleted:    tests/metacontroller-base_test.go
	deleted:    tests/metadata-base_test.go
	deleted:    tests/metadata-overlays-istio_test.go
	deleted:    tests/metrics-collector-base_test.go
	deleted:    tests/minio-base_test.go
	deleted:    tests/minio-overlays-minioPd_test.go
	deleted:    tests/modeldb-base_test.go
	deleted:    tests/mysql-base_test.go
	deleted:    tests/mysql-overlays-mysqlPd_test.go
	deleted:    tests/notebook-controller-base_test.go
	deleted:    tests/notebook-controller-overlays-application_test.go
	deleted:    tests/notebook-controller-overlays-istio_test.go
	deleted:    tests/persistent-agent-base_test.go
	deleted:    tests/pipelines-runner-base_test.go
	deleted:    tests/pipelines-ui-base_test.go
	deleted:    tests/pipelines-ui-overlays-istio_test.go
	deleted:    tests/pipelines-viewer-base_test.go
	deleted:    tests/profiles-base_test.go
	deleted:    tests/profiles-overlays-debug_test.go
	deleted:    tests/profiles-overlays-devices_test.go
	deleted:    tests/profiles-overlays-istio_test.go
	deleted:    tests/prometheus-base_test.go
	deleted:    tests/pytorch-job-crds-base_test.go
	deleted:    tests/pytorch-operator-base_test.go
	deleted:    tests/pytorch-operator-overlays-application_test.go
	deleted:    tests/scheduledworkflow-base_test.go
	deleted:    tests/seldon-core-operator-base_test.go
	deleted:    tests/seldon-core-operator-overlays-application_test.go
	deleted:    tests/spartakus-base_test.go
	deleted:    tests/studyjob-base_test.go
	deleted:    tests/suggestion-base_test.go
	deleted:    tests/tensorboard-base_test.go
	deleted:    tests/tensorboard-overlays-istio_test.go
	deleted:    tests/tf-job-operator-base_test.go
	deleted:    tests/tf-job-operator-overlays-application_test.go
	deleted:    tests/tf-job-operator-overlays-istio_test.go
	deleted:    tests/vizier-core-base_test.go
	deleted:    tests/vizier-db-base_test.go
	deleted:    tests/webhook-base_test.go
```

 Is this expected?

**Comment by yanniszark** [comment]
@cliveseldon these are the standard commands I run for PRs as well.
I suggest to submit the results and see if the tests pass.

**Comment by cliveseldon** [comment]
@yanniszark Not sure I follow. You want me do commit to the PR all the deleted go files? Is this correct?

**Comment by cliveseldon** [comment]
OK. So the `hack/gen-test-targets.sh` script is a bit brittle. It expects the top level folder to be called "manifests" - I had `fork-manifests". I've run. The tests fail seemly for some unexpected paths on things not to do with seldon.

**Comment by yanniszark** [comment]
> It expects the top level folder to be called "manifests" - I had `fork-manifests". 

Nice catch! We should also open an issue for that or warn users.

> The tests fail seemly for some unexpected paths on things not to do with seldon.

Does this happen after changing the folder name?
Is the PR rebased on the latest master?

**Comment by cliveseldon** [comment]
Yes its rebased to master. The changes created by `make generate` seem to be mainly formatting changes apart from the Seldon ones.

**Comment by yanniszark** [comment]
@cliveseldon I suspect that a different version of fmt is causing the formatting changes:
https://github.com/kubeflow/manifests/blob/91c22388f5d1d9bf0f337185dcb36aca5c0f5ee8/tests/Makefile#L28

Everything should still work though.

**Comment by cliveseldon** [comment]
The failing test is prometheus

```
=== RUN   TestPrometheusBase
--- FAIL: TestPrometheusBase (0.00s)
    prometheus-base_test.go:339: Err: cannot read file "/manifests/gcp/prometheus/base/params.yaml"

```

**Comment by cliveseldon** [comment]
I fixed the prometheus bug as well. Should be ready to merge @yanniszark

**Comment by yanniszark** [comment]
@cliveseldon thanks a lot! 
I find it really strange that prometheus broke the tests, CI should have prevented that bug from creeping in :thinking: 
cc @kkasravi @jlewi if you have any idea on this.

/lgtm
/approve

**Pull request merged**
