### PR TITLE
basic-auth-ingress is missing from gcp

### LINKED ISSUE #54: basic-auth-ingress is missing from gcp
from ksonnet gcp/prototypes/basic-auth-ingress.jsonnet

parameters are 

namespace=
ipName=
hostname=
secretName=envoy-ingress-tls
ingressSetupImage=gcr.io/kubeflow-images-public/ingress-setup:latest
privateGKECluster=false
ingressName=envoy-ingress
issuer=letsencrypt-prod

### PR DESCRIPTION
**Pull request by kkasravi**
fixes #54, kubeflow/kubeflow/issues/3207

should be paired with kubeflow/kubeflow/pull/3108

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/58)

### CODE REVIEW

**Comment by swiftdiaries** [comment]
Not sure about the GCP ingress part but others look good
/cc @gabrielwen for the GCP part

**Comment by kkasravi** [comment]
@jlewi @hougangliu @gabrielwen 

This needs to be merged as a prerequisite for kubeflow/kubeflow/pull/3108

**Comment by kkasravi** [comment]
@hougangliu @ashahba @swiftdiaries i've made a few changes and confirmed with works with [#3801](https://github.com/kubeflow/kubeflow/issues/3801)

**Comment by hougangliu** [comment]
/lgtm
/approve
thanks!

**Pull request merged**
