### PR TITLE
Fix: Update docker image pull policy

### LINKED ISSUE #2308: Notebook-controller and Profile-and-kfam Docker Image Pull Policy
Hi,

We notice the below 3 docker images' `imagePullPolicy` are set to `Always `
* `docker.io/kubeflownotebookswg/notebook-controller:v1.6.1`
* `docker.io/kubeflownotebookswg/kfam:v1.6.1`
* `docker.io/kubeflownotebookswg/profile-controller:v1.6.1`

This could lead to hitting the [docker image pull rate limit](https://aws.amazon.com/premiumsupport/knowledge-center/ecs-pull-container-error-rate-limit/#:~:text=Docker%20Hub%20uses%20IP%20addresses,pulls%20per%206%2Dhour%20period)  which is set to **100 pull for anonymous users**  in **every 6 hours**.

We are wondering if the pullPolicy for these images is set to `Always` intentionally or it's a miss that can be set as `IfNotPresent` so they can be cached?

### PR DESCRIPTION
**Pull request by imVipul3000**
**Which issue is resolved by this Pull Request:**
Resolves #2308

**Description of your changes:**
replace "Always" to "IfNotPresent" for imagePullPolicy so that it will only pull if image is not in local

**Checklist:**
- [x] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
@imVipul3000 

Thanks for your PR. But there is a Problem with changing the OCI images here. The OCI images must be changed in the corresponding repositories such as Kubeflow/pipelines. As a side note we do not support Docker, only OCI images.

Feel free to join our manifests WG meeting for questions.

**Review by aqeelat — COMMENTED** [review]
I suggest removing the imagePullPolicy altogether and relying on k8s defaults.

**Comment by juliusvonkohout** [comment]
> I suggest removing the imagePullPolicy altogether and relying on k8s defaults.  

Also a valid option

**Comment by juliusvonkohout** [comment]
/close

this is not the right repository, please use the upstream ones

**Pull request closed without merging**
