### PR TITLE
Revert   PRs  back to 3e85b3c83de12fed7d675151d0d4f8474eb04790

### PR DESCRIPTION
**Pull request by jlewi**
**Which issue is resolved by this Pull Request:**
Resolves #
Related to #426

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/429)

### CODE REVIEW

**Comment by jlewi** [comment]
I manually tried deploying this.
When I first reran kfctl apply I got

```
Error from server (InternalError): error when creating "/tmp/kout698072699": Internal error occurred: failed calling webhook "kfservice.kfserving-webhook-server.deployment-mutator": Post https://kfserving-webhook-server-service.kubeflow.svc:443/mutate-deployments?timeout=30s: ssh: rejected: connect failed (Connection refused)
Error from server (InternalError): error when creating "/tmp/kout698072699": Internal error occurred: failed calling webhook "kfservice.kfserving-webhook-server.deployment-mutator": Post https://kfserving-webhook-server-service.kubeflow.svc:443/mutate-deployments?timeout=30s: ssh: rejected: connect failed (Connection refused)
```

I reran kfctl apply and it succeeded.

So its possible there is a problem deploying kfserving but our tests aren't catching it because we are rerunning apply.

**Comment by swiftdiaries** [comment]
Can we remove KFServing from the KfDef and point to the README there?
I understand there's a lot of churn there

**Comment by jlewi** [comment]
@swiftdiaries I filed https://github.com/kubeflow/kfserving/issues/399 about KFServing.

I'm open to removing KFServing if we confirm its a problem. Lets not do it in this PR though. Lets keep this PR a clean roll back.

I checked and KFServing has been in the KFDef specs for quite a while.

**Comment by jlewi** [comment]
I manually verified that my endpoint ended up being accessible
jlewi-1003-3e85b3c-001.endpoints.jlewi-dev.cloud.goog

**Pull request merged**
