### PR TITLE
KFP visualization-service: Fix double ml-pipeline- prefix in names

### PR DESCRIPTION
**Pull request by elikatsis**
Signed-off-by: Ilias Katsakioris <elikatsis@arrikto.com>

---

Related to kubeflow/pipelines#3849.

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by elikatsis** [comment]
cc @Bobgy

**Comment by Bobgy** [comment]
test failure seems transient
/retest

**Comment by Bobgy** [comment]
Thanks for the fix @elikatsis

**Comment by Bobgy** [comment]
/hold
in fact, I met this problem later: https://github.com/kubernetes-sigs/kustomize/issues/1301
when building KF 1.1

So I'd prefer we don't use the common prefix, so above issue will be avoided.
Another personal opinion is that, common prefix breaks grepability. People usually find resources by searching the full name.

**Comment by elikatsis** [comment]
Thanks for the information, it really helps knowing that bug is there.
I changed the commit accordingly

**Comment by jlewi** [comment]
/approve

@Bobgy I suggest creating an OWNERS file in tests and adding yourself.

**Comment by Bobgy** [comment]
Something seems failed in building kfctl
```
E       subprocess.CalledProcessError: Command 'cmd: make build-kfctl exited with code 2' returned non-zero exit status 2.
../../../../../../testing/py/kubeflow/testing/util.py:86: CalledProcessError
------------------------------ Captured log call -------------------------------
INFO     root:util.py:46 Running: gcloud auth activate-service-account --key-file=/secret/gcp-credentials/key.json
cwd=None
INFO     root:util.py:61 Subprocess output:
INFO     root:util.py:72 Activated service account credentials for: [kubeflow-testing@kubeflow-ci.iam.gserviceaccount.com]
INFO     root:kfctl_go_test.py:43 using kfctl repo: /mnt/test-data-volume/kubeflow-manifests-presubmit-e2e-1210-d600c3d-1936-4b93/src/kubeflow/kfctl
INFO     root:kfctl_go_test.py:53 config_path after substitution: /mnt/test-data-volume/kubeflow-manifests-presubmit-e2e-1210-d600c3d-1936-4b93/src/kubeflow/manif
ests/kfdef/kfctl_gcp_iap.yaml
INFO     root:util.py:46 Running: make build-kfctl
cwd=/mnt/test-data-volume/kubeflow-manifests-presubmit-e2e-1210-d600c3d-1936-4b93/src/kubeflow/kfctl
INFO     root:util.py:61 Subprocess output:
INFO     root:util.py:72 make: *** No rule to make target 'build-kfctl'.  Stop.
INFO     root:util.py:46 Running: make build-kfctl
cwd=/mnt/test-data-volume/kubeflow-manifests-presubmit-e2e-1210-d600c3d-1936-4b93/src/kubeflow/kfctl
INFO     root:util.py:61 Subprocess output:
INFO     root:util.py:72 make: *** No rule to make target 'build-kfctl'.  Stop.
INFO     root:util.py:46 Running: make build-kfctl
cwd=/mnt/test-data-volume/kubeflow-manifests-presubmit-e2e-1210-d600c3d-1936-4b93/src/kubeflow/kfctl
INFO     root:util.py:61 Subprocess output:
INFO     root:util.py:72 make: *** No rule to make target 'build-kfctl'.  Stop.
INFO     root:util.py:46 Running: make build-kfctl
cwd=/mnt/test-data-volume/kubeflow-manifests-presubmit-e2e-1210-d600c3d-1936-4b93/src/kubeflow/kfctl
INFO     root:util.py:61 Subprocess output:
INFO     root:util.py:72 make: *** No rule to make target 'build-kfctl'.  Stop.
```

**Comment by Bobgy** [comment]
Same failure in https://github.com/kubeflow/manifests/pull/1224, so tests are broken in master

**Comment by Bobgy** [comment]
https://github.com/kubeflow/kfctl/commit/81c92c7c14554e01030dd75c7f22e040e6ed119e#diff-b67911656ef5d18c4ae36cb6741b7965R126
a new PR in kubeflow/kfctl is removed the `build-kfctl` makefile rule

**Comment by Bobgy** [comment]
Okay, problem solved
/retest

**Pull request merged**
