### PR TITLE
Modifying cluster-kubeflow.yaml file to update GKE version. 

### LINKED ISSUE #1519: GKE 1.14 no longer supported, which breaks installs on GCP for 1.0.2
/kind bug

**What steps did you take and what happened:**
 Attempted a command line install of kubeflow `1.0.2`. The attempt failed. When querying the deployment manager about the failure we get the trace below:
```
gcloud --project=redacted-project-name deployment-manager deployments describe kubeflow                                               
---
fingerprint: GxK9NqnNQBbfIDmFlreKIA==
id: '9087252920422578001'
insertTime: '2020-08-26T09:11:42.911-07:00'
name: kubeflow
operation:
  endTime: '2020-08-26T09:13:35.596-07:00'
  error:
    errors:
    - code: RESOURCE_ERROR
      location: /deployments/kubeflow/resources/kubeflow
      message: '{"ResourceType":"gcp-types/container-v1beta1:projects.locations.clusters","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"No
        valid versions with the prefix \"1.14\" found.","status":"INVALID_ARGUMENT","statusMessage":"Bad
        Request","requestPath":"https://container.googleapis.com/v1beta1/projects/redacted-project-name/locations/us-central1-c/clusters","httpMethod":"POST"}}'
  name: operation-1598458395765-5adca18de2a63-777e2cf1-c8080550
  operationType: update
  progress: 100
  startTime: '2020-08-26T09:13:16.030-07:00'
  status: DONE
  user: redacted
  update:
  manifest: https://www.googleapis.com/deploymentmanager/v2/projects/redacted-project-name/global/deployments/kubeflow/manifests/manifest-1598458395957
NAME                  TYPE                                                               STATE      INTENT
kubeflow              gcp-types/container-v1beta1:projects.locations.clusters            FAILED     CREATE_OR_ACQUIRE
kubeflow-admin        iam.v1.serviceAccount                                              COMPLETED
kubeflow-gpu-pool-v1  gcp-types/container-v1beta1:projects.locations.clusters.nodePools  ABORTED    CREATE_OR_ACQUIRE
kubeflow-ip           compute.v1.globalAddress                                           COMPLETED
kubeflow-user         iam.v1.serviceAccount                                              COMPLETED
kubeflow-vm           iam.v1.serviceAccount                                              COMPLETED
```

It seems support for `gke 1.14` has been dropped:
```
gcloud container get-server-config --zone us-central1-a --format json | jq .validMasterVersions                                                  
Fetching server config for us-central1-a
[
  "1.16.13-gke.1",
  "1.15.12-gke.16",
  "1.15.12-gke.13",
  "1.15.12-gke.9",
  "1.15.12-gke.2"
]
```

**What did you expect to happen:**
The installation process should have succeeded.

**Environment:**

- Kubeflow version: `1.0.2`
- kfctl version: `1.0.2`
- Kubernetes platform: `gcp`

Are there plans to modify the installation packages for the `1.0` branch to support newer gke versions ?

### PR DESCRIPTION
**Pull request by virgoaugustine**
**Which issue is resolved by this Pull Request:**
Resolves #1519 

**Description of your changes:**
Changed the "cluster-version" from 1.14 to 1.15. 

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by virgoaugustine** [comment]
@googlebot I signed it!

**Comment by jlewi** [comment]
Deployment manager configs are no longer used starting with Kubeflow 1.1.
We should probably delete this.
The CNRM configurations use GKE release channels.

**Comment by jlewi** [comment]
@virgoaugustine Do you want to update this PR to delete the DM configs? I think the fix to #1519 is to use Kubeflow 1.1

**Comment by virgoaugustine** [comment]
@jlewi will it be best to update the cluster-kubeflow.yaml file for just the v1.0 branch then instead of the master branch? So people who still use the v1.0 branch can successfully create and deploy clusters?

**Pull request closed without merging**
