### PR TITLE
Update AWS storage options to 1.14 CSI compatible

### PR DESCRIPTION
**Pull request by Jeffwan**
**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**
Update AWS storage options to 1.14 CSI compatible

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by Jeffwan** [comment]
/cc @richardsliu 

a candidate for v1.0.2

**Comment by PatrickXYS** [comment]
@richardsliu  It looks good to me, can you take a look?

**Comment by sublimotion** [comment]
Looks good to me.

**Comment by Jeffwan** [comment]
```
go: finding github.com/kr/logfmt v0.0.0-20140226030751-b84e30acd515
go: finding github.com/gobuffalo/envy v1.6.5
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
go: finding github.com/coreos/go-systemd v0.0.0-20180511133405-39ca1b05acc7
go: finding github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc
go: error loading module requirements
make: *** [modules] Error 1
Makefile:35: recipe for target 'modules' failed
```

```
util.py                     72 INFO     go: finding modernc.org/cc v1.0.0
util.py                     72 INFO     go: error loading module requirements
util.py                     72 INFO     Makefile:71: recipe for target 'generate' failed
util.py                     72 INFO     make: *** [generate] Error 1
=============================== warnings summary ===============================
kfctl_go_test.py::test_build_kfctl_go
```

Seems it's failed to build `kfctl`

**Pull request merged**
