### PR TITLE
Pin manifest to stable tag v1.2.0

### PR DESCRIPTION
**Pull request by Jeffwan**
**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**
Pin manifests to official release tag. Following cherry-pick won't affect stable deployment

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by PatrickXYS** [comment]
```
W
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-5.4.0, py-1.9.0, pluggy-0.13.1
rootdir: /mnt/test-data-volume/kubeflow-manifests-presubmit-e2e-e2e-1672-342761e-2336-b785/src/kubeflow/kfctl/py/kubeflow/kfctl/testing/pytests
plugins: timeout-1.4.0
collected 1 item
kfctl_create_cluster_test.py::test_create_cluster
-------------------------------- live log call ---------------------------------
INFO     root:kfctl_create_cluster_test.py:25 Creating EKS Cluster
INFO     root:util.py:46 Running: /bin/bash -c /usr/local/bin/create-eks-cluster.sh
cwd=None
INFO     root:util.py:61 Subprocess output:
INFO     root:util.py:72 [ℹ]  eksctl version 0.30.0
INFO     root:util.py:72 [ℹ]  using region us-west-2
INFO     root:util.py:72 [ℹ]  setting availability zones to [us-west-2c us-west-2a us-west-2b]
INFO     root:util.py:72 [ℹ]  subnets for us-west-2c - public:192.168.0.0/19 private:192.168.96.0/19
INFO     root:util.py:72 [ℹ]  subnets for us-west-2a - public:192.168.32.0/19 private:192.168.128.0/19
INFO     root:util.py:72 [ℹ]  subnets for us-west-2b - public:192.168.64.0/19 private:192.168.160.0/19
INFO     root:util.py:72 [ℹ]  using Kubernetes version 1.17
INFO     root:util.py:72 [ℹ]  creating EKS cluster "eks-cluster-b2f40389" in "us-west-2" region with managed nodes
INFO     root:util.py:72 [ℹ]  will create 2 separate CloudFormation stacks for cluster itself and the initial managed nodegroup
INFO     root:util.py:72 [ℹ]  if you encounter any issues, check CloudFormation console or try 'eksctl utils describe-stacks --region=us-west-2 --cluster=eks-cluster-b2f40389'
INFO     root:util.py:72 [ℹ]  CloudWatch logging will not be enabled for cluster "eks-cluster-b2f40389" in "us-west-2"
INFO     root:util.py:72 [ℹ]  you can enable it with 'eksctl utils update-cluster-logging --enable-types={SPECIFY-YOUR-LOG-TYPES-HERE (e.g. all)} --region=us-west-2 --cluster=eks-cluster-b2f40389'
INFO     root:util.py:72 [ℹ]  Kubernetes API endpoint access will use default of {publicAccess=true, privateAccess=false} for cluster "eks-cluster-b2f40389" in "us-west-2"
INFO     root:util.py:72 [ℹ]  2 sequential tasks: { create cluster control plane "eks-cluster-b2f40389", 2 sequential sub-tasks: { no tasks, create managed nodegroup "linux-nodes" } }
INFO     root:util.py:72 [ℹ]  building cluster stack "eksctl-eks-cluster-b2f40389-cluster"
INFO     root:util.py:72 [ℹ]  deploying stack "eksctl-eks-cluster-b2f40389-cluster"
INFO     root:util.py:72 [✖]  unexpected status "CREATE_IN_PROGRESS" while waiting for CloudFormation stack "eksctl-eks-cluster-b2f40389-cluster"
INFO     root:util.py:72 [ℹ]  fetching stack events in attempt to troubleshoot the root cause of the failure
INFO     root:util.py:72 [!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
INFO     root:util.py:72 [ℹ]  to cleanup resources, run 'eksctl delete cluster --region=us-west-2 --name=eks-cluster-b2f40389'
INFO     root:util.py:72 [✖]  waiting for CloudFormation stack "eksctl-eks-cluster-b2f40389-cluster": RequestCanceled: waiter context canceled
INFO     root:util.py:72 caused by: context deadline exceeded
INFO     root:util.py:72 Error: failed to create cluster "eks-cluster-b2f40389"
FAILED
```

Failed to create cluster... Should be one-off issue

/retest

**Comment by PatrickXYS** [comment]
/lgtm
/approve
/hold

Hold to see other folks have any opinion os the PR

**Comment by berndverst** [comment]
/LGTM

Looks good for Azure (and all other manifests look good too from what I can tell)

**Pull request merged**
