### PR TITLE
add a selector to deployment config for xgboost-operator, change the …

### PR DESCRIPTION
**Pull request by xfate123**
…image version and apiVersion

**Which issue is resolved by this Pull Request:**
Resolves #
1. version unmatched
2. need selector
3.cannot pull image 

**Description of your changes:**
1. change the apiVersion to v1
2. add a selector
3. update the image version according to its'  gcr

### CODE REVIEW

**Comment by xfate123** [comment]
@googlebot I signed it!

**Comment by terrytangyuan** [comment]
@xfate123 Your commit comes from LemonIceStuff, which is why CLA isn't resolved. Try reset your commit and then do a force push.

**Comment by xfate123** [comment]
@terrytangyuan  Thanks for your advice, I will tried what you said

**Comment by xfate123** [comment]
@googlebot I fixed it.

**Comment by terrytangyuan** [comment]
@xfate123 There are no changes in your commits?

**Comment by xfate123** [comment]
@terrytangyuan I am so sorry. Cause I am kind new to this, still learning. Last time I forgot to sign in on my terminal before I commit.  And I don't know how to reset and force push. Can I close and push again for this one. Thank you so much

**Comment by terrytangyuan** [comment]
You can try the following and look up for anything that you are not familiar with:
```
git reset --soft HEAD~1
# Make sure you configured your git using the correct email and username, and then:
git commit -m "xxxx"
git push origin <yourBranchName> -f
```

**Comment by xfate123** [comment]
@terrytangyuan Thank you so much! I will try it

**Comment by xfate123** [comment]
@terrytangyuan everything looks good, thank you so much for teaching me.

**Pull request merged**
