### PR TITLE
feat(backend): Updated to make possible to evict pods even with empty dir. Fixes #4530 kubeflow/pipelines 

### PR DESCRIPTION
**Pull request by NikeNano**
**Which issue is resolved by this Pull Request:**
Resolves #4530 in kubeflow/pipelines see: https://github.com/kubeflow/pipelines/issues/4530

**Description of your changes:**

**Checklist:**
- [x] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by PatrickXYS** [comment]
Unit tests pass:
Make sure you have installed kustomize == 3.2.1
make generate-changed-only
make test

**Comment by NikeNano** [comment]
> Unit tests pass:
> Make sure you have installed kustomize == 3.2.1
> make generate-changed-only
> make test

Thanks, a rebase fixed the issues :)

**Comment by Bobgy** [comment]
/assign @thesuperzapper 
For review

**Comment by Bobgy** [comment]
/LGTM
/Approve
Thanks

**Pull request merged**
