### PR TITLE
Automated cherry pick of #941: Configure tolerations for istio-nodeagent so that it gets Cherry pick of #941 on v1.0-branch. #941: Configure tolerations for istio-nodeagent so that it gets

### PR DESCRIPTION
**Pull request by krishnadurai**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/964)

### CODE REVIEW

**Comment by krishnadurai** [comment]
@rafaelbarreto87 would you please consent to this PR as I'm looking to cherry-pick your changes to 1.0 release branch.

You just need to comment:
@googlebot I consent.

**Comment by jlewi** [comment]
@krishnadurai looks like tests are failing.

**Comment by jlewi** [comment]
Original issue: kubeflow/manifests#923

Do we need to cherry-pick this onto the 1.0 branch? It looks like the issue was about GPUs and ISTIO 1.3. But I think on GCP we are still using the older version of ISTIO?

**Comment by rafaelbarreto87** [comment]
@jlewi We're currently using the Dex deployment in a GKE cluster because it works better for our use case (it's easier to setup in a private cluster). Also, the fix, while works for GCP, is not GCP specific. The core problem is that istio-nodeagent does not get scheduled in all cluster nodes due to the lack of tolerations. This happens to apply to GPU node pools, but is generally applicable.

**Comment by jlewi** [comment]
@rafaelbarreto87 This PR is changing the 1.3 manifests of ISTIO on the 1.0 branch. It only makes sense to cherry-pick this onto the 1.0 branch if some of the 1.0 configs are using ISTIO 1.3. 

The GCP configs are still using ISTIO 1.2 so cherry-picking this onto the 1.0 branch is kind of a null op as far as GCP is concerned.

How would 1.0 configs pick up this change? Do we have KFDef configs on 1.0 that are using the 1.3 manifests?

I'd like to make sure that anything on the 1.0 branch that might be impacted by this change is reviewed by the appropriate reviewers.

It looks like the kfctl_istio_dex.yaml files are using the 1.3 install.
https://github.com/kubeflow/manifests/blob/a0f129168c2b58a6ee6700b6914ef8448769a963/kfdef/kfctl_istio_dex.v1.0.0.yaml#L25

So someone who owns that config should approve this CP.

/assign @yanniszark 

@krishnadurai  I think you can fix the CLA by rebasing the change and squashing commits. That will change the author of the commit to be you and the CLA check will pass.

**Comment by rafaelbarreto87** [comment]
@jlewi I read what you wrote too quickly and I completely understood it. Thought you're saying this should only be applied to the GCP manifests. Never mind that.

@googlebot I consent

**Comment by rafaelbarreto87** [comment]
@googlebot I consent

**Comment by krishnadurai** [comment]
@richardsliu @jlewi can this be included?

**Comment by krishnadurai** [comment]
@yanniszark could you PTAL?

**Comment by yanniszark** [comment]
If I understand correctly, the issue here is that we want the istio-nodeagent daemonset to run on all Nodes.
Some users have Nodes with special hardware (GPUs), on which the DaemonSet is not scheduled.
The current PR tolerates NoSchedule and NoExecute for all keys.

IMO, that's a bit too much.
If you are adding tolerations, you should know exactly what you're allowing.
For example, with the proposed configuration, nodeagent Pods will also run on the master Node.

I would propose the following:
* Add tolerations for common keys only (e.g., `nvidia.com/gpu`). I think the NVidia GPU one will solve 90% of the use-cases and the rest will need to patch the configuration with the values they need.
* Put any changes in an overlay.

What do you think?

**Comment by jlewi** [comment]
@yanniszark IIUC your comments would apply to the changes on master?

To be clear, I consider myself to be a bystander because for GCP we aren't using the ISTIO 1-3-1 configs and our plan is to move to Anthos Service Mesh and get of the business of maintaining ISTIO configs.

**Comment by krishnadurai** [comment]
Note: #923 was the original issue.

@yanniszark it does make sense to limit the tolerations to the specific key `nvidia.com/gpu=present`. You have mentioned the unintended consequences of not limiting the tolerations.

@jlewi this should apply to master as well.

I'll make the changes required in master.

cc: @rafaelbarreto87

**Pull request closed without merging**
