### PR TITLE
Step 1: Reorganize folder structure

### LINKED ISSUE #1738: Step 1: Reorganize folder structure
Part-of: https://github.com/kubeflow/manifests/issues/1735

Currently, the manifests repo is a flat namespace with everything mangled.
We plan to reorganize the folder structure into sections that will reflect the
following properties:
- Applications with their source code in upstream KF maintained by Kubeflow WGs (e.g., notebook-controller)
- Common services (Dex, Istio, Cert-Manager, KNative), maintained by the
  Manifests WG.
- Applications contributed by community members, not owned by any Kubeflow WG.
- Distribution-specific manifests (kfdef, stacks, aws, gcp, etc.). The goal is
  for this folder to become empty in subsequent releases.

BEFORE (folders only):
```
.
├── admission-webhook
├── application
├── argo
├── aws
├── cert-manager
├── common
├── default-install
├── dex-auth
├── docs
├── experimental
├── flink
├── gatekeeper
├── gcp
├── hack
├── istio
├── istio-1-3-1
├── jupyter
├── katib
├── kfdef
├── kfserving
├── knative
├── kubebench
├── kubeflow-roles
├── metacontroller
├── metadata
├── modeldb
├── mpi-job
├── mxnet-job
├── namespaces
├── pipeline
├── profiles
├── pytorch-job
├── seldon
├── spark
├── stacks
├── tektoncd
├── tests
├── tf-training
└── xgboost-job
```

AFTER (folders only):
```
.
├── apps
│   ├── admission-webhook/upstream
│   ├── centraldashboard/upstream
│   ├── jupyter/jupyter-web-app/upstream
│   ├── jupyter/notebook-controller/upstream
│   ├── katib/upstream
│   ├── kfserving/upstream
│   ├── kubebench/upstream
│   ├── mpi-job/upstream
│   ├── mxnet-job/upstream
│   ├── pipeline/upstream
│   ├── profiles/upstream
│   ├── pytorch-job/upstream
│   ├── tf-training/upstream
│   └── xgboost-job/upstream
├── common
│   ├── cert-manager
│   ├── dex-auth
│   ├── istio
│   ├── istio-1-3-1
│   ├── knative
│   ├── kubeflow-roles
│   └── namespaces
├── contrib
│   ├── application
│   ├── argo
│   ├── basic-auth
│   ├── default-install
│   ├── experimental
│   ├── flink
│   ├── gatekeeper
│   ├── metacontroller
│   ├── metadata
│   ├── modeldb
│   ├── seldon
│   ├── spark
│   ├── spartakus
│   └── tektoncd
├── distributions
│   ├── aws
│   ├── gcp
│   ├── kfdef
│   └── stacks
├── docs
├── hack
└── tests

```

### PR DESCRIPTION
**Pull request by yanniszark**
**Which issue is resolved by this Pull Request:**
Resolves https://github.com/kubeflow/manifests/issues/1738
Umbrella issue: https://github.com/kubeflow/manifests/issues/1735

**Description of your changes:**
Currently, the manifests repo is a flat namespace with everything mangled.
This PR reorganizes the folder structure into sections that will reflect the
following properties:
- Applications with their source code in upstream KF maintained by Kubeflow WGs (e.g., notebook-controller)
- Common services (Dex, Istio, Cert-Manager, KNative), maintained by the
  Manifests WG.
- Applications contributed by community members, not owned by any Kubeflow WG.
- Distribution-specific manifests (kfdef, stacks, aws, gcp, etc.). The goal is
  for this folder to become empty in subsequent releases.

### CODE REVIEW

**Comment by elikatsis** [comment]
Thank you Yannis!

I'll review this
/assign @elikatsis

**Comment by moficodes** [comment]
@yanniszark are we updating the paths for the kfdefs? 

would it not break the kfdef at this state?

**Comment by yanniszark** [comment]
> are we updating the paths for the kfdefs?

@moficodes not at the moment. This is something planned after step 4 (https://github.com/kubeflow/manifests/issues/1735) because the structure of many upstream kustomizations may change again. Before the 1.3 release, distribution owners will have enough time to import the kustomizations they want.

> would it not break the kfdef at this state?

Correct! However, interim commits are not guarranteed to be good, especially in the middle of this restructuring. In contrast, the release will be validated.

**Comment by moficodes** [comment]
@yanniszark  thanks for the clarification. 

Just to confirm, are we merging all 4 phases at once? becase there are kfdefs that rely on master. and if we merge this to master those kfdefs stop working.

**Comment by PatrickXYS** [comment]
> @yanniszark thanks for the clarification.
> 
> Just to confirm, are we merging all 4 phases at once? becase there are kfdefs that rely on master. and if we merge this to master those kfdefs stop working.

I think we need to rely on stable branches instead, e.g, v1.1-branch, v1.2-brannch, the user should use kfdef referenced in corresponding branches instead.

Can you clarify what's the use case user need to use kfdef in the master branch in production environment?

**Comment by moficodes** [comment]
for example the kfdef for openshift that uses tekton for pipeline is using master. (i think its the only kfdef like this) https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_openshift.master.kfptekton.yaml

i think its fine since master is a development branch.

**Comment by PatrickXYS** [comment]
I see it's because this is done after 1.2,

but we haven't cut 1.3 release yet

**Comment by moficodes** [comment]
Yeah. I dont think its going to break any production application. But if we merge something to master I would think we would want make sure all the kfdef targetting master is working.

**Comment by yanniszark** [comment]
@moficodes manifests only provides a guarantee for release branches to be stable. It is expected that some changes (like paths changes) can break distributions between releases. Distributions should be updated asynchronously, after the release of the stable branch.
After all, in the near future, where distributions will live outside manifests, it won't be reasonable to block manifests PRs on them. This is the same case now.

**Comment by moficodes** [comment]
Understood. Thanks @yanniszark

**Pull request merged**
