### PR TITLE
Automated cherry pick of #549: kfdef: existing_arrikto: add cert-manager Cherry pick of #549 on v0.7-branch. #549: kfdef: existing_arrikto: add cert-manager

### PR DESCRIPTION
**Pull request by yanniszark**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/617)

### CODE REVIEW

**Comment by yanniszark** [comment]
Related to https://github.com/kubeflow/manifests/issues/616

/assign @jlewi @krishnadurai

**Comment by jlewi** [comment]
@yanniszark Is there any risk to other 0.7 configs if we cherry pick these changes?

It looks like this PR is adding an overlay so presumably other configs are completely unaffected.

**Comment by yanniszark** [comment]
@jlewi I would expect it not to. I will rebase to get green tests.

**Comment by yanniszark** [comment]
@jlewi all tests are green after the rebase.
As mentioned, this should only affect the istio_dex config.
I'm leaving a hold in case you want to do another review here.

/approve
/hold

**Pull request merged**
