### PR TITLE
Revert master broken changes

### PR DESCRIPTION
**Pull request by kunmingg**
**Which issue is resolved by this Pull Request:**
Resolves https://github.com/kubeflow/manifests/issues/426

**Description of your changes:**
- revert PRs:
    https://github.com/kubeflow/manifests/pull/424
    https://github.com/kubeflow/manifests/pull/405
    https://github.com/kubeflow/manifests/pull/401
    https://github.com/kubeflow/manifests/pull/410
    https://github.com/kubeflow/manifests/pull/342
- (temporary) point kfdef config to 3e85b3c83de12fed7d675151d0d4f8474eb04790

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/427)

### CODE REVIEW

**Comment by jlewi** [comment]
@kunmingg Why did you pin the version of kubelfow/manifests in kfctl_gcp_iap.yaml etc..

**Comment by jlewi** [comment]
Here's a clean roll back
https://github.com/kubeflow/manifests/pull/429

**Comment by kunmingg** [comment]
I try to pin the version so presubmit will use https://github.com/kubeflow/manifests/commit/3e85b3c83de12fed7d675151d0d4f8474eb04790

**Comment by jlewi** [comment]
@kunmingg presubmits already modify kfdef in order to use the version of the code in the presubmit.
https://github.com/kubeflow/kubeflow/blob/6ddf28cc772a8ec54f842082d9466c87ec3083e1/testing/kfctl/kfctl_go_test.py#L134

**Comment by kunmingg** [comment]
Got it, we can close this one.

**Comment by richardsliu** [comment]
Jeremy's change got merged so let's close this one.
/close

**Pull request closed without merging**
