### PR TITLE
Fix formatting issue in aws/nvidia-device-plugin manifest

### LINKED ISSUE #1166: Encountered error applying application mpi-operator
Getting this error installing latest master manifest 

> time="2020-05-14T22:16:48Z" level=warning msg="Encountered error applying application mpi-operator:  (kubeflow.error): Code 500 with message: Apply.Run  Error unable to recognize \"/tmp/kout844630924\": no matches for kind \"CustomResourceDefinition\" in version \"apiextensions.k8s.io/v1\"" filename="kustomize/kustomize.go:202"

### PR DESCRIPTION
**Pull request by terrytangyuan**
**Which issue is resolved by this Pull Request:**
Resolves #1166
cc @apryiomka
/cc @Jeffwan 

**Description of your changes:**

Fixes the following error:
```
Error: failed to apply: (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize: (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for nvidia-device-plugin Error accumulating resources: accumulating resources from 'overlays/application/application.yaml': YAML file [overlays/application/application.yaml] encounters a format error.
error converting YAML to JSON: yaml: line 25: did not find expected '-' indicator
```

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by Jeffwan** [comment]
```
fatal: reference is not a tree: fb6d35607c7f3c4dd93ab33799be83ae8cde42e2
```

Seems a weird issue, I will check CI jobs.

**Comment by Jeffwan** [comment]
@terrytangyuan Seems this PR https://github.com/kubeflow/manifests/pull/1175 fix this change as well.

**Comment by terrytangyuan** [comment]
Okay I am closing this for now.

**Pull request closed without merging**
