### PR TITLE
Update 20220926-contrib-component-guidelines.md

### PR DESCRIPTION
**Pull request by juliusvonkohout**
@kimwnasptd  @annajung this was missing from https://github.com/kubeflow/manifests/pull/2286#issuecomment-1273554536 and exspecially the kuberay integration shows that proper projects can easily implement it.

### CODE REVIEW

**Comment by annajung** [comment]
I think this is a fair ask and definitely a good practice! If we like to enforce this during the [current clean up effort](https://github.com/kubeflow/manifests/issues/2311), we should try to get this merged soon & communicate this to /contrib component owners

cc @kimwnasptd

**Comment by juliusvonkohout** [comment]
@kimwnasptd 
The most important ones (Seldon and kserve) already work with the predecessor of PSS. I am running it with similar restrictions (and istio-cni) for over one year.  Kuberay does so as well and they will go even one step further as detailed in https://github.com/ray-project/kuberay/pull/750. So the restricted PSS still allows to run as a specific non-root user but the kuberay developers want to become even better than that.

**Comment by kimwnasptd** [comment]
After some discussion with @juliusvonkohout we decided to use this PR towards the overarching goal of better defining the implementation details (or technical requirements) that we would expect from the contrib components.

We've had context around this in other places, like https://github.com/kubeflow/manifests/pull/2286#issuecomment-1273538637.

The first step will be to break down the requirements to 2 categories:
* Structural requirements
* Technical requirements

The first category is regarding what we currently have. Requirements regarding the file structure of the addons. Things like having a README, exposing upgrade instructions and examples. 

Then the next one will be a list of more technical requirements that we will expect these addons to follow

**Comment by kimwnasptd** [comment]
Some aspects that I believe we'll need to re-evaluate are:
* Defining the least subset of **required** criteria for accepting new components
* Re-think the deprecation process, since we are adding more requirements

Also we could think about a model where we explicitly "rank"/document how much an addon aligns with the requirements. So that users looking at different addons can know the state and be able to decide which ones they want to add in their platform

cc @annajung

**Comment by kimwnasptd** [comment]
Adding some items we discussed with @juliusvonkohout and @kromanow94 live as functional requirements:
* Running with baseline PSS
* [stretch] Namespace isolation
* [stretch] Running with strict PSS
* [stretch] Running with Istio sidecars

**Comment by juliusvonkohout** [comment]
> Adding some items we discussed with @juliusvonkohout and @kromanow94 live as functional requirements:
> 
>     * Running with baseline PSS
> 
>     * [stretch] Namespace isolation
> 
>     * [stretch] Running with strict PSS
> 
>     * [stretch] Running with Istio sidecars

i have added the necessary changes.

**Comment by kimwnasptd** [comment]
/lgtm

Thanks @juliusvonkohout!

**Pull request merged**
