### PR TITLE
Katib: Re-add per component packages

### LINKED ISSUE #1159: katib add support for external databases - refactor manifests
A PR to do this was #1141

This got reverted in #1158 because it broke the tests. The policy is to roll back fix and then forward fix. Apologies @discordianfish .

As discussed [here](https://github.com/kubeflow/manifests/issues/1157#issuecomment-625267395) I think the PR got merged off an old base which didn't include a new test that verifies certain common labels aren't set.

@discordianfish would you mind submitting a forward fix by reverting #1158 and getting the tests to pass?

### PR DESCRIPTION
**Pull request by discordianfish**
This reverts commit a03973bb6d5fd6d447f57a8f17512298bdc716ec.

**Which issue is resolved by this Pull Request:**
Resolves #1159

**Description of your changes:**
Re-add the katib changes from #1141 that have been reverted due to failing tests.

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by discordianfish** [comment]
@jlewi Ok tests pass locally but looks like CI servers have been running out of space.

**Comment by jlewi** [comment]
/lgtm
/approve

Tests are failing because NFS is full @Jeffwan is working on fixing this.

**Comment by discordianfish** [comment]
Looks like it was still out of space? Has this been fixed now?
/retest

**Comment by Jeffwan** [comment]
disk issue has been resolved. It still have resource quota issue not resolved yet

**Comment by discordianfish** [comment]
Let see how far it gets
/retest

**Comment by discordianfish** [comment]
Ok great, tests pass. Can we merge it now?

**Comment by discordianfish** [comment]
Oh magic

**Pull request merged**
