### PR TITLE
update central dashboard

### PR DESCRIPTION
**Pull request by kunmingg**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/166)

### CODE REVIEW

**Comment by kunmingg** [comment]
/assign @avdaredevil 
Should we update to v0.6?

**Comment by avdaredevil** [comment]
Hey @kunmingg could you explain this change?

/cc @avdaredevil 
/cc @prodonjs 
/unassign @avdaredevil 
/assign @kunmingg 
/area front-end
/area central-dashboard

**Comment by prodonjs** [comment]
@avdaredevil Kustomize is replacing ksonnet so this is the going-forward method of making the change you did in https://github.com/kubeflow/kubeflow/pull/3466. The image being pointed to here has all changes committed to master as of 6/21/19, so if we get nothing else in by the cut date this we be suitable for 0.6.0.

/lgtm

**Comment by kunmingg** [comment]
@avdaredevil 
I plan to update components images to latest on master head.
For central dashboard should we use v0.6.0-rc2 or newer ones?

**Pull request merged**
