### PR TITLE
README: Add component version matrix

### PR DESCRIPTION
**Pull request by yanniszark**
**Description of your changes:**
Add a matrix with each component and the included manifests version.

Refs: https://github.com/kubeflow/manifests/issues/1775

### CODE REVIEW

**Comment by yanniszark** [comment]
cc @kubeflow/wg-manifests-leads

**Comment by StefanoFioravanzo** [comment]
Hey @yanniszark, thanks!

I see that the Katib and KFServing versions don't point to the release tags, is there a particular reason for that?

**Comment by yanniszark** [comment]
@StefanoFioravanzo that's a good question. Those are the desired versions that KFServing and Katib gave us:
https://github.com/kubeflow/manifests/issues/1775
https://github.com/kubeflow/manifests/pull/1840

**Comment by StefanoFioravanzo** [comment]
@yanniszark I see, thanks!

/lgtm
/approve

**Pull request merged**
