### PR TITLE
Migrate Kfdef to v1beta1

### PR DESCRIPTION
**Pull request by gabrielwen**
Migrate all `KfDef` to v1beta1 format.

Ran with command:
`kfdef-converter tov1beta1 <filename>`

Related to: kubeflow/kubeflow#3703

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/553)

### CODE REVIEW

**Comment by jlewi** [comment]
/assign @yanniszark 
/assign @Jeffwan 

Could you please take a look?

**Comment by yanniszark** [comment]
@gabrielwen @jlewi a recent change has resulted in conflicts for the kfctl_existing_arrikto file.
Is it possible to do a rebase?

In addition, I expect that the only changes are formatting changes, correct?

**Comment by gabrielwen** [comment]
> @gabrielwen @jlewi a recent change has resulted in conflicts for the kfctl_existing_arrikto file.
> Is it possible to do a rebase?
> 
> In addition, I expect that the only changes are formatting changes, correct?

Correct, we are only to migrate the API version.

**Comment by gabrielwen** [comment]
@yanniszark rebased, could you take a look when you have a chance?  thanks!

**Comment by yanniszark** [comment]
@gabrielwen thanks a lot :smile:

**Pull request merged**
