### PR TITLE
fix dex-login-test

### PR DESCRIPTION
**Pull request by tzabbi**
# Pull Request Template for Kubeflow manifests Issues

- set executable permission for python script
- set shebang line in python script

## ✅ Contributor checklist
  - Make sure you have tested with kustomize. See [Installation Prerequisites](https://github.com/kubeflow/manifests#prerequisites)
  - All the commits have been _signed-off_  (To pass the `DCO` check)
  - Submit the [Contributor License Agreements](https://cla.developers.google.com/clas) (To pass the `cla/google` check)

---     
 
> You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### CODE REVIEW

**Comment by tzabbi** [comment]
@juliusvonkohout do you now what has to be deployt that we can log into the central dashboard?

**Comment by juliusvonkohout** [comment]
You might want to take a look at https://github.com/kubeflow/manifests/blob/master/.github/workflows/notebook_controller_m2m_test.yaml and other files there for reference

**Comment by juliusvonkohout** [comment]
https://github.com/kubeflow/manifests/pull/2805 is also worth a look

**Comment by juliusvonkohout** [comment]
But what you have looks also good. We have to anyway restructure our tests in https://github.com/kubeflow/manifests/pull/2805 and other PRs

**Comment by tzabbi** [comment]
Ready for review

**Pull request merged**
