### PR TITLE
Fix CNRM cluster package.

### PR DESCRIPTION
**Pull request by jlewi**
* namespace should be set in kustomization.yaml; not in the
  actual resource. If we set it in the resource then if we have kustomize
  subpackages that try to patch the resource kustomize won't be able
  to find the original resource.

### CODE REVIEW

**Comment by jlewi** [comment]
@Bobgy @rmgogogo @kunmingg Does one of you want to volunteer to review this?

**Comment by rmgogogo** [comment]
I reviewed yesterday but TBH didn't have enough knowledge to catch the details yet.
Any docs I can refer?

LGTM first to unblock your side work.

/lgtm

**Comment by jlewi** [comment]
Thanks @Bobgy  

/approve

**Pull request merged**
