### PR TITLE
[kubeflow 1.8] Update kubeflow/training-operator manifests from v1.7.0-rc.0

### PR DESCRIPTION
**Pull request by DnPlas**
Sync kubeflow/training-operator tag v1.7.0-rc.0 manifests

WG leads @andreyvelich @johnugeorge @kubeflow/wg-training-leads 
WG liaison @nagar-ajay 
cc: @annajung @jbottum

### CODE REVIEW

**Comment by jbottum** [comment]
good job!  question - Are the revision numbers correct in the Readme ?  many of the components are listed as 1.7

**Comment by DnPlas** [comment]
> good job! question - Are the revision numbers correct in the Readme ? many of the components are listed as 1.7

Yup, the training-operator version for Kubeflow 1.8 is 1.7

**Comment by annajung** [comment]
cc @kimwnasptd for approval

**Comment by kimwnasptd** [comment]
Thanks Daniela!

/approve

**Pull request merged**
