### PR TITLE
Seldon 1.4.0 Upgrade for Kubeflow 1.2 Release

### PR DESCRIPTION
**Pull request by cliveseldon**
**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**

 * Upgrade seldon to 1.4.0
 * Also fixes 1.18 k8s compatability

**Checklist:**
- [*] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by cliveseldon** [comment]
Presubmit is failing for `No space left on device`

```
W
+ SRC_DIR=/mnt/test-data-volume/kubeflow-manifests-presubmit-unit-1600-d4ea16e-8928-b452/src
+ mkdir -p /src/kubeflow
+ git clone --depth=2 --no-single-branch https://github.com/kubeflow/manifests.git /mnt/test-data-volume/kubeflow-manifests-presubmit-unit-1600-d4ea16e-8928-b452/src/kubeflow/manifest
s
fatal: could not create leading directories of '/mnt/test-data-volume/kubeflow-manifests-presubmit-unit-1600-d4ea16e-8928-b452/src/kubeflow/manifests': No space left on device
```

**Comment by PatrickXYS** [comment]
The error is expected, check issue here https://github.com/kubeflow/testing/issues/769

**Comment by cliveseldon** [comment]
@animeshsingh @krishnadurai Can we get this in for 1.2 Kubeflow release?

**Comment by PatrickXYS** [comment]
Can you rebase master and re-run test?

**Comment by cliveseldon** [comment]
@PatrickXYS Not sure this has help - tests still blocked/failing?

**Comment by PatrickXYS** [comment]
```
   TestValidK8sResources: validate_resources_test.go:236: Path ../seldon/seldon-core-operator/base/resources.yaml; resource seldondeployments.machinelearning.seldon.io; has status field
```

Unit test failed, can you generate test and make test again?

**Comment by PatrickXYS** [comment]
/lgtm
/approve
/hold
@cliveseldon Feel free to unhold when you feel it's good to

**Comment by cliveseldon** [comment]
@PatrickXYS Thanks!

**Pull request merged**
