### PR TITLE
Fix apps description in example/kustomization.yaml

### PR DESCRIPTION
**Pull request by mtszkw**
**Which issue is resolved by this Pull Request:**
No issue was created for this I believe, just noticed the "typo" when I was adjusting my kustomization.yaml.

**Description of your changes:**
Comments above Tensorboard Controller and Web App were swapped, so I just fixed that.

**Checklist:**
- [x] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by mtszkw** [comment]
@googlebot I signed it!

**Comment by kimwnasptd** [comment]
/ok-to-test

Good catch!

**Pull request merged**
