### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by khushveermalviya**
adding every purpose command for kubctl

**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 5.2.1+**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
I think this is mostly basic Kubernetes knowledge. @diegolovison what do you think?

**Comment by diegolovison** [comment]
Hi @juliusvonkohout 
I have the same opinion as yours

**Comment by khushveermalviya** [comment]
Yes ,As beginners i confused between command lines and more.

**Comment by juliusvonkohout** [comment]
@khushveermalviya this really belongs to a kubernetes tutorial, not Kubeflow. You need to understand Kubernetes to install Kubeflow.

since the documentation lead thinks so as well i will close this.

Please join the slack channel wg-manifests and our regaular meetings (tomorrow as well) if you want to propose new things

https://www.kubeflow.org/docs/about/community/

**Pull request closed without merging**
