### PR TITLE
Pin GKE to 1.14.8 because the latest 1.14 release breaks workload identity

### PR DESCRIPTION
**Pull request by jlewi**
Related to kubeflow/kubeflow#4693

**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**

**Checklist:**
- [ ] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/759)

### CODE REVIEW

**Comment by kunmingg** [comment]
Looks same as https://github.com/kubeflow/manifests/pull/758,
you might want to merge to v1.0 branch?

**Comment by jlewi** [comment]
Thanks @kunmingg for catching that.

**Pull request closed without merging**
