### PR TITLE
cherry-pick: Permissions for Knative objects

### PR DESCRIPTION
**Pull request by kimwnasptd**
Cherry-pick https://github.com/kubeflow/manifests/pull/1877

cc @henrysecond1 @pvaneck 
/cc @elikatsis 
/assign @kimwnasptd

### CODE REVIEW

**Comment by kimwnasptd** [comment]
@henrysecond1 could you add a `@googlebot I consent.` comment?

**Comment by henrysecond1** [comment]
Sure, thanks for the review.

@googlebot I consent.

**Comment by pvaneck** [comment]
@henrysecond1 May have to try triggering the cla bot again with a new comment with just the `@googlebot I consent.` line

**Comment by henrysecond1** [comment]
@googlebot I consent.

**Pull request merged**
