### PR TITLE
Cherry pick Seldon Changes

### PR DESCRIPTION
**Pull request by cliveseldon**
Cherry pick of PR for Seldon Changes for 0.4.0

I couldn't run the automated cherry pick as my original PR #273 included a rebase which seems to cause issues when I run:

```
master-kubeflow/hack/cherry_pick_pull.sh upstream/v0.6-branch 273
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/304)

### CODE REVIEW

**Comment by abhi-g** [comment]
/cc jlewi
Clive, any specific reason the presubmit was skipped

**Comment by cliveseldon** [comment]
@abhi-g not sure what you mean by pre-submit skipped. Can you expand?

**Comment by abhi-g** [comment]
Clive on the PR page in GitHub the prow not lists all pre requisite for
merge towards the bottom in a table. There for this PR it's saying that the
kubeflow-manifests-presubmit status is skipped. Not sure why that is the
case. Generally I expect it to say whether the tests passed or failed.

**Comment by cliveseldon** [comment]
I don't know why the pre-submit was skipped. @yanniszark ?

**Comment by swiftdiaries** [comment]
I think it's because prow is only configured on the master branch. Since this PR is merging to the v0.6-branch the job wasn't triggered

**Comment by jlewi** [comment]
@swiftdiaries good catch we should setup the tests to run on the release branch; looks like that got overlooked

**Comment by jlewi** [comment]
Closing this as obsolete.

**Pull request closed without merging**
