### PR TITLE
Sync kserve manifests 0.13.0

### PR DESCRIPTION
**Pull request by ca-scribner**
Updates kserve to v0.13.0 from v0.12.1

This update was generated using the procedure from contrib/kserve/UPGRADE.md, not using hacks/sync-kserve-kserve-manifests.sh, because kserve [appears to have forgotten to add 0.13.0 to their `install/` directory](https://github.com/kserve/kserve/tree/v0.13.0/install/v0.13.0).  Instead, the manifests here have been pulled directly from [the 0.13.0 release assets](https://github.com/kserve/kserve/releases/tag/v0.13.0)

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
@ca-scribner Please tag the kserve maintainers. I would like to get approval from one of them.

**Comment by ca-scribner** [comment]
@juliusvonkohout I've [asked for their thumbsup](https://cloud-native.slack.com/archives/C06AH2C3K8B/p1718111127227529)

**Comment by juliusvonkohout** [comment]
@diegolovison can you test this?

@rimolive we also need this in rc.2

**Pull request merged**
