### PR TITLE
Katib manifests for Kubeflow 1.1

### PR DESCRIPTION
**Pull request by andreyvelich**
**Which issue is resolved by this Pull Request:**
Part of: https://github.com/kubeflow/katib/issues/1211.

**Description of your changes:**
This is the manifests changes for Katib in Kubeflow 1.1.
I updated images version to the latest commit and I made few changes according to the Katib release issue.

/assign @jlewi @johnugeorge @gaocegege 

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by andreyvelich** [comment]
I changed image tag from 5df1bd2 to 917164a.

917164a should have most recent changes and contains SDK for Katib which we mentioned on the website.
/cc @johnugeorge @gaocegege

**Comment by johnugeorge** [comment]
This has all the latest fixes
/lgtm

**Comment by jlewi** [comment]
@andreyvelich @johnugeorge can one of you please /approve this?

**Comment by shawnzhu** [comment]
I got error when running `make test` in the `tests` folder. looks like these files are should be changed as well:

https://github.com/kubeflow/manifests/blob/6e0925a6bc162873892200d9bb5b691794c8e2c2/tests/stacks/examples/alice/test_data/expected/%7Eg_v1_configmap_katib-config.yaml#L6-L38

https://github.com/kubeflow/manifests/blob/6e0925a6bc162873892200d9bb5b691794c8e2c2/tests/stacks/generic/test_data/expected/%7Eg_v1_configmap_katib-config.yaml#L6-L38

If this is the case, do you mind if I create a PR to fix them?

**Pull request merged**
