### PR TITLE
Update kubeflow/kfp-tekton manifests from v1.2.1

### PR DESCRIPTION
**Pull request by yhwang**
Ref: https://github.com/kubeflow/manifests/issues/2194#issuecomment-1140065302
Updates the KFP Tekton component to `v1.2.1`

Signed-off-by: Yihong Wang <yh.wang@ibm.com>

### CODE REVIEW

**Comment by kimwnasptd** [comment]
Thanks for the PR @yhwang!

/lgtm
/approve

**Comment by yhwang** [comment]
@kimwnasptd thanks, I rebased and solved the README conflicts. can you re-approve it again? Thanks!

**Comment by kimwnasptd** [comment]
Thank you @yhwang!

/lgtm 
/approve

**Pull request merged**
