### PR TITLE
Add application name for seldon and mpi-operator

### LINKED ISSUE #517: Miss application name for some of components
I get two empty names when we deploy applications. I found I forgot to have a name field for seldon and mpi-operator

https://github.com/kubeflow/manifests/blob/bc64c99dbdbbe7833812f20232e48010d963e163/kfdef/kfctl_aws.yaml#L249-L260

This is only for aws kfdef files.

```
INFO[0003] Processing application: persistent-agent      filename="kustomize/kustomize.go:443"
INFO[0003] Processing application: pipelines-runner      filename="kustomize/kustomize.go:443"
INFO[0003] Processing application: pipelines-ui          filename="kustomize/kustomize.go:443"
INFO[0003] Processing application: pipelines-viewer      filename="kustomize/kustomize.go:443"
INFO[0003] Processing application: scheduledworkflow     filename="kustomize/kustomize.go:443"
INFO[0003] Processing application: pipeline-visualization-service  filename="kustomize/kustomize.go:443"
INFO[0003] Processing application: profiles              filename="kustomize/kustomize.go:443"
INFO[0003] Processing application:                       filename="kustomize/kustomize.go:443"
INFO[0003] Processing application:                       filename="kustomize/kustomize.go:443"
INFO[0003] Processing application: istio-ingress         filename="kustomize/kustomize.go:443"
INFO[0003] Processing application: aws-alb-ingress-controller  filename="kustomize/kustomize.go:443"
INFO[0003] Processing application: nvidia-device-plugin  filename="kustomize/kustomize.go:443"

```

### PR DESCRIPTION
**Pull request by Jeffwan**
**Which issue is resolved by this Pull Request:**
Resolves #517 

**Description of your changes:**
Add application name and make sure they're populated in `kfctl build`

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/518)

### CODE REVIEW

**Comment by jlewi** [comment]
@Jeffwan Do you know why the test is failing?

**Comment by Jeffwan** [comment]
Rebase the changes.  I am trying to follow the way you showed yesterday to debug the test failures. :D

**Comment by Jeffwan** [comment]
@jlewi  Probably just flaky tests. I will post the errors messages next time I see similar and then we we fix them.

**Pull request merged**
