### PR TITLE
Update Argo component to v2.8.0

### PR DESCRIPTION
**Pull request by saschagrunert**
**Which issue is resolved by this Pull Request:**

None

**Description of your changes:**

Supersedes: https://github.com/kubeflow/manifests/pull/642
Refers to:vhttps://github.com/kubeflow/pipelines/pull/3537

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

**Side Nodes:***
- Some unit tests seem to fail but the argo legacy tests are successful.
- Deployed it on my local machine and it seems to work.

### CODE REVIEW

**Comment by saschagrunert** [comment]
This is ready for review. The update of the final version should be just a removal of the `-rc3`'s.

**Comment by saschagrunert** [comment]
Updated it to the final 2.8.0 release

**Comment by thesuperzapper** [comment]
@saschagrunert what is happening with this PR?

**Comment by saschagrunert** [comment]
> @saschagrunert what is happening with this PR?

I'm waiting for review :shrug:

**Comment by desaintmartin** [comment]
Should it be recreated/reopened?

**Comment by saschagrunert** [comment]
> Should it be recreated/reopened? Or Should it be re-created for 2.10?

I can still work on this. Before doing so I'd like to get feedback if the change is actually wanted. Not sure if any of the approvers/maintainers can ack on that :)

**Pull request closed without merging**
