### PR TITLE
Update Katib images for Kubeflow 1.3.1

### PR DESCRIPTION
**Pull request by andreyvelich**
**Which issue is resolved by this Pull Request:**
Related: https://github.com/kubeflow/manifests/issues/1890.

**Description of your changes:**
This is updated Katib 0.11.1 images for Kubeflow 1.3.1 release.

/assign @yanniszark @gaocegege @johnugeorge 

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by johnugeorge** [comment]
merge it ?

**Comment by andreyvelich** [comment]
> merge it ?

If @kubeflow/wg-manifests-leads are fine with these changes we can merge it.

**Comment by yanniszark** [comment]
@andreyvelich thanks for the PR!
Could you update the README.md file to point to the revision you are using?

**Comment by andreyvelich** [comment]
> @andreyvelich thanks for the PR!
> Could you update the README.md file to point to the revision you are using?

Sure, done

**Comment by andreyvelich** [comment]
This PR was implemented as part of: https://github.com/kubeflow/manifests/pull/1919.
cc @yanniszark

**Pull request closed without merging**
