### PR TITLE
add gcp basic-auth-ingress application overlay

### LINKED ISSUE #467: add application overlay for  basic-auth-ingress

### PR DESCRIPTION
**Pull request by kkasravi**
**Which issue is resolved by this Pull Request:**
Resolves #467

**Description of your changes:**
added basic-auth-ingress application overlay and updated kfdef/kfctl_gcp_basic_auth.yaml

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/468)

### CODE REVIEW

**Comment by jlewi** [comment]
@kkasravi  Please rebase to pick up #498; that's likely causing the test failure.

**Comment by kkasravi** [comment]
@richardsliu @jlewi i think this just needs a lgtm

**Pull request merged**
