### PR TITLE
Added PSS profile seccompProfile to pods of istio

### PR DESCRIPTION
**Pull request by biswajit-9776**
# Pull Request Template for Kubeflow manifests Issues

- Please include a summary of changes and the related issue. 
- List any dependencies that are required for this change. 
- Please delete the options that are not relevant.
- The following checklist will help you to satisfy the requirements.

  
## ✅ Unit Test Checklist
  
  - [ ] 🛠️ Make sure you have installed kustomize == 5.2.1+     
  - [ ] ✍️ Have you written new tests for your core changes, as applicable?      
  - [ ] 🔄 Have you successfully run existing tests with your changes ?    
  - [ ] 🚀 Have you successfully run existing and new tests with your changes ?

## ✅ Contributor checklist
  - [ ] All the commits have been _signed-off_  (To pass the `DCO` check)
  - [ ] Submit the [Contributor License Agreements](https://cla.developers.google.com/clas) (To pass the `cla/google` check)

---     
 
> You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### CODE REVIEW

**Comment by biswajit-9776** [comment]
I have tested on cluster for both _audit_ and _enforce_ mode of PSS labels.
Previously the pods were only failing for the enforce=restricted label.
Post the changes in this PR, the pods are successfully created for all modes of PSS.

**Comment by juliusvonkohout** [comment]
Hello, this must be done automatically via istioctl or istio profiles or kustomize overlays/components, not manually.

**Comment by biswajit-9776** [comment]
Hi, I'm looking for a method of setting seccompProfile during installation like:
```yaml
istioctl install --set values.global.proxy.seccompProfile.type=RuntimeDefault
```
I haven't encountered anything like it yet; meanwhile, I would set these changes as kustomize component in our contrib/security directory.

**Comment by juliusvonkohout** [comment]
> Hi, I'm looking for a method of setting seccompProfile during installation like:
> 
> ```yaml
> istioctl install --set values.global.proxy.seccompProfile.type=RuntimeDefault
> ```
> 
> I haven't encountered anything like it yet; meanwhile, I would set these changes as kustomize component in our contrib/security directory.

You can add them directly to both istio folders in https://github.com/kubeflow/manifests/blob/master/common/istio-1-22/kubeflow-istio-resources/base/kustomization.yaml as long as this is a static file that is not by the synchronization scripts in /hack.

**Comment by biswajit-9776** [comment]
> > Hi, I'm looking for a method of setting seccompProfile during installation like:
> > ```yaml
> > istioctl install --set values.global.proxy.seccompProfile.type=RuntimeDefault
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I haven't encountered anything like it yet; meanwhile, I would set these changes as kustomize component in our contrib/security directory.
> 
> You can add them directly to both istio folders in https://github.com/kubeflow/manifests/blob/master/common/istio-1-22/kubeflow-istio-resources/base/kustomization.yaml as long as this is a static file that is not modified by the synchronization scripts in /hack.

So, the two components should be used in ` https://github.com/kubeflow/manifests/blob/master/common/istio-1-22/kubeflow-istio-resources/base/kustomization.yaml`  instead of the example/kustomization.yaml?

**Comment by juliusvonkohout** [comment]
Should the two patches be used in ` https://github.com/kubeflow/manifests/blob/master/common/istio-1-22/kubeflow-istio-resources/base/kustomization.yaml`  instead of the example/kustomization.yaml?

Yes, this is something we can do directly. Please check whether the kustoization.yaml is static.

**Comment by biswajit-9776** [comment]
No, this file isn't modified by any scripts or other files. It's just used in workflows and some tests.

**Comment by juliusvonkohout** [comment]
Let's try in general.

**Comment by biswajit-9776** [comment]
`https://github.com/kubeflow/manifests/blob/master/common/istio-1-22/kubeflow-istio-resources/base/kustomization.yaml`

This kustomization doesn't have the required resources for the deployments in our patches as our deployments are part of istio-install/base/install.yaml

A better idea I could think of is `istio-1-22/istio-install/base/patches.` Since, the install.yaml is in the _resources:_ section of `istio-1-22/istio-install/base/kustomization.yaml`, our deployments can get patched successfully.

**Comment by juliusvonkohout** [comment]
Then lets go with https://github.com/kubeflow/manifests/blob/master/common/istio-1-22/istio-install/base/kustomization.yaml and the same for CNI.

**Comment by juliusvonkohout** [comment]
It looks good so far an will take a closer look soon.
We have to make sure, that this is also copied to the istio-1-23 folder if we upgrade with the synchronisation script in /hack to 1.23+ and I have to merge this after the 1.9 release this week.

**Comment by biswajit-9776** [comment]
I have taken a look at the scripts in /hack and the script doesn't touch the istio-install/patches in any way and copies all its content to newer istio versions. If we face any issue, I would take a look at it right away or run a pre-upgrade from the script anytime.

**Comment by juliusvonkohout** [comment]
/hold

i think we are missing istio-cni

**Pull request merged**
