### PR TITLE
Updating seldon core to v1.17.1

### PR DESCRIPTION
**Pull request by SachinVarghese**
**Description of your changes:**
Updating seldon core to v1.17.1

**Checklist:**
- [x] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
Hello, you have to sign the CLA. I really like that people keep seldon up to date.

**Comment by SachinVarghese** [comment]
> Hello, you have to sign the CLA. I really like that people keep seldon up to date.

Thank you, I have signed the CLA, the PR should be ready for review now.

**Comment by juliusvonkohout** [comment]
> > Hello, you have to sign the CLA. I really like that people keep seldon up to date.
> 
> Thank you, I have signed the CLA, the PR should be ready for review now. Is it likely that this PR can make it to the next release (1.8)?

@annajung @kimwnasptd @DnPlas do we want to Backport this to 1.8?

@SachinVarghese is it not enough to have it in the master branch and in 1.9? Is it needed for Kubernetes 1.26?

**Comment by juliusvonkohout** [comment]
@axsaucedo
@adriangonz
@cliveseldon
@ryandawsonuk

Since you are the owners of seldon here, are you still all dedicated to maintaining it?

**Comment by adriangonz** [comment]
Hey @juliusvonkohout ,

@ryandawsonuk and @axsaucedo no longer work with Seldon. However, @cliveseldon and myself are still dedicated to it (as well as others within the team, like @SachinVarghese).

**Comment by juliusvonkohout** [comment]
> Hey @juliusvonkohout ,
> 
> @ryandawsonuk and @axsaucedo no longer work with Seldon. However, @cliveseldon and myself are still dedicated to it (as well as others within the team, like @SachinVarghese).

Then lets remove these two in the PR as well and add @SachinVarghese to the owners

**Comment by juliusvonkohout** [comment]
/lgtm
@adriangonz do you see anything missing? otherwise i recommend to approve it. with '/approve'

**Comment by DnPlas** [comment]
> > > > Hello, you have to sign the CLA. I really like that people keep seldon up to date.
> > > 
> > > 
> > > Thank you, I have signed the CLA, the PR should be ready for review now. Is it likely that this PR can make it to the next release (1.8)?
> > 
> > 
> > @annajung @kimwnasptd @DnPlas do we want to Backport this to 1.8?
> > @SachinVarghese is it not enough to have it in the master branch and in 1.9? Is it needed for Kubernetes 1.26?
> 
> The previous version of Seldon Core was 1.15.0, which doesn't run on Kubernetes 1.26. So it would be good to have it in the 1.8 release if possible. If not, we can have it in the master for the next release.

hi there, yes we have to backport this change also to 1.8, once we merge this PR.

**Comment by juliusvonkohout** [comment]
@SachinVarghese @adriangonz @ukclivecox can you upgrade Sheldon to 1.18.x? We want to support Kubernetes 1.27-1.29 in Kubeflow 1.9

**Comment by adriangonz** [comment]
Hey @juliusvonkohout ,

None of the previous maintainers mentioned above work for Seldon anymore (nor work on the Seldon Core project). 

For next steps on this one, it would be best to check with either @ramonpzg or @ahousley.

**Comment by ramonpzg** [comment]
Hi @juliusvonkohout -- `>v1.18` is now compatible with k8s 1.27 :)

We are keeping track of it here https://docs.seldon.io/projects/seldon-core/en/latest/workflow/install.html

**Comment by juliusvonkohout** [comment]
> Hi @juliusvonkohout -- `>v1.18` is now compatible with k8s 1.27 :)
> 
> We are keeping track of it here https://docs.seldon.io/projects/seldon-core/en/latest/workflow/install.html

can you create a PR then to update? We also need to update the owners file.

**Pull request merged**
