### PR TITLE
knative shouldn't be part of GCP stack kustomization

### PR DESCRIPTION
**Pull request by jlewi**
* related to kubeflow/gcp-blueprints#74

* knative needs to be installed in its own namespace so we don't want
  to make it part of the kubeflow namespace kustomization package

* We will have to install it separately in the blueprint.

### CODE REVIEW

**Comment by jlewi** [comment]
/approve

@Bobgy Please try to do "/approve" in addition to lgtm so that PRs can be merged if you have approval rights.

**Comment by Bobgy** [comment]
I see, will do so next time.

**Pull request merged**
