### PR TITLE
fix jupyter-web-app image tag (#1686)

### PR DESCRIPTION
**Pull request by thesuperzapper**
(cherry picked from commit 9f52c781a95adf08c55377689642921da67fc94f)

### CODE REVIEW

**Comment by thesuperzapper** [comment]
This is a cherry-pick for the Kubeflow 1.2 `jupyter-web-app` image fix PR: https://github.com/kubeflow/manifests/pull/1686

Same as before, (because Azure and IBM hard code the image), I need you to `/approve` this: @berndverst, @adrian555

**Review by adrian555 — APPROVED** [review]

**Comment by thesuperzapper** [comment]
@berndverst still need Azure to `/approve ` it

**Comment by thesuperzapper** [comment]
I also need someone to `/lgtm` this. Can one of @Jeffwan @berndverst do that?

**Pull request merged**
