### PR TITLE
Remove copyright headers

### LINKED ISSUE #2411: Arrikto copyrights to files
There are arrikto copyright headers retaining all rights on the following files in the istio kustomization folders:

[istio-namespace](https://github.com/kubeflow/manifests/blob/08228090334c0a0d32e8945d0aa4dc356d95bc74/common/istio-1-16/istio-namespace/base/kustomization.yaml)

[cluster-local-gateway](https://github.com/kubeflow/manifests/blob/08228090334c0a0d32e8945d0aa4dc356d95bc74/common/istio-1-16/cluster-local-gateway/base/kustomization.yaml)

Is this intentional? Is it meant to convey a different license for these files as opposed to the overall license [here](https://github.com/kubeflow/manifests/blob/08228090334c0a0d32e8945d0aa4dc356d95bc74/LICENSE)?

### PR DESCRIPTION
**Pull request by imiller445**
**Which issue is resolved by this Pull Request:**
Resolves #2411

**Description of your changes:**
Remove copyright headers

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by annajung** [comment]
Great catch, thanks for cleaning this up!

/lgtm

**Comment by imiller445** [comment]
Thanks Anna!

/assign @patrickxys

**Comment by imiller445** [comment]
Hey @PatrickXYS, just a bump to make sure you saw this PR. Thanks!

**Comment by annajung** [comment]
cc @kimwnasptd for review

**Comment by imiller445** [comment]
Just bumping this PR to see if someone can approve and help get it closed out.

**Comment by juliusvonkohout** [comment]
Ill put this on the agenda for the next manifests wg meeting

**Comment by juliusvonkohout** [comment]
@imiller445 Please fix the merge conflict.

**Comment by kromanow94** [comment]
The changes described in this PR were taken over by https://github.com/kubeflow/manifests/pull/2581.

**Pull request closed without merging**
