### PR TITLE
cherry-pick k8s_istio.v1.1.0 KFDef (#1515)

### PR DESCRIPTION
**Pull request by swiftdiaries**
* Add missing files for k8s_istio.v1.1.0 KFDef

* Also removed tensorboard from the KFDef

* Generate tests

**Which issue is resolved by this Pull Request:**
Resolves https://github.com/kubeflow/kubeflow/issues/5246

**Description of your changes:**

**Checklist:**
- [ ] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by crosvera** [comment]
@swiftdiaries I tested your changes and I could successfully deploy kubeflow. I had to edit the `repos` section to point to your repo cause the changes are only there.

**Comment by swiftdiaries** [comment]
Thanks @crosvera ! I'm hoping to get this merged soon so you can use the config as-is

**Comment by crosvera** [comment]
yeah @swiftdiaries, but I still got the same problem that I mention here https://github.com/kubeflow/kubeflow/issues/5246
best regards

**Review by krishnadurai — APPROVED** [review]

**Comment by swiftdiaries** [comment]
/approve
Approving this myself because this pertains to the `kfctl_k8s_istio` config

**Pull request merged**
