### PR TITLE
Add AWS Kustomize manifests (#221)

### PR DESCRIPTION
**Pull request by Jeffwan**
This is a cherry-pick of #221 

**Which issue is resolved by this Pull Request:**
Resolves https://github.com/kubeflow/kubeflow/issues/4057

**Description of your changes:**
Once we use 0.6 tags in kubeflow configs, notice aws components are not in 0.6-branch. Need to cherry-pick entire aws folder. 

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/360)

### CODE REVIEW

**Comment by axelborja** [comment]
@Jeffwan Thanks for this one.

Because we are unable to install any v0.6 version without this fix.

**Comment by Jeffwan** [comment]
@kkasravi @richardsliu Could you help check PR?

**Comment by kkasravi** [comment]
/lgtm

@Jeffwan make sure you've rebased from v0.6-branch 
(git rebase -i upstream/v0.6-branch) - so you've pulled in those changes.
May not be strictly necessary since these are new.

**Comment by Jeffwan** [comment]
em.. it's a little bit weird. I create branch on top of 0.6-branch and it should have all latest changes.  Not sure it's related to https://github.com/kubeflow/kfctl/pull/38

INFO|2019-09-24T18:21:13|/src/kubeflow/testing/py/kubeflow/testing/argo_client.py|31| Workflow kubeflow-manifests-presubmit-kfctl-go-360-b655e03-5874-3221 in namespace kubeflow-test-infra; phase=Failed

**Comment by kevincasadodsc** [comment]
Any update on this? There were some changes made to the master branch that are no longer backwards compatible with 0.6.2 version of kfctl. Namely this one: https://github.com/kubeflow/manifests/pull/342. Now to deploy on eks I was forced to use a specific commit for the manifests.

**Comment by Jeffwan** [comment]
@kevincasadodsc I will try to grab someone to check errors here. This change should not be related. Hope we can merge it by this week.

**Comment by Jeffwan** [comment]
from the logs, I see 

```
il.py                     71 INFO     time="2019-10-04T00:51:05Z" level=warning msg="Backfilling auth; this is deprecated; Auth should be explicitly set in Gcp pl
ugin" filename="gcp/gcp.go:1733"
util.py                     71 INFO     time="2019-10-04T00:51:05Z" level=info msg="Adding plugin gcp" filename="v1alpha1/application_types.go:571"
util.py                     71 INFO     Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: coordinator Generate failed for gcp:  (kubeflow.er
ror): Code 400 with message: could not generate deployment manager configs under gcp_config Error:  (kubeflow.error): Code 400 with message: could not copy /mnt/tes
t-data-volume/kubeflow-manifests-presubmit-kfctl-go-360-b655e03-6784-f89c/kfctl-f89c/.cache/kubeflow/kubeflow-kubeflow-6ddf28c/deployment/gke/deployment_manager_con
figs/cluster.jinja to /mnt/test-data-volume/kubeflow-manifests-presubmit-kfctl-go-360-b655e03-6784-f89c/kfctl-f89c/gcp_config/cluster.jinja Error cannot create dire
ctory: open /mnt/test-data-volume/kubeflow-manifests-presubmit-kfctl-go-360-b655e03-6784-f89c/kfctl-f89c/.cache/kubeflow/kubeflow-kubeflow-6ddf28c/deployment/gke/de
ployment_manager_configs/cluster.jinja: no such file or directory
util.py                     71 INFO     Usage:

```

I think it's related to the change we delete deployment folder from kubeflow.  @jlewi  Not sure why the [test](http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-manifests-presubmit-kfctl-go-360-b655e03-6784-f89c?tab=workflow&nodeId=kubeflow-manifests-presubmit-kfctl-go-360-b655e03-6784-f89c-1153914034) use master branch? this should only test 0.6-branch as I think.

**Comment by axelborja** [comment]
Un fortunately without this one, we could not deploy kubeflow on AWS. so, this PR should be of the highest priority.

**Comment by JohannesTK** [comment]
+1 with @axelborja

**Comment by karlschriek** [comment]
Any update on this? We are currently unable to deploy on AWS. Workarounds using 0.6.1 keep causes other problems

**Comment by JohannesTK** [comment]
@Jeffwan, @kkasravi & @richardsliu - any updates?

**Comment by Jeffwan** [comment]
Sorry guys, I am kinda overwhelmed with other stuff recently and I will either 
1. give workaround on 0.6.2
2. give 0.7 setups.
3. Fix this issue with community folks 

@JohannesTK  @axelborja @karlschriek

**Comment by Jeffwan** [comment]
Hi folks, please check workaround here. https://github.com/kubeflow/kubeflow/issues/4199#issuecomment-544762443

I also ask @jlewi to help check

**Comment by jlewi** [comment]
Here are the logs from the failed tests.
[Uploading kubeflow-manifests-presubmit-kfctl-go-360-b655e03-4224-4fb9-4066529238.log.txt…]()

```
2019-10-08T22:10:24.354615121Z  main            util.py                     71 INFO     couldn't generate KfApp:  (kubeflow.error): Code 500 with message: coordinator Generate failed for gcp:  (kubeflow.error): Code 400 with message: could not generate deployment manager configs under gcp_config Error:  (kubeflow.error): Code 400 with message: could not copy /mnt/test-data-volume/kubeflow-manifests-presubmit-kfctl-go-360-b655e03-4224-4fb9/kfctl-4fb9/.cache/kubeflow/kubeflow-kubeflow-ca7d46a/deployment/gke/deployment_manager_configs/cluster.jinja to /mnt/test-data-volume/kubeflow-manifests-presubmit-kfctl-go-360-b655e03-4224-4fb9/kfctl-4fb9/gcp_config/cluster.jinja Error cannot create directory: open /mnt/test-data-volume/kubeflow-manifests-presubmit-kfctl-go-360-b655e03-4224-4fb9/kfctl-4fb9/.cache/kubeflow/kubeflow-kubeflow-ca7d46a/deployment/gke/deployment_manager_configs/cluster.jinja: no such file or directory
```

It looks like the issue is that the test isn't trying to use the v0.6-branch but is instead pulling from master on which the GKE DM configs have been removed.

**Comment by jlewi** [comment]
Since the only files modified are in aws/ directory and we don't have any AWS e2e tests its fine to ignore them.

The unittests passed.

Merging manually.

**Comment by Jeffwan** [comment]
Thank a lot Jeremy!

**Comment by axelborja** [comment]
Thanks a lot @Jeffwan && @jlewi  !!

**Pull request merged**
