### PR TITLE
Migrate kustomize version from 2.x version to 3.x.

### PR DESCRIPTION
**Pull request by jbrette**
**Which issue is resolved by this Pull Request:**
Resolves #
- [upgrade manifests to work with kustomize-v3.0.1 #372](https://github.com/kubeflow/manifests/issues/372)
- Needed for [update test-worker to use kustomize-v3.0.1 #465 ](https://github.com/kubeflow/testing/issues/465)

**Description of your changes:**
- **The changes is supposed to be pretty safe because it does not touch the manifests themselves. It only changes the go code used to test the manifests.**

- Updated go.mod to user kustomize 3
- Update gen-test-target.sh
- Updated kusttarget.go to use kustomize 3

The following changes have been added but reverted to preserve backward compatibility (they will be part of a subsequent PR)
- Replace bases: by resources: and collapsed sections if necessary
- Fixed ambassador patch namespace.

**Checklist:**
- [X] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/309)

### CODE REVIEW

**Comment by jbrette** [comment]
@googlebot I signed it!

**Comment by jlewi** [comment]
Is there an issue tracking upgrading from 2.x to 3.x?

Won't this break people who are using kustomize 2.x?

/assign @kkasravi

**Comment by kkasravi** [comment]
@jbrette this is awesome. It will need to be paired with changes to [kustomize.go](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/pkg/kfapp/kustomize/kustomize.go) which will generate a kustomization.yaml file with more than one overlay mixed in.
You have an [example](https://github.com/keleustes/kustomize/tree/allinone/examples/mixin).
My solution for kustomize-v2.0.3 was to generate a kustomization.yaml that included the base and overlays were 'hoisted' into this file. Based on your [comment](https://github.com/kubernetes-sigs/kustomize/issues/1251#issuecomment-508887971) do you know if the PR you mention addresses PatchesStrategicMerge for CRD's? CRD's would need to be registered in go's type system and have patch strategy annotations like [this](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/types.go#L35)

**Comment by jbrette** [comment]
@kkasravi Have look at that [PR](https://github.com/kubeflow/kubeflow/pull/4055). 

- It is not really leveraging the new kustomize features yet.
- It is compiling with the new version of the kustomize v3 pkg.
- bases: is supposed to be deprecated. Still need to complete the merge the handling of the bases: and resources: field.

**Comment by kkasravi** [comment]
@jbrette both look pretty comprehensive and complete.

I have e2e running on tektoncd, i'll test out your changes

**Comment by jbrette** [comment]
@kkasravi @jlewi Genttle bump now that kubeflow itself has been updated. This PR does not change the manifest, only the go code automatically generated to test the manifests.

**Comment by kkasravi** [comment]
@jbrette thank you!
/lgtm
/approve

**Pull request merged**
