### PR TITLE
[WIP] Create new Openshift stack for Operator enabled Kubeflow

### PR DESCRIPTION
**Pull request by tumido**
**Which issue is resolved by this Pull Request:**
Loosely connected to: https://github.com/kubeflow/manifests/issues/1867
Resolves: https://issues.redhat.com/browse/ODH-373

**Description of your changes:**
Creates a brand new stack for Openshift that uses operators instead of bundled, hardcoded thirdparty apps.

Uses operated and managed solutions for:
- Istio (via Openshift Service Mesh)
- Cert manager (via Jetstack Cert Manager)
- Tekton Pipelines (via Openshift Pipelines)
- Knative (via Openshift Serverless)

Known issues to be solved:
- Addmission webhook doesn't work
- metadata-envoy-deployment is crashing for Service mesh related issues

Most apps are not fully tested yet

Apps remaining to port
- Kubeflow Pipelines via Argo

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
I have a rootless kubeflow 1.3 running using istio-cni and some special SCCs etc. . Are you interested in a collaboration?

**Comment by tumido** [comment]
Hey, sorry @juliusvonkohout, first of all sorry for the delays on this PR. I didn't have time much time lately for this. I'm back again on this this week however.

Sure I'd be interested in any kind of collaboration! :) Do you have any links or pointers to your work? I can grant you access to my fork so we can collaborate on this PR branch directly if you want to. :slightly_smiling_face:

**Review by juliusvonkohout — CHANGES_REQUESTED** [review]
1. Is there a reason that you are using  kfp-tekton? It still has some serious bugs (https://github.com/kubeflow/kfp-tekton/issues/461) and the normal kfp will be rootless soon https://github.com/kubeflow/pipelines/issues/5718

2. Did you really test, that it works with the servicemesh, that is based on istio 1.6 instead of 1.9 ?

3. Your SCC is incredibly dangerous. Never ever do such root things... In my accepted pull requests (https://github.com/kubeflow/manifests/pull/1756) i fixed most of the root issues. Just the pipeline cache is remaining. But you should fix or disable the pipeline cache instead of creating such a security risk.

```
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: kubeflow-istio-cni-scc

priority: 1 # to overwrite the default restricted scc
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
readOnlyRootFilesystem: false
allowedCapabilities: null
defaultAddCapabilities: null
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  #type: MustRunAsNonRoot
  type: MustRunAsRange
  uidRangeMin: 1000
  uidRangeMax: 65535
fsGroup: 
  type: MustRunAs # otherwise openshift PVC mounts are not working properly
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: MustRunAs
volumes:
- configMap
- emptyDir
- projected
- secret
- downwardAPI
- persistentVolumeClaim
allowHostDirVolumePlugin: false
allowPrivilegedContainer: false
allowPrivilegeEscalation: false

groups: []
# These groups are needed for pure kubernetes, not openshift with redhat servicemesh etc.
#- system:serviceaccounts:cert-manager
#- system:serviceaccounts:knative-serving
#- system:serviceaccounts:knative-eventing
#- system:serviceaccounts:auth
#- system:serviceaccounts:istio-system
#- system:serviceaccounts:kubeflow
users: []
```

To get default-viewer and default-editor access to the SCC
```
cat <<EOF | kubectl apply -f -
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-view: "true"
  name: kubeflow-psp-scc
rules:
- apiGroups:
  - security.openshift.io 
  resourceNames:
  - kubeflow-istio-cni-scc
  resources:
  - securitycontextconstraints 
  verbs: 
  - use
EOF
```

**Comment by tumido** [comment]
The base premise of this PR is to abstract away from Kubeflow as much of the deployment overlap with OLM operators as possible.

A bit of background first: One of our base needs is that we need Kubeflow to be able run on multitenant clusters where Kubeflow is not the only workload. Hence we try to use the centralized solutions available on the platform. That is kinda the "why" we decided on several aspects of this:

- We prefer KFP Tekton over Argo because we can leverage Openshift Pipelines that is OCP native
- Istio in Service Mesh seems to be working so far for me, if I remember correctly anything above 1.6 should be fine for Kubeflow right now http://github.com/kubeflow/kubeflow/issues/5313

Ad 3. My SCC is just a copy paste from [`distributions/stacks/openshift/application/openshift/openshift-scc`](https://github.com/kubeflow/manifests/tree/master/distributions/stacks/openshift/application/openshift/openshift-scc) where I've only tried to limit number of SCCs and the `users` to bare minimum so far. My intention with that was to get rid of the whole SCCs in the end if possible, or leave in here the minimal permission escalation. As you can see, my SCC is targeting kubeflow itself and not `kubeflow-admin/edit/view`, my SCC is never granted to anybody outside the list of the SAs.

By your SCC, I'm guessing that you suggest that there's no SCC needed for Kubeflow itself in a certain configuration, is that correct? Can you point me to a repo/branch where you're deploying this configuration from?

**Comment by juliusvonkohout** [comment]
For 1.3 there is no scc needed except for
 
1. If you use upstream istio 1.9.x with the default sidecars that require user 1337. Service-mesh most likely does not need a fixed user. Those sidecars are also in the user namespaces.


2. To run jupyterlab notebooks user 1000 must be allowed.

So even if you properly fix the pipeline cache root issues you still need my scc in the user namespaces to run jupyterlab notebooks.

"my SCC is never granted to anybody outside the list of the SAs." That is still unnecessary and dangerous.

So the proper way going forward is disabling or fixing the pipeline cache and using the SCCs provided by me.

**Comment by juliusvonkohout** [comment]
I will try to fix the cache-deployer.
```
+ echo 'Start deploying cache service to existing cluster:'
+ NAMESPACE=kubeflow
+ MUTATING_WEBHOOK_CONFIGURATION_NAME=cache-webhook-kubeflowStart deploying cache service to existing cluster:

+ WEBHOOK_SECRET_NAME=webhook-server-tls
+ mkdir -p //bin
+ export 'PATH=//bin:/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
+ kubectl version --output json
+ jq --raw-output '(.serverVersion.major + "." + .serverVersion.minor)'
+ tr -d '"+'
+ server_version_major_minor=1.20
+ curl -s https://storage.googleapis.com/kubernetes-release/release/stable-1.20.txt
+ stable_build_version=v1.20.7
+ kubectl_url=https://storage.googleapis.com/kubernetes-release/release/v1.20.7/bin/linux/amd64/kubectl
+ curl -L -o //bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.20.7/bin/linux/amd64/kubectl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file //bin/kubectl: Permission denied
  0 38.3M    0  1367    0     0   7469      0  1:29:45 --:--:--  1:29:45  7469
curl: (23) Failure writing output to destination
+ chmod +x //bin/kubectl
chmod: //bin/kubectl: No such file or directory
+ true
/kfp/cache/deployer/deploy-cache-service.sh: line 47: can't create webhooks.txt: Permission denied
```
It seems that they just set a wrong home directory...

**Comment by lkoenigsberger** [comment]
So it looks like there are multiple people trying to get kubeflow running within Openshift and make use of the native RedHat Operators including ourselfes. Maybe we join forces to get that to speed as i would really love to see that working completely. I also found today a blog article https://www.openshift.com/blog/operationalizing-kubeflow-in-openshift and the corresponding repo https://github.com/raffaelespazzoli/kubeflow-ocp by @raffaelespazzoli

**Comment by tumido** [comment]
@lkoenigsberger yup, I'm aware of @raffaelespazzoli's work, thank you for the pointers! :slightly_smiling_face:

We're more kfdef focused in here, but in general most of his manifests should be transferable. I must admin I didn't have much time on this PR in the last few weeks, so sorry for stalling on this.

**Pull request closed without merging**
