### PR TITLE
Add overlay to support Azure Database for MySQL

### PR DESCRIPTION
**Pull request by yilun-msft**
**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**
Create an Azure metadata overlay to use Azure MySQL and provide a readme.md as the instruction. Detailed instruction would be seen in the Readme.md. This would enable Azure MySQL user to use Azure MySQL as the metadata db.

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by yilun-msft** [comment]
@googlebot I signed it!

**Review by eedorenko — CHANGES_REQUESTED** [review]
I think we need:
 - Copy content of metadata/overlays/azure to stacks/azure/metadata so we keep everything Azure specific in one folder. 
 - Reference stacks/azure/metadata from [kustomization.yaml](https://github.com/kubeflow/manifests/blob/v1.1-branch/stacks/azure/kustomization.yaml). Perhaps optionally (aka uncomment this if you want to use ...)
 - Update installation guide on the Kubeflow website with what you have in Readme.md.

**Comment by yilun-msft** [comment]
> I think we need:
> 
> * Copy content of metadata/overlays/azure to stacks/azure/metadata so we keep everything Azure specific in one folder.
> * Reference stacks/azure/metadata from [kustomization.yaml](https://github.com/kubeflow/manifests/blob/v1.1-branch/stacks/azure/kustomization.yaml). Perhaps optionally (aka uncomment this if you want to use ...)
> * Update installation guide on the Kubeflow website with what you have in Readme.md.

Eugene, do you mean move metadata/overlays/azure to stacks/azure/metadata or copy them? I will go ahead and document them in kubeflow/website

**Comment by eedorenko** [comment]
I mean move.

**Comment by yilun-msft** [comment]
A meta comment on how the validation is done: I created an Azure Database for MySQL: kf-test.mysql.database.azure.com and edit the kustomization to use ./metadata as instructed in the Readme.md. Execute a pipeline and verify the metadata changes in the selected database named "mlmetadata"

**Pull request merged**
