### PR TITLE
Document how to change the default username for dex

### PR DESCRIPTION
**Pull request by biswajit-9776**
# Pull Request Template for Kubeflow manifests Issues

## ✅ Contributor checklist
  - Make sure you have tested with kustomize. See [Installation Prerequisites](https://github.com/kubeflow/manifests#prerequisites)
  - All the commits have been _signed-off_  (To pass the `DCO` check)
  - Submit the [Contributor License Agreements](https://cla.developers.google.com/clas) (To pass the `cla/google` check)

---     
 
> You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### CODE REVIEW

**Comment by biswajit-9776** [comment]
I would be eager to know if this is right approach I could undo this to push a newer commit.

**Comment by juliusvonkohout** [comment]
This is for @diegolovison

**Comment by diegolovison** [comment]
Hi @biswajit-9776 thanks for your contribution.

I would like to know:
* how can we change the username/email once we have KFP deployed?
* is is possible to change when we have KFP deployed?
* Describe the difference between `email` and `username`

I believe your PR is good to merge as is but having all those things clear in a single PR is even better.
If you wish to work on the topics above in other PR just let me know.

**Comment by biswajit-9776** [comment]
This PR is dedicated to default username for dex login as the PR #2777 was for default password.
_email_ is what we fill in when we try to login at the dex dashboard before entering the password.
_username_ is what gets visible in the profile.

**Comment by juliusvonkohout** [comment]
Since it is lgtmed by the documentation lead I
/approve

**Pull request merged**
