### PR TITLE
Add istio sidecar inject false to deployments in kubeflow ns

### PR DESCRIPTION
**Pull request by Bobgy**
**Which issue is resolved by this Pull Request:**
Part of kubeflow/pipelines#1223
Unblocks kubeflow/kfctl#131
**Description of your changes:**
Disabled istio sidecar injection for deployments in kubeflow namespace except for metadata related manifests. There was a problem with auto generated test cases for metadata, discussed in https://github.com/kubeflow/manifests/pull/716 separately.

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

/assign @jlewi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/712)

### CODE REVIEW

**Comment by Bobgy** [comment]
@jlewi Can I get approval on this one? I will address issues in https://github.com/kubeflow/manifests/pull/716 separately.

**Comment by Bobgy** [comment]
Thanks for pointing that out. I will fix that.

**Comment by Bobgy** [comment]
I tried looking at test error message and found this in [link](http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-manifests-presubmit-kfctl-go-iap-712-d5efebe-7440-6f86?tab=workflow&nodeId=kubeflow-manifests-presubmit-kfctl-go-iap-712-d5efebe-7440-6f86-3000414174&sidePanel=logs%3Akubeflow-manifests-presubmit-kfctl-go-iap-712-d5efebe-7440-6f86-3000414174%3Amain)
```
util.py                     72 INFO     failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply c
ould not update deployment manager Error Set New IamPolicy error: googleapi: Error 400: The number of members in the policy (1,505) is larger than the maximum allowed size 1,500., badReq
uest
```
Looks like the test project is reaching quota limit. Can someone help me clean them up?

**Comment by jlewi** [comment]
@Bobgy Can you please open a bug in kubeflow/testing ? And then ping in #buildcop in kubeflow.slack.com?

**Comment by jlewi** [comment]
Looks like we have kubeflow/testing#543

**Comment by jlewi** [comment]
@Bobgy The RC branch for Kubeflow 1.0 has been cut so if you want this to make the cut I would suggest focusing on getting the tests passed and then cherry-picking it into the release branch.

It looks like the test_katib is ready test failed and the test_kf_is_ready test failed

The latter error 

```
E     kubeflow.testing.util.TimeoutError: Timeout waiting for deployment cloud-endpoints-controller in namespace kubeflow
```

Looks like it might be related to kubeflow/kubeflow#4693 which should be fixed on master. 
So you might want to rebase and try again.

/test all

**Comment by Bobgy** [comment]
/test kubeflow-manifests-presubmit
Each test seems to fail on a different case, seems flaky.

**Comment by jlewi** [comment]
Most recent failure was the pytorch job failed to run.

I don't see why adding an annotation to the statefulset would affect that. So I'll go ahead and merge manually.

**Comment by Bobgy** [comment]
Thanks, @jlewi!

**Pull request merged**
