### PR TITLE
Upgrade istio to v1.21.3

### PR DESCRIPTION
**Pull request by biswajit-9776**
# Pull Request Template for Kubeflow manifests Issues

- Please include a summary of changes and the related issue. 
- List any dependencies that are required for this change. 
- Please delete the options that are not relevant.
- The following checklist will help you to satisfy the requirements.

  
## ✅ Unit Test Checklist
  
  - [ ] 🛠️ Make sure you have installed kustomize == 5.2.1+     
  - [ ] ✍️ Have you written new tests for your core changes, as applicable?      
  - [ ] 🔄 Have you successfully run existing tests with your changes ?    
  - [ ] 🚀 Have you successfully run existing and new tests with your changes ?

## ✅ Contributor checklist
  - [ ] All the commits have been _signed-off_  (To pass the `DCO` check)
  - [ ] Submit the [Contributor License Agreements](https://cla.developers.google.com/clas) (To pass the `cla/google` check)

---     
 
>You can join our slack channel **wg-manifests** [here](https://www.kubeflow.org/docs/about/community/). This link also contains our meeting schedule.

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
Please use this PR to finish your scripts. I want to use them myself for istio 1.22.

**Comment by biswajit-9776** [comment]
The scripts are ready to be used.
For now I haven't simplified their order of execution, so to upgrade istio, you would have to do the following:
1. Have a kind cluster running which you can accomplish by running following command from manifests source directory.
```shell
kind create cluster --config tests/gh-actions/kind-cluster.yaml
``` 
2. You first need to run sync-istio-manifests.sh first. It might ask for your sudo password in between and then just push the branch for a PR.
3. After you have pushed the PR, you can now run the sync-istio-cni-manifests.sh.
4. Push the branch again and it's done.

**Comment by biswajit-9776** [comment]
Sorry the script had a comment missing

**Comment by juliusvonkohout** [comment]
> The scripts are ready to be used after this PR is merged.
> For now I haven't simplified their order of execution; so to upgrade istio, you would have to do the following:
> 1. Have a kind cluster running which you can accomplish by running following command from manifests source directory.
> ```shell
> kind create cluster --config tests/gh-actions/kind-cluster.yaml
> ``` 
> 2. You would need to run _sync-istio-manifests.sh_ first. It might ask for your sudo password in between and then just push the branch for a PR.
> 3. After you have pushed the PR, you can now run the _sync-istio-cni-manifests.sh_.
> 4. Push the branch again and it's done.

Please get rid of sudo and Kind. We just want to synchronize the manifests as we do in the other scripts e.g. sync-kserve.

**Comment by juliusvonkohout** [comment]
/approve
since @rimolive reviewed it. Ill try to update to istio 1.22 with the scripts next week.
@rimolive you can upgrade to 1.22 as well if you have time.

**Comment by biswajit-9776** [comment]
@rimolive Do let me know if the scripts fail in any way.

**Pull request merged**
