### PR TITLE
v1.1 manifests for vanilla k8s

### PR DESCRIPTION
**Pull request by swiftdiaries**
**Which issue is resolved by this Pull Request:**
Resolves
https://github.com/kubeflow/website/issues/1984

**Description of your changes:**
Added v1.1 for vanilla k8s KFDef

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by PatrickXYS** [comment]
It would be great if we can adopt multi-tenancy KFP and V3 manifests solution into vanilla K8s manifests.

But I'm okay if we don't have enough capacity.

**Comment by swiftdiaries** [comment]
Hey @PatrickXYS 
Thanks for the review. Let me take a look at it and if I can't get a commit in by tomorrow, we can probably go ahead and merge it

**Comment by HassanOuda** [comment]
Hey @swiftdiaries , were you able to ad in multitenancy KFP into these vanilla k8s v1.1 manifests?

**Comment by swiftdiaries** [comment]
Hey @HassanOuda 
I'm looking to add the single-user KFDef and the related v3 kustomize stack first.
@krishnadurai will look to add the multi-user KFP and the related is too-Sec KFDef and the v3 stack before Tuesday

**Comment by HassanOuda** [comment]
Perfect, thanks a lot @swiftdiaries

**Comment by swiftdiaries** [comment]
Hey @PatrickXYS 
Could you please take another pass? I've scoped it down to single user KF

**Comment by PatrickXYS** [comment]
/lgtm 

@swiftdiaries Thanks for contribution!

**Comment by PatrickXYS** [comment]
@swiftdiaries Can you /approve rather than approve from UI. The approve tag is missing thus can't automatic merge.

**Comment by sakaia** [comment]
This manifest does not include seldon-core. Is this intentionally?

**Comment by swiftdiaries** [comment]
Totally wasn't intentional. It's a standalone installation that works well independently. Instructions: https://github.com/kubeflow/manifests/tree/master/seldon#install-seldon-operator

**Pull request merged**
