### PR TITLE
add permissions for kubectl top pods

### PR DESCRIPTION
**Pull request by munagekar**
**Description of your changes:**

This allows the usage of kubectl top pods. 

This is useful when setting resource requests when using kubeflow/pipelines. I think this will be useful to most users of kubeflow.

**Checklist:**
- [ ] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by PatrickXYS** [comment]
@munagekar 

For the kubeflow role, we want to keep minimum permission at first, can you explain what functionality will be effected without this permission?

Or it would be better to give a usage-list.

**Comment by munagekar** [comment]
@PatrickXYS 

Thank you for the review. 

This allows contributors to use the `kubectl top pods` command. This shows the cpu usage and memory usage, if metric-server is installed on kubernetes server. So users will be able to check the Jupyter Notebook and Kubeflow Pipelines Pod Usage and set the resource requirement and limit.

If this does not align with current design, feel free to close this PR.

**Comment by PatrickXYS** [comment]
@munagekar I understand your point, but why metrics-server has to use Kubeflow-Role?

Can you create your own k8s role and your metrics server use it?

**Comment by munagekar** [comment]
Thank you for your reply, I understand the design philosophy. I will close this PR

**Pull request closed without merging**
