### PR TITLE
Add containerRuntimeExecutor field for other argo executors

### PR DESCRIPTION
**Pull request by Tomcli**
**Description of your changes:**
By default, Argo will use the `docker` containerRuntimeExecutor which it will not work on Kubernetes Cluster that doesn't use docker runtime. Therefore, we want to add the containerRuntimeExecutor field so that users who need different executor runtime can easily change the containerRuntimeExecutor params using kustomize. 

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

cc: @animeshsingh

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/259)

### CODE REVIEW

**Comment by Tomcli** [comment]
Thanks @richardsliu, I updated the Argo tests and now the all the presubmit tests are passed.

**Comment by swiftdiaries** [comment]
@Tomcli 
I didn't see this PR and I added this https://github.com/kubeflow/manifests/pull/266 to do the same via an overlay.
I think it'll be better to have an overlay so that a kfctl config can reference the overlay to install. I'm not sure how var substitution works otherwise at runtime from kfctl.
Do you think it makes sense to pull in those changes here? What are your thoughts?

**Comment by swiftdiaries** [comment]
I used a config like this to init `kfctl` on the overlay
```
apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  name: kubeflow_app
  namespace: kubeflow
spec:
  repos:
  - name: manifests
    root: manifests-master
    uri: https://github.com/swiftdiaries/manifests/archive/containerd-cri-argo.tar.gz
  - name: kubeflow
    root: kubeflow-master
    uri: https://github.com/kubeflow/kubeflow/archive/master.tar.gz
...
```
And the containerd overlay for the argo application:
```
...
applications:
  - kustomizeConfig:
      overlays:
      - containerd
      repoRef:
        name: manifests
        path: argo
    name: argo
...
```

**Comment by Tomcli** [comment]
Thanks @swiftdiaries, I agree having a containerd overlay is better to apply the changes via kfctl. My intent for this PR is to add the containerRuntimeExecutor variable to the base argo configmap so that other users can build their own custom overlays with the containerRuntimeExecutor variable as well.

**Comment by swiftdiaries** [comment]
Oh cool, thanks for the clarification ! I can file a PR with the overlay in #266 after this one goes in.

**Comment by Tomcli** [comment]
cc @animeshsingh

**Comment by animeshsingh** [comment]
@kkasravi can we get this in? Its gating another PR, and is important for us at IBM to get Argo running with containerd

**Comment by swiftdiaries** [comment]
I'll wait for the other reviewers as well but from my side this /lgtm

**Comment by kkasravi** [comment]
@Tomcli will you update the config files to include this value
eg [kfctl_gcp_iap.yaml](https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/kfctl_gcp_iap.yaml)

```
  - kustomizeConfig:
      overlays:
      - istio
      parameters:
      - name: containerRuntimeExecutor
        value: docker
      repoRef:
        name: manifests
        path: argo
    name: argo
```

**Comment by kkasravi** [comment]
other than the question about updating the config files which is in a different repository (kubeflow)
/lgtm

**Comment by Tomcli** [comment]
Thanks @kkasravi for the review. I submitted a [PR to kubeflow](https://github.com/kubeflow/kubeflow/pull/3929) to update the corresponding config files.

**Pull request merged**
