### PR TITLE
Add AWS 1.3 distribution

### PR DESCRIPTION
**Pull request by PatrickXYS**
**Which issue is resolved by this Pull Request:**
Helps #1798

**Description of your changes:**
AWS-EKS manifest for kubeflow 1.3

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by karlschriek** [comment]
@kubeflow/aws I have a few questions about this release. When we deploy to AWS we offload as much as possible to managed AWS services as we possibly can, meaning in particular:

1. Using Cognito for user pool management
2. Using RDS for all metadata storage (pipelines, metadb, cachedb, katibdb) instead of an on-cluster MySQL db
3. Using S3 for all pipeline artifact storage instead of using Minio for on-cluster storage
4. Using Secret Manager in combination with https://github.com/external-secrets/kubernetes-external-secrets in order to manage secrets (for example RDS database credentials)
5. Using IRSA as far as possible

From what I can tell, this distribution aims to roll out on EKS but does not attempt to integrate with any further AWS services. Is that the intention?

**Comment by soleares** [comment]
I thought that one of the goals in 1.3 was to move away from kfdef and use straight kustomize. See: https://github.com/kubeflow/manifests/issues/1062. Is kfdef going to continue to be used for distributions like this?

**Comment by karlschriek** [comment]
> I thought that one of the goals in 1.3 was to move away from kfdef and use straight kustomize. See: #1062. Is kfdef going to continue to be used for distributions?

As far as I know the idea is to make the manifests independent of kfdef/kfctl and to cut the distributions loose to do what they want. Eventually the "distributions" folder in the manifests should disappear as well.

Whether kfdef/kfctl continues to exist I guess will depend on whether distributions continue to adopt them. I personally would prefer the AWS distro to be pure kustomize. We would then wrap that within ArgoCD as Gitops operator. With kfdef/kfctl inbetween that is a bit difficult.

**Comment by DavidSpek** [comment]
@karlschriek I have plans to add an AWS (and other vendors) version(s) of my Argo CD distribution that add the integrations to the manifests. If this is also the route you or other cloud vendors want to take please message me on Slack so we can try and coordinate this effort.

**Comment by PatrickXYS** [comment]
> @kubeflow/aws I have a few questions about this release. When we deploy to AWS we offload as much to managed AWS services as we possibly can, meaning in particular:
> 
> 1. Using Cognito for user pool management
> 2. Using RDS for all metadata storage (pipelines, metadb, cachedb, katibdb) instead of an on-cluster MySQL db
> 3. Using S3 for all pipeline artifact storage instead of using Minio for on-cluster storage
> 4. Using Secret Manager in combination with https://github.com/external-secrets/kubernetes-external-secrets in order to manage secrets (for example RDS database credentials)
> 5. Using IRSA as far as possible
> 
> From what I can tell, this distribution aims to roll out on EKS but does not attempt to integrate with any further AWS services. Is that the intention?
> 
> In the past (in particular with respect to Pipelines and KFServing) we've also had to do quite a bit of hacking to get the authentication via Cognito to work for users.

Hi @karlschriek can you create an issue in the https://github.com/aws/containers-roadmap/issues, and it will attract PM and Managers, and we could also look into how many customers are interested in this.

Thanks!

**Comment by karlschriek** [comment]
Hi @PatrickXYS, sure I can do that. With respect to the current release you are working on, can you confirm if you plan to still and a kfdef with Cognito as was the case in previous releases?

We are also already looking at it and it is not yet evident how to make Cognito work with Istio 1.9.

**Comment by PatrickXYS** [comment]
@karlschriek Our intial plan is to adopt community's manifest at this stage.

After 1.3 formal release, we'll explore the functionality of authenticating Cognito with istio 1.9

**Comment by DavidSpek** [comment]
@PatrickXYS I’m working together with @karlschriek and @matty1979 to try and get Cognito integrated with the Argo CD deployment (which is also just using the upstream manifests). Would you or somebody else from AWS be interested in working together on this?

**Comment by PatrickXYS** [comment]
@DavidSpek This is not related to current PR right? Can we create another PR to keep track?

**Comment by yanniszark** [comment]
/lgtm
/hold
@PatrickXYS please remove the hold when convenient for you!

**Comment by soleares** [comment]
Hi @PatrickXYS it looks like the following from `kfctl_aws.v1.2.0.yaml` are not included in this manifest

- aws-alb-ingress-controller
- nvidia-device-plugin
- istio-ingress
- aws-istio-authz-adaptor

Do you to know if they're compatible with the 1.3 release? I'd like to spin up a 1.3 cluster on EKS but it's probably not worth it yet if I can't use the ingress controller and GPU nodes.

**Comment by DavidSpek** [comment]
@soleares The alb ingress controller is replaced by the [loadbalancer controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller).
As an alternative to the Nvidia device plug-in I can recommend the [NVIDIA GPU operator](https://github.com/NVIDIA/gpu-operator) as this also allows for Prometheus monitoring of GPUs. 
The AWS Istio authz adaptor is not compatible with newer versions of Istio so that is why it isn’t included. 

If you are wanting a deployment that is integrated with AWS services such as RDS and S3 and also contains the gpu operator and other features necessary for a production deployment we almost have this finalized with [ArgoFlow](https://github.com/argoflow/argoflow-aws). This uses Argo CD for all the deployments making it easier to maintain you Kubeflow deployment over time and update it’s components. You can ping me on Slack if you need any help setting things up.

**Pull request merged**
