### PR TITLE
Simplify the pull request template

### PR DESCRIPTION
**Pull request by diegolovison**
Unit Test Checklist and Contributor checklist are done automatically
A brief description of the changes is a duplicated of Please include a summary of changes and the related issue.

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
at least 

  - [ ] I have installed kustomize == 5.2.1+
  - [ ] All the commits have been _signed-off_  (To pass the `DCO` check)

shall stay, since this is useful information.

**Review by juliusvonkohout — CHANGES_REQUESTED** [review]
at least 

##  Checklist
  - [ ] I have installed kustomize == 5.2.1+
  - [ ] All the commits have been _signed-off_  (To pass the `DCO` check)

shall stay, since this is useful information for new contributors.

**Comment by diegolovison** [comment]
> I have installed kustomize == 5.2.1+

It is under the test suite's responsibility and also https://github.com/kubeflow/manifests#prerequisites

> All the commits have been signed-off (To pass the DCO check)

Maybe we should instead of having a checking ` [  ] ` change to something like an information?

**Comment by diegolovison** [comment]
I just saw that this PR failed the DCO. <insert a meme here>

**Comment by juliusvonkohout** [comment]
> > I have installed kustomize == 5.2.1+
> 
> It is under the test suite's responsibility and also https://github.com/kubeflow/manifests#prerequisites
> 
> > All the commits have been signed-off (To pass the DCO check)
> 
> Maybe we should instead of having a checking `[ ]` change to something like an information?

Then please link to the main readme

- [x] I have read the[ main readme](https://github.com/kubeflow/manifests#prerequisites)

**Review by juliusvonkohout — APPROVED** [review]

**Pull request merged**
