### PR TITLE
Add finalizers to roles, change argo executor to k8sapi

### PR DESCRIPTION
**Pull request by blublinsky**
**Which issue is resolved by this Pull Request:**
Resolves #
deployment issues on OpenShift
**Description of your changes:**
Add finalizers to roles

**Checklist:**
- [ ] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/276)

### CODE REVIEW

**Comment by blublinsky** [comment]
@googlebot I signed it!

**Comment by richardsliu** [comment]
@blublinsky 
Can you add an explanation for why this is needed?

Also a couple of things:
1. katib-v1alpha2 is going to be deprecated. Changes should be made to https://github.com/kubeflow/manifests/tree/master/katib-v1alpha2.
2. There are other operators like pytorch-job, mpi-job, etc. Should this be added to all of them?

**Comment by blublinsky** [comment]
@richardsliu This changes are necessary for OpenShift/IBM execution, due to their security constraints. As operator is destroying, its using finalizers and need to have access to it.
I added only to the ones I used, but they should be for all of them

**Comment by richardsliu** [comment]
@blublinsky Can you at least update katib-v1alpha2, since katib-v1alpha1 will be deprecated soon (in about a month)?

**Comment by blublinsky** [comment]
This change is my best guess, I did not try it and v2 is significantly different

**Comment by richardsliu** [comment]
Generally lgtm. Can you resolve the conflict and fix the tests?

**Comment by blublinsky** [comment]
Conflicts resolved

**Comment by blublinsky** [comment]
Conflicts resolved

Boris Lublinsky
FDP Architect
boris.lublinsky@lightbend.com
https://www.lightbend.com/

**Comment by blublinsky** [comment]
Looking at the tests and slightly confused. The test that fails is FAIL: TestTfJobOperatorOverlaysIstio (0.05s)
When I am looking at the test output, it looks like tfjobs/finalizers was not picked up

**Comment by richardsliu** [comment]
You need to fix files like these:
https://github.com/kubeflow/manifests/blob/master/tests/tf-job-operator-overlays-istio_test.go

They can be run locally by doing `make test`.

**Comment by blublinsky** [comment]
Thanks Richard

**Comment by blublinsky** [comment]
OK, 
The initial problem is fixed.
The new one is:
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed
for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from seldon-core-operator Error: StatefulSet in
 version "v1" cannot be handled as a StatefulSet: v1.StatefulSet.Spec: v1.StatefulSetSpec.VolumeClaimTemplates: []v1.PersistentVol
umeClaim: decode slice: expect [ or n, but found {, error found in #10 byte of ...|mplates":{"metadata"|..., bigger context ...|bh
ook-server-secret"}}]}},"volumeClaimTemplates":{"metadata":{"labels":{"app.kubernetes.io/component|…


This is definitely not me


Boris Lublinsky
FDP Architect
boris.lublinsky@lightbend.com
https://www.lightbend.com/

**Comment by kkasravi** [comment]
This is a kustomize-2.0.3 bug in StatefulSet, you need to add 

 

  volumeClaimTemplates: [] 

 

at the end. Look at manifests/gcp/iap-ingress/base/stateful-set.yaml for an example

**Comment by blublinsky** [comment]
Its already there

Boris Lublinsky
FDP Architect
boris.lublinsky@lightbend.com
https://www.lightbend.com/

**Comment by blublinsky** [comment]
The fix was in my version of code, the one that failed

Boris Lublinsky
FDP Architect
boris.lublinsky@lightbend.com
https://www.lightbend.com/

**Comment by jlewi** [comment]
/assign @jlewi

@blublinsky sorry this PR is taking so long; do you want to try to update?

The RBAC role changes seem like pretty straightforward changes. I apologize this PR fell through the cracks and is taking so long.

Here's my suggestion to get this PR fixed and merged

* Rebase on master
* Make sure the only changes are modifying cluster roles to add finalizers (I see a couple other changes in the PR)
* Regenerate the tests by running `make generate`

  * Revert any changed tests that aren't related to the manifests that are being modified in this PR.

**Pull request closed without merging**
