### PR TITLE
Add Myself into AWS OWNERS

### PR DESCRIPTION
**Pull request by PatrickXYS**
**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**
To further maintain AWS resources, add PatrickXYS into AWS folders OWNERS

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by Jeffwan** [comment]
@PatrickXYS Let's leave mameshin there and you can add yourself into owner.

**Comment by PatrickXYS** [comment]
@Jeffwan Fixed, btw, can you also look at this kfctl PR? https://github.com/kubeflow/kfctl/pull/408

**Review by Jeffwan — APPROVED** [review]

**Pull request merged**
