### PR TITLE
Delete gcp-credentials-patch.yaml

### PR DESCRIPTION
**Pull request by krishnadurai**
This has been moved to an overlay called gcp-credentials-patch

**Which issue is resolved by this Pull Request:**
Cleanup of extra config file

**Description of your changes:**
`gcp/iap-ingress/base/gcp-credentials-patch.yaml` is no longer required by base and has been moved to an overlay.

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/340)

### CODE REVIEW

**Comment by krishnadurai** [comment]
/cc @lluunn 

Looks like this file wasn't deleted along with: https://github.com/kubeflow/manifests/commit/964f050c2433dfcad7528b5755309271b98569a9#diff-a26b7919407d92453f2cab7aadf5704b

**Comment by lluunn** [comment]
test failure: couldn't generate kustomization file for component iap-ingress

**Comment by krishnadurai** [comment]
@lluunn I'll just get this fixed within sometime. I stumbled across this because of the Istio upgrade I was trying to make.

**Comment by krishnadurai** [comment]
@lluunn the test was failing because kfctl wasn't able to find the basefile: `gcp/iap-ingress/base/gcp-credentials-patch.yaml`
https://github.com/kubeflow/kubeflow/blob/master/bootstrap/pkg/kfapp/kustomize/kustomize.go#L1030

Now I've moved the overlay configs to `deployment.yaml` and `stateful-set.yaml` so that their respective basefile is found after its deletion here.

**Pull request merged**
