### PR TITLE
Change user name to user@example.com in README

### PR DESCRIPTION
**Pull request by andreyvelich**
**Description of your changes:**
To continue this PR: https://github.com/kubeflow/manifests/pull/1857 we should also update few user names in the README.

/cc @DavidSpek @yanniszark @pvaneck 

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by DavidSpek** [comment]
@andreyvelich I don't think this PR is correct. There is some (understandable) confusion surrounding when the `username` and when the `email` is used.

**Comment by andreyvelich** [comment]
> @andreyvelich I don't think this PR is correct. There is some (understandable) confusion surrounding when the `username` and when the `email` is used.

Why ?
Aren't we confusing user if in the installation we are using [`user`](https://github.com/kubeflow/manifests/blob/master/README.md#installation) username and `12341234` password, but in the [port-forward](https://github.com/kubeflow/manifests/blob/master/README.md#port-forward) section we are using `user@example.com` name and `12341234` password ?

**Comment by DavidSpek** [comment]
The confusing part is that Dex login requires the use of the email address, and not the user name. But in this PR you are stating:

```
we use a default username (`user@example.com`)
```
and
```
it includes a static user named `user@example.com`
```
Which is incorrect, as that isn't the username, but rather the user email address.

**Comment by andreyvelich** [comment]
> The confusing part is that Dex login requires the use of the email address, and not the user name. But in this PR you are stating:
> 
> ```
> we use a default username (`user@example.com`)
> ```
> 
> and
> 
> ```
> it includes a static user named `user@example.com`
> ```
> 
> Which is incorrect, as that isn't the username, but rather the user email address.

Got it. What about namespace name. Should I leave the change with the correct one ?
```
Finally, create a new namespace for the the default user (named `kubeflow-user-example-com`).
```

**Comment by yanniszark** [comment]
I agree with the spirit of this PR. Yes, we should mention the same thing everywhere, to not confuse the user.
Moreover, we can also make the wording more accurate, as @DavidSpek suggests.
How about:

> we use a default username (`user@example.com`)

we use a default email (`user@example.com`)

> a static user named `user@example.com`

a static user with email `user@example.com`

**Comment by DavidSpek** [comment]
@yanniszark That looks good to me.
@andreyvelich I think the namespace is still correct yes.

**Comment by andreyvelich** [comment]
Thanks @DavidSpek and @yanniszark. I will make this change.

**Comment by andreyvelich** [comment]
@DavidSpek @yanniszark Are we ready to merge this PR?

**Comment by DavidSpek** [comment]
Looks good to me!

/lgtm

**Comment by yanniszark** [comment]
Thanks @DavidSpek @andreyvelich 
/lgtm
/approve

**Pull request merged**
