### PR TITLE
feat: remove kf metadata server

### PR DESCRIPTION
**Pull request by Bobgy**
**Which issue is resolved by this Pull Request:**
Part of https://github.com/kubeflow/metadata/issues/250

**Description of your changes:**

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by Bobgy** [comment]
/assign @Jeffwan @PatrickXYS @neuromage 
I'm not sure we want to do this now, a problem is that when KF metadata UI virtual service is removed. I think users cannot access KF metadata server either, so I think there's no reason to keep metadata server too.

**Comment by PatrickXYS** [comment]
I think removal sounds reasonable since we have already removed metadata UI virtualservice.

SGTM

/cc @kubeflow/wg-notebook-leads

**Comment by Jeffwan** [comment]
@Bobgy @PatrickXYS I think it makes sense to remove all and only leave grpc deployment and server there. https://github.com/kubeflow/metadata/issues/250

**Comment by Jeffwan** [comment]
https://github.com/kubeflow/kubeflow/pull/5404 PR to remove link in central dashboard

**Pull request merged**
