### PR TITLE
Add permissions to JWA for SubjectAccessReviews

### LINKED ISSUE #654: jupyter-web-app: Add permissions for SubjectAccessReviews
Context [kubeflow/2981](https://github.com/kubeflow/kubeflow/issues/2981). We want Jupyter Web App to use k8s `SubjectAccessReviews` for enforcing authorization.

For this we will need to give JWA's ServiceAccount permissions to create `SubjectAccessReviews`.

/assign kimwnasptd
cc @yanniszark @jlewi

### PR DESCRIPTION
**Pull request by kimwnasptd**
**Which issue is resolved by this Pull Request:**
Resolves #654

**Description of your changes:**

**Checklist:**
- [ ] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

/cc @yanniszark
/cc @jlewi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/655)

### CODE REVIEW

**Comment by yanniszark** [comment]
@kimwnasptd something went wrong with the test generation.
Can you check that the tests are generated correctly?

**Comment by kimwnasptd** [comment]
@yanniszark thanks for notifying me. I had given the git clonned folder a different name from `manifests` and thus the test generation failed to regenerate the tests.

Should be good now.

**Comment by jlewi** [comment]
@kimwnasptd Please revert changes to tests unrelated to the changed manifests.

**Comment by kimwnasptd** [comment]
Alright, I reverted the commits and regenerated the tests. They also seem to pass so we should be good to go.

**Comment by jlewi** [comment]
@kimwnasptd This PR has 52 modified files. Most of the changed files are test files unrelated to this PR. Can you revert changes to those files (e.g. the AWS, Profile, etc... tests) shouldn't need to be updated.

There should be a make command `make generate-changed-only` that only updates tests that should have changed but I think its broken until #665 is merged.

What I usually do is just run `git checkout upstream/master <file>`.

**Comment by kimwnasptd** [comment]
@jlewi thanks for the explanation. I think I (finally) did it right.

**Pull request merged**
