### PR TITLE
Automated cherry pick of #586: Update deployments to use `apps/v1` api version on v0.7-branch.

### PR DESCRIPTION
**Pull request by zhenghuiwang**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/588)

### CODE REVIEW

**Comment by zhenghuiwang** [comment]
/assign @saschagrunert 

@saschagrunert this pr cherry picks your fix of #588 to the release branch. Can you type
`@googlebot I consent.` to grant the permission. Thanks!

**Comment by richardsliu** [comment]
/lgtm
/approve

@zhenghuiwang You can also rebase and squash the commits to avoid the CLA check.

**Comment by saschagrunert** [comment]
@googlebot I consent.

**Comment by LeonardAukea** [comment]
@zhenghuiwang not sure what you wanted help with here. But I can go through the other deployments and  update to `apps/v1` if not already updated.

**Comment by zhenghuiwang** [comment]
> @zhenghuiwang not sure what you wanted help with here. But I can go through the other deployments and update to `apps/v1` if not already updated.

@LeonardAukea We are good now! the PR is cherry picked. Thanks

**Comment by saschagrunert** [comment]
It still looks not 1.16 ready but I doubt that this has to be fixed in this repository.

**Pull request merged**
