### PR TITLE
Remove the old tekton version

### PR DESCRIPTION
**Pull request by hansinikarunarathne**
# Pull Request Template for Kubeflow manifests Issues

- Please include a summary of changes and the related issue. 
- List any dependencies that are required for this change. 
- Please delete the options that are not relevant.
- The following checklist will help you to satisfy the requirements.

## ✅ Contributor checklist
  - [X] All the commits have been _signed-off_  (To pass the `DCO` check)
  - [X] Submit the [Contributor License Agreements](https://cla.developers.google.com/clas) (To pass the `cla/google` check)

---     
 
> You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
@rimolive can you review this, because  you are actively working on the tekton merge?

**Comment by juliusvonkohout** [comment]
@rimolive do you have any concerns?

**Comment by rimolive** [comment]
My advice is to not remove yet. I don't think we had the kfp manifests prepared to use argo or tekton as backend, and these manifests are the reference.

Let's see who will continue the kfp-tekton merge work and let them know this manifest work is missing.

**Comment by juliusvonkohout** [comment]
alright then lets close for now and focus on something else.

**Comment by juliusvonkohout** [comment]
@rimolive either we get a new kfp-tekton release (https://github.com/kubeflow/manifests/blob/2269c67372dd4664edf5faae9eb80d90db2ae7d0/hack/sync-kfp-tekton-manifests.sh) or we have to remove the separate 2.0.5 kfptekton from the manifests since it add many CVEs and seems to be abandoned.

**Comment by juliusvonkohout** [comment]
See also https://github.com/kubeflow/manifests/pull/2856

@hansinikarunarathne  please rebase or create a new PR for this.

**Comment by juliusvonkohout** [comment]
Even in this excerpt the differences are massive
```
Scanning  gcr.io/ml-pipeline/api-server:2.0.5
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    3     |  36  |   76   |  65 |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/api-server:2.2.0
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    3     |  14  |   62   |  63 |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/application-crd-controller:20231101
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    1     |  13  |   19   |  0  |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/cache-deployer:2.2.0
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    13    |  23  |   77   |  2  |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/cache-server:2.2.0
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    1     |  7   |   44   |  6  |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/frontend:2.0.5
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    4     |  36  |   62   |  10 |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/frontend:2.2.0
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    4     |  35  |   57   |  10 |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/inverse-proxy-agent:2.0.5
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    26    | 345  |  1447  | 529 |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/inverse-proxy-agent:2.2.0
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    23    | 303  |  1300  | 529 |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/metadata-envoy:2.0.5
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    0     |  1   |   29   |  43 |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/metadata-envoy:2.2.0
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    0     |  0   |   22   |  34 |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/metadata-writer:2.2.0
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    13    | 186  |  968   | 548 |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    6     |  17  |   14   |  4  |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/mysql:8.0.26
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    26    | 147  |  145   | 135 |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/persistenceagent:2.0.5
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    1     |  12  |   59   |  6  |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/persistenceagent:2.2.0
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    1     |  7   |   44   |  6  |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/scheduledworkflow:2.0.5
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    1     |  12  |   59   |  6  |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/scheduledworkflow:2.2.0
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    1     |  7   |   44   |  6  |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/viewer-crd-controller:2.0.5
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    1     |  5   |   41   |  2  |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/viewer-crd-controller:2.2.0
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    1     |  1   |   27   |  2  |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/visualization-server:2.0.5
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    8     | 117  |  1529  | 234 |
+----------+------+--------+-----+
Scanning  gcr.io/ml-pipeline/visualization-server:2.2.0
+----------+------+--------+-----+
| Critical | High | Medium | Low |
+----------+------+--------+-----+
|    6     | 113  |  1509  | 232 |
+----------+------+--------+-----+
```

**Comment by hansinikarunarathne** [comment]
> Even in this excerpt the differences are massive
> 
> ```
> Scanning  gcr.io/ml-pipeline/api-server:2.0.5
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    3     |  36  |   76   |  65 |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/api-server:2.2.0
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    3     |  14  |   62   |  63 |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/application-crd-controller:20231101
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    1     |  13  |   19   |  0  |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/cache-deployer:2.2.0
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    13    |  23  |   77   |  2  |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/cache-server:2.2.0
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    1     |  7   |   44   |  6  |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/frontend:2.0.5
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    4     |  36  |   62   |  10 |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/frontend:2.2.0
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    4     |  35  |   57   |  10 |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/inverse-proxy-agent:2.0.5
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    26    | 345  |  1447  | 529 |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/inverse-proxy-agent:2.2.0
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    23    | 303  |  1300  | 529 |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/metadata-envoy:2.0.5
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    0     |  1   |   29   |  43 |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/metadata-envoy:2.2.0
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    0     |  0   |   22   |  34 |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/metadata-writer:2.2.0
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    13    | 186  |  968   | 548 |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    6     |  17  |   14   |  4  |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/mysql:8.0.26
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    26    | 147  |  145   | 135 |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/persistenceagent:2.0.5
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    1     |  12  |   59   |  6  |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/persistenceagent:2.2.0
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    1     |  7   |   44   |  6  |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/scheduledworkflow:2.0.5
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    1     |  12  |   59   |  6  |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/scheduledworkflow:2.2.0
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    1     |  7   |   44   |  6  |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/viewer-crd-controller:2.0.5
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    1     |  5   |   41   |  2  |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/viewer-crd-controller:2.2.0
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    1     |  1   |   27   |  2  |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/visualization-server:2.0.5
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    8     | 117  |  1529  | 234 |
> +----------+------+--------+-----+
> Scanning  gcr.io/ml-pipeline/visualization-server:2.2.0
> +----------+------+--------+-----+
> | Critical | High | Medium | Low |
> +----------+------+--------+-----+
> |    6     | 113  |  1509  | 232 |
> +----------+------+--------+-----+
> ```

Is there relationship between CVE count and tekton ? can you elaborate on this more ?

**Comment by hansinikarunarathne** [comment]
> See also #2856
> 
> @hansinikarunarathne please rebase or create a new PR for this.

I rebased the PR with master

**Comment by juliusvonkohout** [comment]
/lgtm

@rimolive is there any plan to revive the tekton repository for 1.10?

**Comment by juliusvonkohout** [comment]
@animeshsingh
 @ckadner
 @Tomcli
 @fenglixa
 @pugangxa
 @scrapcodes
 @yhwang
 @rafalbigaj

Are you still maintaining and planning to update https://github.com/kubeflow/kfp-tekton for KFP 2.2.0+? The last commit is soon 6 months old and it adds a massive amount of CVEs.

**Comment by juliusvonkohout** [comment]
Please check the main readme and /hack folder for tekton related things.

**Comment by juliusvonkohout** [comment]
Hello, i did not get feedback for several months from the maintainers and it is unmaintained for 6+ months. So i will merge this after Kubeflow 1.9.1.

**Comment by juliusvonkohout** [comment]
/approve

 since 1.9.1 is released

**Comment by juliusvonkohout** [comment]
It is a lot less now 

```
+------------------------+--------+--------------+----------+------------+---------+
|     Working Group      | Images | Critical CVE | High CVE | Medium CVE | Low CVE |
+------------------------+--------+--------------+----------+------------+---------+
|         AutoML         |   17   |      35      |   207    |    411     |   804   |
|       Pipelines        |   31   |     186      |   1695   |    6725    |   2360  |
| Workbenches(Notebooks) |   12   |      26      |   221    |    272     |   255   |
|         Kserve         |   14   |      65      |   534    |    5517    |   1662  |
|       Manifests        |   16   |      21      |    35    |    251     |    90   |
|     Model Registry     |   3    |      17      |    72    |    101     |   150   |
|       All Images       |   90   |     330      |   2666   |   13162    |   5237  |
+------------------------+--------+--------------+----------+------------+---------+

+------------------------+--------+--------------+----------+------------+---------+
|     Working Group      | Images | Critical CVE | High CVE | Medium CVE | Low CVE |
+------------------------+--------+--------------+----------+------------+---------+
|         AutoML         |   18   |      38      |   216    |    546     |   783   |
|       Pipelines        |   45   |     249      |   2422   |   11381    |   3378  |
| Workbenches(Notebooks) |   12   |      26      |   221    |    299     |   228   |
|         Kserve         |   14   |      65      |   533    |    5610    |   1590  |
|       Manifests        |   16   |      21      |    35    |    251     |    90   |
|     Model Registry     |   3    |      17      |    72    |    103     |   150   |
|       All Images       |  105   |     396      |   3401   |   18075    |   6135  |
+------------------------+--------+--------------+----------+------------+---------+
```

**Pull request merged**
