### PR TITLE
Add new updated Jupyter notebook images

### PR DESCRIPTION
**Pull request by Tabrizian**
**Which issue is resolved by this Pull Request:**
Resolves #

kubeflow/kubeflow#3725

**Description of your changes:**

This PR updates the Jupyter notebook images.

**Checklist:**
- [X] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/401)

### CODE REVIEW

**Comment by jlewi** [comment]
Thanks @Tabrizian could you please revert the changes to the test files unrelated to your change. 
Since you are only changing the jupyter web config; the tests for the other packages shouldn't change so we shouldn't need to regenerate them.

**Comment by Tabrizian** [comment]
Thanks for the review. I fixed it.

**Comment by Tabrizian** [comment]
@jlewi there was a minor bug in the tests. This needs a LGTM.

**Pull request merged**
