### PR TITLE
Update istio to v1.22.0-beta.1

### PR DESCRIPTION
**Pull request by biswajit-9776**
**Description of your changes:**
Update of istio to version 1.22.0-beta.1

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 5.2.1+**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
1. You need to sign with DCO as explained here https://github.com/kubeflow/manifests/pull/2714/checks?check_run_id=24899922386

**Comment by diegolovison** [comment]
Hello, how this update is done? Are they copying and pasting files?

**Comment by juliusvonkohout** [comment]
> Hello, how this update is done? Are they copying and pasting files?

It is explained in the readme.

**Comment by juliusvonkohout** [comment]
If you do not manage to fix the tests you can also try Istio 1.21 first.

**Comment by juliusvonkohout** [comment]
> > If you do not manage to fix the tests this week you can also try Istio 1.21 first.
> 
> @juliusvonkohout Do you believe the tests/gh-actions/install_multi_tenancy.sh and similar tests are failing due to the istio-1.22.0.beta-1? If that is so, I can create another PR for upgrading istio to v1.21.0 .

That is something to find out by running them locally.

**Comment by juliusvonkohout** [comment]
But yes, you can also open a separate Pr for 1.21 and see which one works better.

**Pull request closed without merging**
