### PR TITLE
Upgrade Knative serving to 1.10.2 and eventing to 1.10.1

### PR DESCRIPTION
**Pull request by annajung**
**Which issue is resolved by this Pull Request:**
Part of https://github.com/kubeflow/manifests/issues/2450

**Description of your changes:**
- Upgrade Knative serving to 1.10.2
- Upgrade Knative eventing to 1.101

cc @kimwnasptd

### CODE REVIEW

**Comment by annajung** [comment]
I used upterm to see what's happening inside the cluster, and it looks like a few of the pods are not coming up because of insufficient resources, so they're in a pending state until the timeout hits, which results in a failed test.

I will take a deeper look into it this week

**Comment by annajung** [comment]
Due to insufficient resources and the default setting that does not allow scheduling pods on the control plane nodes, at some point in the test, pods cannot run and stay in the pending state and fails to meet the condition check for all pods in "ready" state.

It looks like there are two approaches to solving the issue, both have been tested and were successful in running the KServe test
1. Allow scheduling on the control plane
2. Add another worker for kind installation

Not sure which one is better approach @kimwnasptd thoughts?

**Comment by kimwnasptd** [comment]
@annajung I'd also vote for adding another worker node in our config file, just to unblock us for now.

**Comment by annajung** [comment]
@yuzisun  Looks like KServe is using serving 1.10.1 and eventing 1.10.0 according to the [quick install script](https://github.com/kserve/kserve/blob/9b917d8349e4885abe4621db47def0a385ecd76d/hack/quick_install.sh#L34C1-L35C45) and the [github actions](https://github.com/kserve/kserve/blob/9b917d8349e4885abe4621db47def0a385ecd76d/test/scripts/gh-actions/setup-kourier.sh#L27), do you have any concerns with 1.10.2 and eventing 1.10.1?

we like to get this in before the feature freeze Aug 2nd

**Pull request merged**
