### PR TITLE
add application overlays for pipeline

### LINKED ISSUE #469: add application overlays for pipeline
```
└── pipeline
    ├── api-service
    ├── minio
    ├── mysql
    ├── persistent-agent
    ├── pipeline-visualization-service
    ├── pipelines-runner
    ├── pipelines-ui
    ├── pipelines-viewer
    └── scheduledworkflow
```

### PR DESCRIPTION
**Pull request by kkasravi**
**Which issue is resolved by this Pull Request:**
Resolves #469 

**Description of your changes:**
```
└── pipeline
    ├── api-service
    ├── minio
    ├── mysql
    ├── persistent-agent
    ├── pipeline-visualization-service
    ├── pipelines-runner
    ├── pipelines-ui
    ├── pipelines-viewer
    └── scheduledworkflow
```
**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/470)

### CODE REVIEW

**Comment by jlewi** [comment]
Pipelines has their own versioning scheme. The release is 0.1.31
https://github.com/kubeflow/pipelines/releases

So that's what we should set in the application resources.

**Comment by yanniszark** [comment]
@kkasravi isn't the application `Kubeflow Pipelines` and runner, persistence-agent, etc components of that application?
Shouldn't we group all of these components under a single Kubeflow Pipelines Application, as different components?
It seems more in line with the [official Application CRD example](https://github.com/kubernetes-sigs/application/blob/master/docs/example.yaml), where a Server, a Database and a Dashboard are grouped under a wordpress Application.

**Comment by kkasravi** [comment]
> @kkasravi isn't the application `Kubeflow Pipelines` and runner, persistence-agent, etc components of that application?
> Shouldn't we group all of these components under a single Kubeflow Pipelines Application, as different components?
> It seems more in line with the [official Application CRD example](https://github.com/kubernetes-sigs/application/blob/master/docs/example.yaml), where a Server, a Database and a Dashboard are grouped under a wordpress Application.

@yanniszark yes the top level directories under manifests do suggest these types of groupings: gcp, katib, admission-webhook, pipeline, though KfDef isn't organized this way. Upgrades (which use applications) would be much more granular and the Application CR doesn't provide any type of sub-grouping. You would have Application.componentKinds which would include the aggregate list of k8 resources across manifests/pipeline/*. Health level info would also be more granular and possibly more difficult to diagnose. If there were any ordering dependencies under pipeline (as there is under admission-webhook), the Application.componentKinds array doesn't capture this either. I think once we replace the overlays/mixins with kustomize/v3 this might be easier to do.

**Pull request merged**
