### PR TITLE
[IBM] Remap components to application for IBM stack

### PR DESCRIPTION
**Pull request by moficodes**
**Which issue is resolved by this Pull Request:**
Resolves # -

**Description of your changes:**
We are remapping the IBM manifests to use Only application instead of a mix of application and components

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Review by Tomcli — CHANGES_REQUESTED** [review]
For the kfctl_ibm_customstack.yaml URI, can you change it to `https://github.com/kubeflow/manifests/archive/master.tar.gz`. So it can work once this PR is merged? thanks.

**Comment by Tomcli** [comment]
Overall, it looks good to me.

**Review by moficodes — COMMENTED** [review]
@tomcli made the change.

> *[Reviewable](https://reviewable.io/reviews/kubeflow/manifests/1603#-:-MLAtPrX8IEIPN5Azrm-:b-owxztx)* status: 0 of 250 files reviewed, all discussions resolved (waiting on @krishnadurai and @PatrickXYS)

**Comment by Tomcli** [comment]
@moficodes you need to rebase since kfp moved to 1.0.4

**Comment by moficodes** [comment]
@Tomcli Done!

**Comment by Tomcli** [comment]
@moficodes it will be nice if you can squash your commits into one. This way the PR won't show the rebase commits from master.

**Comment by PatrickXYS** [comment]
If you have rebased from master branch, you can try to run test

**Comment by Tomcli** [comment]
/lgtm for the deployment,
I'm not sure why there no presubmit test after the rebase

**Comment by PatrickXYS** [comment]
https://github.com/kubeflow/manifests/pull/1601 

Since we have migrated to AWS Test-infra after this PR merged, can you rebase master and then re-run the test?

**Pull request merged**
