### PR TITLE
(bug) Increase Resources to Tensboard Controller

### LINKED ISSUE #2101: Tensorboards-controller crash loop in OOM Killed
Hello there,

We have encountered a problem about the default resources of tensorboards controller.

We deployed kubeflow following [this section](https://github.com/kubeflow/manifests#install-individual-components) about 60 days ago, starting from v1.3 and upgraded to v1.4.1

We did not keep observing all the service status, but as far as I can remember, all pods were in Running state when we first deploy kubeflow v1.3

Currently we notice that the tensorboard-controller pod keeps crashing because of OOM Killed.

We expanded the memory requests to 40mi and limits to 60mi, and the error is still there.

But both to 100mi the error disappeared.

Is the default resource limit too small?

### PR DESCRIPTION
**Pull request by vinayan3**
**Which issue is resolved by this Pull Request:**
Resolves #2101 

**Description of your changes:**
* Increase resources so that the controller stops crashing.

**Checklist:**
- [ ] Unit tests pass: - no make file.
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/kubeflow/manifests/pull/2173/checks?check_run_id=5561270783

**Comment by vinayan3** [comment]
@Arhell Ii have to work out with the corporate signer what is going on with the CLA. I won't be able to commit until that is sorted out.

**Comment by juangon** [comment]
I am reproducing this problem too

**Comment by kimwnasptd** [comment]
Thanks for the PR @vinayan3! This is definitely something to include.

But, can you make the PR on the `kubeflow/kubeflow` repo where the source of the manifests is? We only copy manifests in this repo from the components' repos.

**Comment by vinayan3** [comment]
> Thanks for the PR @vinayan3! This is definitely something to include.
> 
> But, can you make the PR on the `kubeflow/kubeflow` repo where the source of the manifests is? We only copy manifests in this repo from the components' repos.

Yes I'll get up a PR for this in the main repo. Thanks for letting me know how this works.

**Pull request closed without merging**
