### PR TITLE
chery-pick changes from master

### PR DESCRIPTION
**Pull request by thesuperzapper**
Cherry picking changes from master

**Checklist:**
- [X] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@Jeffwan here is a chery-pick of the changes I made today for the components owned by wg-notebook

**Comment by Jeffwan** [comment]
/cc @Bobgy @PatrickXYS  who has permission to approve

This is cherry-pick PR and reviewed yesterday. We need to cut a new RC release once it's merged

**Pull request merged**
