### PR TITLE
Cherry pick KFP multi user changes to 1.1 branch

### PR DESCRIPTION
**Pull request by Bobgy**
**Which issue is resolved by this Pull Request:**
Part of https://github.com/kubeflow/pipelines/issues/3241

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by Bobgy** [comment]
Because this PR cherry picks multiple commits.
/label tide/merge-method-rebase

**Comment by Bobgy** [comment]
@jlewi is it possible adding labels in https://github.com/kubernetes/test-infra/blob/master/config/prow/config.yaml#L562 to this repo, so I can configure merge method?

**Comment by jlewi** [comment]
@Bobgy sure send me a PR.

how does method rebase work?

**Comment by Bobgy** [comment]
it's not a PR, in github UI, repo maintainers can add new labels to the repo.

Tide can use different merge methods if those labels are present.

**Comment by jlewi** [comment]
@Bobgy Right my question is what is the different merge method doing?

I assume its rebasing off something but what is it rebasing off of and how is that different from the default method?

/lgtm
/approve

**Comment by Bobgy** [comment]
when a PR has multiple commits, the default is to squash them into one before merging.

rebase and merge are also possible, but they keep the original commits in merged branch.


because this PR cherrypicks many past commits, I think It makes more sense not squashing to one commit.


if we add the suggested labels, PR author can configure merge behavior for specific PRs

**Pull request merged**
