### PR TITLE
Solve identation issue in new spark operator overlay.

### PR DESCRIPTION
**Pull request by jbrette**
**Which issue is resolved by this Pull Request:**
Resolves #
The indentation issue prevents make test to work since the yaml syntax is incorrect.

**Description of your changes:**

- Add two spaces in the spark/overlays/application.yaml
- rerun make generate.
- rerun make test

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/377)

### CODE REVIEW

**Comment by jbrette** [comment]
@richardsliu  make tests broke after the merge of #174.

/cc @holdenk

**Comment by holdenk** [comment]
/ok-to-rest
Sorry about the white space changes breaking your test.

**Comment by jbrette** [comment]
The indentation [fix](https://github.com/kubeflow/manifests/pull/309/commits/365562963155bb75540bcc020ff79a60d22af781) has been merged with the upgrade to kustomize 3.x #309 . The code has been regenerated at the same time, hence we don't need this PR anymore.
Closing this PR and associated deflect.

**Pull request closed without merging**
