### PR TITLE
istio: oidc-authservice: add readiness probe and update image

### PR DESCRIPTION
**Pull request by yanniszark**
Signed-off-by: Yannis Zarkadas <yanniszark@arrikto.com>

**Which issue is resolved by this Pull Request:**
Resolves https://github.com/kubeflow/manifests/issues/632
Hopefully a fix for https://github.com/arrikto/oidc-authservice/issues/2

**Description of your changes:**
Adds a readiness check to the OIDC authservice and updates image to new version.

**Checklist:**
- [X] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/633)

### CODE REVIEW

**Comment by krishnadurai** [comment]
@yanniszark you could self approve.

**Comment by yanniszark** [comment]
@krishnadurai @ryandawsonuk had to rebase, could you lgtm again?
Thanks!

**Pull request merged**
