### PR TITLE
cve: fix Double-count in "All Images" for CVE image scan report

### LINKED ISSUE #2855: Double-count in "All Images" for CVE image scan report
### Validation Checklist

- [X] Is this a Kubeflow issue?
- [X] Are you posting in the right repository ?
- [X] Did you follow the installation guide https://github.com/kubeflow/manifests?tab=readme-ov-file ?
- [X] Is the issue report properly structured and detailed with version numbers?
- [ ] Is this for Kubeflow development ?
- [X] Would you like to work on this issue?
- [X] You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### Version

master

### Describe your issue

With the KF 1.9 release, a CVE scanning report for images have been provided:
- https://blog.kubeflow.org/kubeflow-1.9-release/#cve-scanning

However the table "All Images" line is having some double-counting error:
Screenshot 2024-08-22 at 12 44 03

That is because, for instance, `Model Registry` accounts for a total of 3 images, but actually 2 are shared with the `Pipelines`:
- `mysql:8.0.3`
- `gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0`

### Steps to reproduce the issue

Running in the `hack` the `python trivy_scan.py` only for Pipelines and Model Registry results in:

```
+----------------+--------+--------------+----------+------------+---------+
| Working Group  | Images | Critical CVE | High CVE | Medium CVE | Low CVE |
+----------------+--------+--------------+----------+------------+---------+
|   Pipelines    |   45   |     226      |   2138   |   10112    |   3339  |
| Model Registry |   3    |      17      |    71    |    103     |   151   |
|   All Images   |   48   |     243      |   2209   |   10215    |   3490  |
+----------------+--------+--------------+----------+------------+---------+
```

While "All Images" should be resulting in 46, since Model Registry has only 1 image in addition to the same one shared with Pipelines.

### Put here any screenshots or videos (optional)

/assign @tarilabs 

I'm going to submit a PR shortly.

### PR DESCRIPTION
**Pull request by tarilabs**
## ✏️ A brief description of the changes
See #2855
To avoid double-counting, a dictionary with entry key==image_name is used for the rolling totals.

## 📦 List any dependencies that are required for this change
None.

## 🐛 If this PR is related to an issue, please put the link to the issue here.
Resolves #2855

## ✅ Contributor checklist
  - Make sure you have tested with kustomize. See [Installation Prerequisites](https://github.com/kubeflow/manifests#prerequisites)
  - All the commits have been _signed-off_  (To pass the `DCO` check)
  - Submit the [Contributor License Agreements](https://cla.developers.google.com/clas) (To pass the `cla/google` check)

---     
 
> You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).
  
---

With Pipelines being:

```
docker.io/metacontrollerio/metacontroller:v2.0.4
gcr.io/cloudsql-docker/gce-proxy:1.25.0
gcr.io/ml-pipeline/api-server:2.0.5
gcr.io/ml-pipeline/api-server:2.2.0
gcr.io/ml-pipeline/application-crd-controller:20231101
gcr.io/ml-pipeline/cache-deployer:2.2.0
gcr.io/ml-pipeline/cache-server:2.2.0
gcr.io/ml-pipeline/frontend:2.0.5
gcr.io/ml-pipeline/frontend:2.2.0
gcr.io/ml-pipeline/inverse-proxy-agent:2.0.5
gcr.io/ml-pipeline/inverse-proxy-agent:2.2.0
gcr.io/ml-pipeline/metadata-envoy:2.0.5
gcr.io/ml-pipeline/metadata-envoy:2.2.0
gcr.io/ml-pipeline/metadata-writer:2.2.0
gcr.io/ml-pipeline/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance
gcr.io/ml-pipeline/mysql:8.0.26
gcr.io/ml-pipeline/persistenceagent:2.0.5
gcr.io/ml-pipeline/persistenceagent:2.2.0
gcr.io/ml-pipeline/scheduledworkflow:2.0.5
gcr.io/ml-pipeline/scheduledworkflow:2.2.0
gcr.io/ml-pipeline/viewer-crd-controller:2.0.5
gcr.io/ml-pipeline/viewer-crd-controller:2.2.0
gcr.io/ml-pipeline/visualization-server:2.0.5
gcr.io/ml-pipeline/visualization-server:2.2.0
gcr.io/ml-pipeline/workflow-controller:v3.3.10-license-compliance
gcr.io/ml-pipeline/workflow-controller:v3.4.16-license-compliance
gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.53.2@sha256:2cab05747826e7c32e2c588f0fefd354e03f643bd33dbe20533eada00562e6b1
gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/events:v0.53.2@sha256:0cf6f0be5319efdd8909ed8f987837d89146fd0632a744bf6d54bf83e5b13ca0
gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.53.2@sha256:6578d145acd9cd288e501023429439334de15de8bd77af132c57a1d5f982e940
gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.53.2@sha256:1e8f8be3b51be378747b4589dde970582f50e1e69f59527f0a9aa7a75c5833e3
gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0
gcr.io/tfx-oss-public/ml_metadata_store_server:1.5.0
mysql:8.0.3
postgres:14.7-alpine3.17
python:3.7
quay.io/aipipeline/apiserver:2.0.0
quay.io/aipipeline/apiserver:2.0.5
quay.io/aipipeline/persistenceagent:2.0.0
quay.io/aipipeline/persistenceagent:2.0.5
quay.io/aipipeline/pipelineloop-controller:1.9.2
quay.io/aipipeline/pipelineloop-webhook:1.9.2
quay.io/aipipeline/scheduledworkflow:2.0.0
quay.io/aipipeline/scheduledworkflow:2.0.5
quay.io/aipipeline/tekton-exithandler-controller:2.0.5
quay.io/aipipeline/tekton-exithandler-webhook:2.0.5
quay.io/aipipeline/tekton-kfptask-controller:2.0.5
quay.io/aipipeline/tekton-kfptask-webhook:2.0.5
```

and Model Registry being:

```
gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0
kubeflow/model-registry:latest
mysql:8.0.3
```

and therefore **_common_** images being:

```
gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0
mysql:8.0.3
```

## Before

```
+----------------+--------+--------------+----------+------------+---------+
| Working Group  | Images | Critical CVE | High CVE | Medium CVE | Low CVE |
+----------------+--------+--------------+----------+------------+---------+
|   Pipelines    |   45   |     226      |   2138   |   10112    |   3339  |
| Model Registry |   3    |      17      |    71    |    103     |   151   |
|   All Images   |   48   |     243      |   2209   |   10215    |   3490  |
+----------------+--------+--------------+----------+------------+---------+
```

## After (with the changes in this PR)

```
+----------------+--------+--------------+----------+------------+---------+
| Working Group  | Images | Critical CVE | High CVE | Medium CVE | Low CVE |
+----------------+--------+--------------+----------+------------+---------+
|   Pipelines    |   45   |     226      |   2138   |   10112    |   3339  |
| Model Registry |   3    |      17      |    71    |    103     |   151   |
|   All Images   |   46   |     226      |   2138   |   10125    |   3407  |
+----------------+--------+--------------+----------+------------+---------+
```

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
Thank you very much for the PR. @hansinikarunarathne please review

**Comment by juliusvonkohout** [comment]
@rimolive either we get a new kfp-tekton release (https://github.com/kubeflow/manifests/blob/2269c67372dd4664edf5faae9eb80d90db2ae7d0/hack/sync-kfp-tekton-manifests.sh) or we have to remove the separate 2.0.5 kfptekton from the manifests since it add many CVEs and seems to be abandoned.

**Comment by tarilabs** [comment]
This PR is about removing a wrong-double-count from the generated report, when WGs/Components share the same image.
I believe other concerns are to be addressed separately.

**Comment by juliusvonkohout** [comment]
@tarilabs i revived https://github.com/kubeflow/manifests/pull/2772 for that purpose

**Comment by tarilabs** [comment]
great! so can we get this merged as well for having instead the double-counting corrected?
just want to make sure i completed all tasks required to have this PR merged.

**Comment by tarilabs** [comment]
thank you @juliusvonkohout

**Pull request merged**
