### PR TITLE
fix mismatched comment and command in exmaple/kustomization.yaml 

### PR DESCRIPTION
**Pull request by kairos03**
**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**
- fix mismatched comment and command in `exmaple/kustomization.yaml`

**Checklist:**
- [x] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by juliusvonkohout** [comment]
/close

solved in master

There has been no activity for a long time. Please reopen if necessary.

**Pull request closed without merging**
