### PR TITLE
Add steps to install Kubeflow on kind

### PR DESCRIPTION
**Pull request by diegolovison**
**Which issue is resolved by this Pull Request:**
Resolves the missing steps to be able to get Kubeflow up and running locally.

**Description of your changes:**
It will add some steps in order to make it easy to have Kubeflow on top of kind.

**Checklist:**
- [ x ] Unit tests pass:
  **Make sure you have installed kustomize == 5.0.3**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
Is podman also possible? I am always reluctant towards insecure docker stuff.

**Comment by diegolovison** [comment]
I wasn't able to make it working with podman. May we create an issue and work on that later?

**Comment by juliusvonkohout** [comment]
You are the documentation lead so

/approve

**Pull request merged**
