### PR TITLE
Update manifests for AutoML WG 0.12-rc.0

### LINKED ISSUE #1970: Sync AutoML WG manifests for KF 1.4-RC0
Sub issue from #1958 

We need to update the manifests provided by the AutoML WG with this repo, before cutting the first RC of manifests.

cc @kubeflow/wg-automl-leads

### PR DESCRIPTION
**Pull request by kimwnasptd**
closes #1970 

I copied the manifests from https://github.com/kubeflow/katib/tree/v0.12.0-rc.0/manifests/v1beta1

/cc @andreyvelich @johnugeorge @gaocegege

### CODE REVIEW

**Review by andreyvelich — COMMENTED** [review]
Thank you @kimwnasptd!
Should we also update README: https://github.com/kubeflow/manifests#kubeflow-components-versions ?

**Comment by kimwnasptd** [comment]
Good point! 

I'll add a commit to update the Katib version in this PR and then I'll create another one to ensure the versions are up to date for all components before the RC is cut in manifests

**Comment by kimwnasptd** [comment]
Pushed a commit to update the README.

PTAL

**Review by andreyvelich — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
