### PR TITLE
Set better stalebot parameters

### LINKED ISSUE #2514: To many open issues and PRs and no stalebot
@kimwnasptd @annajung 

We have 140 open issues. Some of them are against e.g. Kubeflow 1.3 and many are just spam or legacy stuff. Who has the permissions to manage and close them ? https://github.com/kubeflow/manifests/issues?page=6&q=is%3Aissue+is%3Aopen
The same goes for open PRs of which some are from 2021 https://github.com/kubeflow/manifests/pull/1925
[kimonas] Anna to the rescue with /close
[anna] Should we use the stalebot for closing some automatically?
[julius] The stalebot is not  maintained anymore
[anna] maybe we could use GH Apps (not actions) for closing those

I will still go trough them manually on a weekend.

### PR DESCRIPTION
**Pull request by rimolive**
**Which issue is resolved by this Pull Request:**
Resolves #2514

**Description of your changes:**
Setup parameters for stalebot similar to kubeflow/pipelines repo. That way issues/PRs can stay for a relevant timeframe.

**Checklist:**
- [X] Unit tests pass:
  **Make sure you have installed kustomize == 5.2.1+**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
@rimolive please cross check with my early efforts in https://github.com/kubeflow/manifests/compare/master...issue-templates.

**Comment by juliusvonkohout** [comment]
@hansinikarunarathne might help here as well @rimolive. She is anyway interested in the triaging and stalebot GSOC proposal. On Slack she is hansini karunarathne as well.

**Comment by juliusvonkohout** [comment]
@Ayush9026 is also interested @rimolive on Slack Ayush Gupta

**Comment by juliusvonkohout** [comment]
@rimolive and the same goes for @siddeshas07 on Slack Siddesh A S. All three have valid applications for GSOC and were interviewed by me.

**Comment by rimolive** [comment]
Let's discuss in the next manifests WG about this PR. I'll add in the meeting notes.

**Comment by juliusvonkohout** [comment]
superseded by https://github.com/kubeflow/manifests/pull/2760

**Pull request closed without merging**
