### PR TITLE
fix(knative): aggregate knative namespaced roles to kubeflow roles

### LINKED ISSUE #1876: Aggregate knative namespaced roles to kubeflow roles
On multi-user mode, users can not list knative resources in their namespaces.

For example, below error occurs on `kubectl get services.serving.knative.dev -n xxx`

```sh
Error from server (Forbidden): services.serving.knative.dev is forbidden: User "xxx" cannot list resource "services" in API group "serving.knative.dev" in the namespace "xxx"
```
I created a PR for fixing this issue. Please take a look, thanks!

### PR DESCRIPTION
**Pull request by henrysecond1**
**Which issue is resolved by this Pull Request:**
Resolves #1876

**Description of your changes:**

This PR aggregates knative namespaced roles to kubeflow roles.

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by pvaneck** [comment]
Hey, thanks for catching this, and I think this is indeed needed. The Knative install structure was changed a bit when the Knative version was updated. Do you mind adding these labels as kustomize patches [here](https://github.com/kubeflow/manifests/tree/master/common/knative/knative-serving-install/base/patches) where you'd have another file like `clusterrole-patch.yaml` with contents like: 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-admin: "true"
  name: knative-serving-namespaced-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
  name: knative-serving-namespaced-edit
...etc
```

**Comment by henrysecond1** [comment]
Sure, thanks for checking it. I'll rebase and update PR.

**Comment by henrysecond1** [comment]
@pvaneck I updated my PR. Used kustomize patches to add labels. I deployed generated manifests to my dev cluster and it worked as expected. Please check, thanks.

**Review by pvaneck — COMMENTED** [review]
Hey, the patches look good. There was one more refactoring just recently where the eventing and serving folders were each consolidated and renamed. Can you rebase one more time?

@yanniszark I think this will be good to have in the upcoming release.

**Comment by henrysecond1** [comment]
I rebased my PR :)

**Review by pvaneck — COMMENTED** [review]
/lgtm

**Comment by kimwnasptd** [comment]
Apologies for the delayed review. @henrysecond1 thank you both for catching this and submitting the PR. Also @pvaneck thank you very much for taking a look and reviewing this!

I also checked out the changes and they look good, so lets merge this one. 

Note that for the 1.3.1 release I hadn't tested this PR so the latest `1.3.1-rc.0` tag did not include this, but I'll create a new tag for this once it gets merged.

**Pull request merged**
