### PR TITLE
Add container port to profile deployment

### LINKED ISSUE #976: Profiles deployment has missing port
We have installed Kubeflow with the vanilla deployment configuration in the cluster and we have setup Istio routing to it with SDS. After this we got an error in the UI ("Unable to contact Profile Controller").

The access to the `profiles-kfam.kubeflow` service was blocked. I found out that there is no `ports` section in the profiles deployment. When I added the following snippet the problem was resolved:

```
spec:
  ...
  template:
    ...
    spec:
      ...
      containers:
      - name kfam
        ports:
        - containerPort: 8081
          name: kfam-http
          protocol: TCP

```

### PR DESCRIPTION
**Pull request by Bobgy**
**Which issue is resolved by this Pull Request:**
Resolves #976

**Description of your changes:**
Add containerPort to profile deployment.
Required as per https://github.com/kubeflow/manifests/issues/976#issuecomment-599879207

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/1021)

### CODE REVIEW

**Comment by Bobgy** [comment]
Looks like an flaky test
/retest

**Comment by Bobgy** [comment]
Not sure why there are many test file location change, that might be an issue with the new test generation script.

@jlewi Are the newly generated test changes expected or not?

**Comment by jlewi** [comment]
The changes to the test file locations are expected see #1016 

/assign @kunmingg

**Comment by Bobgy** [comment]
Looks like presubmit test is stuck at pending, maybe my accidental closing the PR confuses tide bot. I will open a new one instead.

**Comment by Bobgy** [comment]
/close
Use https://github.com/kubeflow/manifests/pull/1042 instead

**Pull request closed without merging**
