### PR TITLE
Fix basic auth cloud endpoint missing target namespace and appName

### PR DESCRIPTION
**Pull request by kunmingg**
Basic auth cloud endpoint missed target namespace and appName.
This PR patch them to cloud endpoint config.

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/243)

### CODE REVIEW

**Comment by jlewi** [comment]
@kunmingg Can you describe the bug and fix please?

**Comment by kunmingg** [comment]
@jlewi 
description updated.

**Pull request merged**
