### PR TITLE
Sync kubeflow training operator manifests v1.4.0 rc.0

### PR DESCRIPTION
**Pull request by kimwnasptd**
Refs #2105 

cc @terrytangyuan @johnugeorge 
/cc @StefanoFioravanzo @elikatsis

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
LGTM from a quick glance but could you run a diff check with upstream?

**Review by terrytangyuan — APPROVED** [review]
Please unhold whenever it's ready after the diff check.

/lgtm
/hold

**Comment by johnugeorge** [comment]
Thanks @kimwnasptd 

/lgtm

**Comment by kimwnasptd** [comment]
> LGTM from a quick glance but could you run a diff check with upstream?

I'm using scripts for doing the copy-pasting and creating the branch for the PR https://github.com/kubeflow/manifests/blob/master/hack/sync-training-operator-manifests.sh

I double checked one more time though and the files are as they are, using the `v1.4.0-rc.0` tag for training operator.

/hold cancel

**Pull request merged**
