### PR TITLE
Add argo to stacks/generic

### PR DESCRIPTION
**Pull request by Bobgy**
**Which issue is resolved by this Pull Request:**
Follow up of https://github.com/kubeflow/manifests/pull/1185
Part of https://github.com/kubeflow/manifests/issues/1090

**Description of your changes:**
Add argo to `stacks/generic`

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by Bobgy** [comment]
Friendly ping @jlewi, can you review this?
(it's the base for two other PRs, and more incoming, so I'd hope this one gets reviewed early)

**Comment by jlewi** [comment]
/lgtm
/approve

But looks like there are conflicts

**Comment by Bobgy** [comment]
The mysql PR based on minio and argo, but it was merged first

**Comment by Bobgy** [comment]
Merged together in https://github.com/kubeflow/manifests/pull/1247
/close

**Pull request closed without merging**
