### PR TITLE
Add scripts to make user creation and deletion easier.

### PR DESCRIPTION
**Pull request by choudhryfrompak**
# Pull Request Template for Kubeflow manifests Issues

## ✅ Contributor checklist
  - Make sure you have tested with kustomize. See [Installation Prerequisites](https://github.com/kubeflow/manifests#prerequisites)
  - All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

---     
 
> You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### CODE REVIEW

**Comment by choudhryfrompak** [comment]
I think this will be a notable contribution. as of now the user creation in kubeflow is complicated.. These scripts can change that. Kindly review for changes, I am always up for improvement. Thanks

**Comment by choudhryfrompak** [comment]
I am contributing to a project for first time.. if there is something i am doing wrong, let me know so i can fix that

**Comment by juliusvonkohout** [comment]
Hello @choudhryfrompak , i only see a submodule but no direct code. The static users are just for playing around. What i am rather looking for is a simple example for users to add an oidc connector to dex. So a second example overlay based on https://github.com/kubeflow/manifests/blob/master/common/dex/overlays/oauth2-proxy/config-map.yaml that adds for example a generic oidc provider as in https://dexidp.io/docs/connectors/oidc/ we could also just add it commented out to https://github.com/kubeflow/manifests/blob/master/common/dex/overlays/oauth2-proxy/config-map.yaml for now and link to it in the main readme.

**Comment by choudhryfrompak** [comment]
Thank you for the review. I will continue working to meet the community's expectations. Additionally, I will create a new pull request to add the link as a comment in the ConfigMap and provide an explanation for it in the main README.

**Pull request closed without merging**
