### PR TITLE
Pipelines kustomize v3 manifest

### PR DESCRIPTION
**Pull request by Bobgy**
**Which issue is resolved by this Pull Request:**
Resolves https://github.com/kubeflow/manifests/issues/1048
Resolves https://github.com/kubeflow/manifests/issues/897
Resolves https://github.com/kubeflow/pipelines/issues/3993

**Description of your changes:**
Add kustomize v3 manifest for pipelines.
In addition to existing pipelines components, I also integrated the newly introduced components:
* cache server
* metadata writer

/cc @Ark-kun 

I verified these with gcp blueprint deployment, caching and metadata writer both works properly.

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by Bobgy** [comment]
@jlewi I removed most of the vars after rebasing to kfp rc2 manifest with changes in https://github.com/kubeflow/pipelines/pull/3978.

The remaining usages of var are:
* virtual service: clusterDomain and namespace, https://github.com/kubeflow/manifests/pull/1248/files#diff-adc2be74d4efe3becc4b6ea7bec4d15bR37
* minio and mysql: pv name and pd name
https://github.com/kubeflow/manifests/pull/1248/files#diff-adc2be74d4efe3becc4b6ea7bec4d15bR37 and https://github.com/kubeflow/manifests/blob/f68a7fbb2917d450b685da800d3d4612d14536d2/pipeline/minio/installs/gcp-pd/kustomization.yaml#L16-L32 ( they are using the same pattern )

I'm not sure why we are parameterizing PV name, it was consistent with KF 1.0 manifest. I'll take a look at commit history to find why. I'm guessing that's because persistence volume is immutable after creation, so for proper devops action of changing a PV, it's best to customize the name to use a new PV.

Because this PR is huge. I suggest we separate a PR for how to get rid of the last 4 vars (if we do want to).

**Comment by Bobgy** [comment]
I did some investigation, the PV, PVC name parameterization by var was added in https://github.com/kubeflow/manifests/pull/104. However, it didn't explain any reasoning about why they were added.

@gabrielwen Do you have context why we needed to parameterize PV and PVC name for pipeline's mysql and minio db?

**Comment by jlewi** [comment]
Thanks @Bobgy I think most of the vars you mentioned are for internal substitution; e.g.
namespace. Per the [guide](https://github.com/kubeflow/manifests/blob/master/docs/KustomizeBestPractices.md#internal-subsitution-of-fields-kustomize-isnt-aware-of) this is ok as long as we give the vars unique enough names so we don't conflict with similar vars from other packages.

A better solution for clusterDomain is being tracked in https://github.com/kubeflow/manifests/issues/1007#issuecomment-619404552

You can keep that one as is for now. On GCP we can probably just switch to `kpt setters` since we are already using `kpt setter`.

> @gabrielwen Do you have context why we needed to parameterize PV and PVC name for pipeline's mysql and minio db?

I think it might have been related to how we were creating the PD. I think we may have been using deployment manager (and now KCC) to create the PD and thus needed to substitute in the correct name to the package. 

I think the reasoning was we wanted to use KCC/DM and not the dynamic provisioner to create the PD because we wanted to make sure the PD wasn't destroyed if KF was deleted because we didn't want to destroy any data.

I'm good with submitting PR as is and filing issues to track fixing things later.

**Comment by Bobgy** [comment]
@jlewi the conflicts were caused by `env` to `envs` change: https://github.com/kubeflow/manifests/commits/master/pipeline/upstream

but kfp standalone manifests don't support `envs` yet, because we wanted to maintain `kubectl kustomize` compatibility, which uses a kustomize v2.x version: https://github.com/kubernetes-sigs/kustomize#kubectl-integration.

I'll ask the PR owner for a resolution.

**Comment by Bobgy** [comment]
I updated kfp pull upstream script to use `sed` for a quick HACK that transforms `env:` to `envs:` during pull: https://github.com/kubeflow/manifests/pull/1248/commits/a842b7b042ed22edbd37f2c4678fe0121e8aa3a4

What do you think?

**Comment by jlewi** [comment]
SGTM

Although you could also write a kpt FN transformer.

kustomize 2.x is very old. A lot of things won't work if you rely on it.

/lgtm
/approve

**Comment by Bobgy** [comment]
> Although you could also write a kpt FN transformer.

Thanks for sharing, will try that next time


> kustomize 2.x is very old. A lot of things won't work if you rely on it.

convenience from kubectl is the major reason we keep using it. We will consider upgrading when we get the first blocking issue

**Pull request merged**
