### PR TITLE
Add notebook crd validation

### PR DESCRIPTION
**Pull request by zabbasi**
related to https://github.com/kubeflow/kubeflow/issues/2417 and https://github.com/kubeflow/kubeflow/pull/3394

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/109)

### CODE REVIEW

**Comment by zabbasi** [comment]
tested validation by applying a sample notebook manifest
update tests by running the followings under tests: 
1. `make generate`
1. `make tests`

locally all tests passed.

\retest

**Comment by lluunn** [comment]
There are some katib changes in the PR, is it intended?

**Comment by richardsliu** [comment]
The katib changes in the PR looked like naming conflicts, the v1alpha1 suffix should be kept.

**Pull request merged**
