### PR TITLE
Katib 0.10 v1beta1 release

### PR DESCRIPTION
**Pull request by andreyvelich**
**Which issue is resolved by this Pull Request:**
Related: https://github.com/kubeflow/katib/issues/1360.
Blocked by: https://github.com/kubeflow/katib/pull/1356, https://github.com/kubeflow/katib/pull/1355, https://github.com/kubeflow/katib/pull/1339.
The manifests are ready, but I need to change images once we release them.

/assign @johnugeorge @gaocegege 
/cc @jlewi 

**Description of your changes:**

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by Jeffwan** [comment]
Hi @andreyvelich Is this the version you like to release in kubeflow 1.2?

**Comment by andreyvelich** [comment]
@Jeffwan Yes, I am waiting for this: https://github.com/kubeflow/katib/pull/1344.
After, I'll update manifests with the latest images / manifest changes.

**Comment by andreyvelich** [comment]
I changed image tag to `v1beta1-e294a90`, let's merge this PR for the new manifests changes.
If we need to update tag for the Katib 0.10, I'll do it in the following PR.
Please, take a look @gaocegege @johnugeorge.

**Comment by Jeffwan** [comment]
```
fatal: could not create leading directories of '/mnt/test-data-volume/kubeflow-manifests-presubmit-unit-1593-928486b-2768-a695/src/ku
beflow/manifests': No space left on device
```

@andreyvelich Have you tried this to clean up disk ?https://github.com/kubeflow/testing/blob/master/playbook/playbook.md#nfs-volume-is-out-of-disk-space

**Comment by andreyvelich** [comment]
@Jeffwan It seems to be full, let me try to follow [first way](https://github.com/kubeflow/testing/blob/master/playbook/playbook.md#deleting-old-directories-on-the-nfs-share) to delete it.
/cc @jlewi

**Review by gaocegege — COMMENTED** [review]
/lgtm

**Pull request merged**
