### PR TITLE
Upgrades Istio in kfctl_istio_dex kfdef

### PR DESCRIPTION
**Pull request by krishnadurai**
**Which issue is resolved by this Pull Request:**
Resolves kubeflow/kubeflow#4501

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/620)

### CODE REVIEW

**Comment by krishnadurai** [comment]
@ellis-bigelow Istio 1.3.1 was converted and added to manifests about 2 weeks back. The Kfdef here is just trying to incorporate it.
We should soon look to upgrade to 1.4+ in manifests.

**Comment by krishnadurai** [comment]
@animeshsingh @yuzisun this is the PR I'm working on. Just need to setup a cluster and verify and we could look to merge it. Pre-submits are clearing.

**Comment by krishnadurai** [comment]
This is ready for review. I've tested this in a fresh cluster.

Only thing blocking is the correction of pre-submits here:
https://github.com/kubeflow/kfctl/pull/96

@jlewi @yanniszark

**Comment by krishnadurai** [comment]
@jlewi @yanniszark can we look to merge this PR?

**Comment by krishnadurai** [comment]
Looks like we might not be able to confirm through presubmits in kfctl too:

https://github.com/kubeflow/kfctl/blob/master/prow_config.yaml#L66-L69

**Comment by jlewi** [comment]
There's an open issue for the presubmits #613.

/lgtm
/approve

**Comment by krishnadurai** [comment]
@animeshsingh you could look to use this config for Istio 1.3.1.

**Pull request merged**
