### PR TITLE
Remove tensorboard manifest

### LINKED ISSUE #415: Remove tensorboard manifest and from KFDef
Hi!

Was poking around in the generated kubeflow installation based on the `kfctl_k8s_istio.yaml` manifest, which, in the version I have, by default contains a Tensorboard deployment. When I asked about it @jlewi pointed out that it should not be there by default and asked me to post an issue about it. I can't find a version number for it, I don't remember what version of kfctl I was using at the time but I downloaded the kfctl manifest at least before September 14, 22:25 if that helps!

### PR DESCRIPTION
**Pull request by Jeffwan**
**Which issue is resolved by this Pull Request:**
Resolves #415 

**Description of your changes:**
Remove following items
 - tensorboard/
 - references in kfdef/. I didn't touch pinned manifest, just change master files.
 - stacks/  - aws and ibm has some references
 - tests/tests/legacy_kustomizations/tensorboard

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by Jeffwan** [comment]
/cc @adrian555 @animeshsingh 

Please confirm on the IBM changes. I think we added tensorboard because it's from original manifest. This component should be deprecated. I remove them from IBM stacks. Check #415 for more details. 

This will be integrated into https://github.com/kubeflow/kubeflow/issues/3578 in the future. We may bring new manifest later in future versions.  I only touch master manifest.

**Comment by Jeffwan** [comment]
@jlewi Can you help approve the change?

**Comment by jlewi** [comment]
Thanks!
/lgtm
/approve

**Comment by supertetelman** [comment]
Is there any chance of this being cherry-picked into  v1.1-rc.2?

**Pull request merged**
