### PR TITLE
Added securityContext profiles for deployments failing PSS restricted level

### PR DESCRIPTION
**Pull request by biswajit-9776**
# Pull Request Template for Kubeflow manifests Issues

## ✅ Contributor checklist
  - Make sure you have tested with kustomize. See [Installation Prerequisites](https://github.com/kubeflow/manifests#prerequisites)
  - All the commits have been _signed-off_  (To pass the `DCO` check)
  - Submit the [Contributor License Agreements](https://cla.developers.google.com/clas) (To pass the `cla/google` check)

---     
 
> You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2).

### CODE REVIEW

**Comment by biswajit-9776** [comment]
Will be adding more to the patches and will rename them after the warnings I get locally vanish out.

**Comment by biswajit-9776** [comment]
@juliusvonkohout, I have undone the changes to the cronjob, the patches for pipelines, profile controller and other deployments of static namespaces are here. Do let me know if you need anything else before merging.

**Comment by juliusvonkohout** [comment]
For the cronjob you need to work together with hansini

/lgtm
/approve

**Pull request merged**
