### PR TITLE
Update manifests for 1.3 RC

### LINKED ISSUE #1775: Release 1.3 - Sync manifests from upstream repos
In order to cut the 1.3 release, we need to sync manifests from the upstream repos. For this reason, the manifests wg needs to gather the git revisions from each upstream repo, in order to sync them here.

| Application | Manifests Path | Upstream Path | Upstream Repo | Revision |
| --- | --- | --- | --- | --- |
| TFJob Operator | apps/tf-training/upstream | manifests | https://github.com/kubeflow/tf-operator | `v1.1.0 ` |
| PyTorch Operator | apps/pytorch-job/upstream | manifests | https://github.com/kubeflow/pytorch-operator | `v0.7.0` |
| MPI Operator | apps/mpi-job/upstream | manifests | https://github.com/kubeflow/mpi-operator | `b367aa55886d2b042f5089df359d8e067e49e8d1` |
| MXNet Operator | apps/mxnet-job/upstream | manifests | https://github.com/kubeflow/mxnet-operator | `v1.1.0` |
| XGBoost Operator | apps/xgboost-job/upstream | manifests | https://github.com/kubeflow/xgboost-operator | `v0.2.0` |
| Notebook Controller | apps/jupyter/notebook-controller/upstream | components/notebook-controller/config | https://github.com/kubeflow/kubeflow | `origin/v1.3.0-rc.0` |
| Central Dashboard | apps/centraldashboard/upstream | components/centraldashboard/manifests | https://github.com/kubeflow/kubeflow | `origin/v1.3.0-rc.0` |
| Profiles + KFAM | apps/profiles/upstream | components/profile-controller/config | https://github.com/kubeflow/kubeflow | `origin/v1.3.0-rc.0` |
| PodDefaults Webhook | apps/admission-webhook/upstream | components/admission-webhook/manifests | https://github.com/kubeflow/kubeflow | `origin/v1.3.0-rc.0` |
| Jupyter Web App | apps/jupyter/jupyter-web-app/upstream | components/crud-web-apps/jupyter/manifests | https://github.com/kubeflow/kubeflow | `origin/v1.3.0-rc.0` |
| Volumes Web App | apps/volumes-web-app | components/crud-web-apps/volumes/manifests | https://github.com/kubeflow/kubeflow |  `origin/v1.3.0-rc.0` |
| Tensorboards Web App | apps/tensorboard/tensorboards-web-app | components/crud-web-apps/tensorboards/manifests | https://github.com/kubeflow/kubeflow |  `origin/v1.3.0-rc.0` |
| Tensorboard Controller | apps/tensorboard/tensorboard-controller | components/tensorboard-controller/config | https://github.com/kubeflow/kubeflow | `origin/v1.3.0-rc.0` |
| Katib | apps/katib/upstream | manifests/v1beta1 | https://github.com/kubeflow/katib | `v0.11.0` |
| KFServing | apps/kfserving/upstream | config | https://github.com/kubeflow/kfserving | `e189a510121c09f764f749143b80f6ee6baaf48b` |
| Kubeflow Pipelines | apps/pipeline/upstream | manifests/kustomize | https://github.com/kubeflow/pipelines | `1.5.0-rc.0` |

### LINKED ISSUE #1776: Test manifests and provide instructions with kustomize + kubectl
Umbrella Issue: https://github.com/kubeflow/manifests/issues/1777

Validate manifests and provide simple installation instructions with kustomize + kubectl.

### PR DESCRIPTION
**Pull request by yanniszark**
**Which issue is resolved by this Pull Request:**
Resolves https://github.com/kubeflow/manifests/issues/1775
Resolves https://github.com/kubeflow/manifests/issues/1776

**Description of your changes:**

Update manifests for Kubeflow 1.3 RC:
- Sync manifests from upstream repos
- Cleanup `common` directory
- Include instructions for installing the components and common services of Kubeflow

### CODE REVIEW

**Review by PatrickXYS — APPROVED** [review]
/lgtm

Thanks for making this happen! @yanniszark 

/hold
Feel free to unhold to merge

**Comment by yanniszark** [comment]
@PatrickXYS awesome!
/hold cancel

**Comment by martialblog** [comment]
@yanniszark Hi Yannis, just a tiny question. I've noticed that this PR changed the Central Dashboard Config from CD_REGISTRATION_FLOW=true to CD_REGISTRATION_FLOW=false , however the multi-tenancy documentation on the website still says:

> The automatic profile creation can be disabled as part of the deployment by setting the registration-flow env variable to false.

This should be updated correct?

**Pull request merged**
