### PR TITLE
v1.1 manifests for vanilla k8s

### PR DESCRIPTION
**Pull request by swiftdiaries**
Cherry-pick commits from PR #1494 #1483 

**Which issue is resolved by this Pull Request:**
Resolves https://github.com/kubeflow/kubeflow/issues/5022
Related: https://github.com/kubeflow/manifests/issues/1491

**Description of your changes:**
Adds v1.1 KFDef for vanilla k8s clusters

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

### CODE REVIEW

**Comment by swiftdiaries** [comment]
Needs https://github.com/kubeflow/manifests/pull/1483 to merge first (?)

**Comment by PatrickXYS** [comment]
Seems like unit test failed http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-manifests-presubmit-unit-1484-94770df-8176-f783?tab=workflow&nodeId=kubeflow-manifests-presubmit-unit-1484-94770df-8176-f783-3280408246.

Can you try `make generate-changed-only` to see what happened?

**Comment by swiftdiaries** [comment]
@PatrickXYS I'm waiting on https://github.com/kubeflow/manifests/pull/1483 to go in before I cherry-pick those changes in this PR 
Can I ping you when that's done for a review?

**Comment by jlewi** [comment]
Why are 705 files being changed?  Are these just test files?

**Comment by swiftdiaries** [comment]
Yes, they're all test files. It's adding a new stack called `kubernetes` so all test files related to that stack is generated here.
A comparable PR adding the AWS stack: https://github.com/kubeflow/manifests/pull/1419

**Comment by PatrickXYS** [comment]
Hey @swiftdiaries when you cherry-pick others' commits, you need to re-write commit author to you. And make sure the author of all the commits to be you.

Otherwise, the CLA check failed.
```
CLAs are signed, but unable to verify author consent
```

**Comment by swiftdiaries** [comment]
Ah thanks for the pointer @PatrickXYS 
Let me update with that

**Pull request merged**
