### PR TITLE
Automated cherry pick of #651: Update kfserving manifests to 0.2.1 #875: Cluster local gateway Istio Gateway manifests This is #876: Cluster local gateway for Istio 1.1.6 Cherry pick of #651 #875 #876 on v1.0-branch. #651: Update kfserving manifests to 0.2.1 #875: Cluster local gateway Istio Gateway manifests This is #876: Cluster local gateway for Istio 1.1.6

### PR DESCRIPTION
**Pull request by animeshsingh**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/886)

### CODE REVIEW

**Comment by animeshsingh** [comment]
@googlebot I consent.

**Comment by krishnadurai** [comment]
@animeshsingh @Tomcli While I test Istio 1.3.1 with kfctl_istio_dex.yaml, Knative 0.11.1, and KFServing 0.2.1 I come across this issue: knative/serving#6793

Otherwise LGTM.

**Comment by krishnadurai** [comment]
Referring to the issue kubeflow/kfserving#668 : A method to whitelist the URIs of deployed inference services will solve the above issue.

/lgtm

**Comment by krishnadurai** [comment]
@googlebot I conse

**Comment by yuzisun** [comment]
@googlebot I consent.

**Pull request merged**
