### PR TITLE
Update OWNERS file with Arrikto folk

### PR DESCRIPTION
**Pull request by yanniszark**
Add Arrikto folk to the OWNERS file, as part of forming the new WG
Manifests, in order to carry out the plan specified in the charter.

/cc @PatrickXYS @jlewi @Bobgy 

Signed-off-by: Yannis Zarkadas <yanniszark@arrikto.com>

### CODE REVIEW

**Comment by PatrickXYS** [comment]
Can you rebase and re-run the test?

@yanniszark

**Comment by yanniszark** [comment]
@PatrickXYS rebased! Let's see :)

**Comment by PatrickXYS** [comment]
@yanniszark It works

/lgtm

**Pull request merged**
