### PR TITLE
Revert "Automated cherry pick of #949: Adds kfserving ingressgateway …

### PR DESCRIPTION
**Pull request by kunmingg**
**Which issue is resolved by this Pull Request:**
Resolves https://github.com/kubeflow/manifests/issues/1036

**Description of your changes:**
Remove latest change for kfserving ingressgateway 

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/1037)

### CODE REVIEW

**Comment by richardsliu** [comment]
The cherrypick was made to fix v1.0.1 which was missing the kfserving ingressgateway manifests.

Maybe we should just deprecate v1.0.0.

**Comment by jlewi** [comment]
@richardsliu It sounds like we need a more fine grained fix; i.e. leave 1.0.0 unchanged but add it to 1.0.1. But that assumes 1.0.1 hasn't been "frozen" yet.  if 1.0.1 is frozen/finalized then we should start 1.0.2RC.

In keeping with the philosophy though that we should revert first I suggest we revert and then fix.

So on my end
/lgtm
/approve

@richardsliu do you agree with that?

**Comment by Jeffwan** [comment]
@jlewi @richardsliu  What's the current status? Seems master branch and v1.0.1 has the change, but v1.0-branch doesn't. This will be broken when we release v1.0.2, etc.

**Comment by richardsliu** [comment]
New PR: https://github.com/kubeflow/manifests/pull/1072

**Comment by Jeffwan** [comment]
Cool. @richardsliu What's the timeline for v1.0.2? Before we release, can we create an issue to collect some feedbacks on candidate needs to be cherry-picked?

**Pull request merged**
