### PR TITLE
Enable aws authorization support for multi-user

### PR DESCRIPTION
**Pull request by Jeffwan**
**Which issue is resolved by this Pull Request:**
Resolves #https://github.com/kubeflow/kubeflow/issues/4761

**Description of your changes:**
Enable multi-user authorization for AWS

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/908)

### CODE REVIEW

**Comment by jlewi** [comment]
Looks like you have some conflicts.
Do you need to rerun the python script to generate the 1.0.0 files?
Otherwise LGTM.

**Comment by Jeffwan** [comment]
@jlewi Yeah. I rerun the command and 1.0.0 manifest file have been updated.  Just resolve the conflict.

**Pull request merged**
