### PR TITLE
Cherry-pick commits to v1.3-branch

### PR DESCRIPTION
**Pull request by yanniszark**
Cherry-pick bugfixes to v1.3-branch.
Refs https://github.com/kubeflow/manifests/issues/1798

cc @kubeflow/wg-manifests-leads

### CODE REVIEW

**Comment by yanniszark** [comment]
@Bobgy @pvaneck @DavidSpek @Bobgy I'll need you to write the cla command in order to cherry-pick your fixes.

**Comment by DavidSpek** [comment]
@googlebot I consent.

**Comment by pvaneck** [comment]
@googlebot I consent.

**Comment by andreyvelich** [comment]
@googlebot I consent.

**Comment by Bobgy** [comment]
Thank you!
@googlebot I consent

**Comment by yanniszark** [comment]
@googlebot I consent.

**Comment by Bobgy** [comment]
Strange, the system says it's still pending @andreyvelich's consent, but Andrey has consented above.

I'll override to keep the release going.

**Pull request merged**
