### PR TITLE
Automated cherry pick of #913: Updates and synchronizes config files Removes drift from Cherry pick of #913 on v1.0-branch. #913: Updates and synchronizes config files Removes drift from

### PR DESCRIPTION
**Pull request by krishnadurai**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/919)

### CODE REVIEW

**Comment by jlewi** [comment]
@krishnadurai are there any risks with adding the cluster-local-gateway change? Is it purely additive?

**Comment by krishnadurai** [comment]
@jlewi this is purely additive. I don't see a risk with this.

**Pull request merged**
