### PR TITLE
Update jupyter notebooks image tags

### PR DESCRIPTION
**Pull request by Tabrizian**
**Which issue is resolved by this Pull Request:**
Resolves #

kubeflow/kubeflow#4267

**Description of your changes:**

**Checklist:**
- [x] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/497)

### CODE REVIEW

**Comment by Tabrizian** [comment]
@jlewi I can't understand why the tests are failing. I could saw the logs but I can't now.

**Comment by jlewi** [comment]
@Tabrizian if you join the log kubeflow-ci-viewers group you will be able to see logs in stackdriver.

Here are the logs

[kubeflow-manifests-presubmit-e2e-497-b1e849c-7712-fe79-2386170504.log.txt](https://github.com/kubeflow/manifests/files/3719648/kubeflow-manifests-presubmit-e2e-497-b1e849c-7712-fe79-2386170504.log.txt)

**Comment by Tabrizian** [comment]
@jlewi Thanks for posting the logs. It seems like it is related to the `TestKfservingCrdsOverlaysApplication`. Rebasing to see whether it helps or not.

**Comment by jlewi** [comment]
I think the presubmits are broken.
Should be fixed by
kubeflow/manifests#505

**Comment by jlewi** [comment]
Here are the logs from the most recent run.
[kubeflow-manifests-presubmit-kfctl-go-497-344005a-1952-9716-1515545093.log.txt](https://github.com/kubeflow/manifests/files/3721024/kubeflow-manifests-presubmit-kfctl-go-497-344005a-1952-9716-1515545093.log.txt)

It looks like it failed waiting for the iap-enabler pod. The iap-enabler pod is restarting with error.

```
Error unable to fetch PROJECT from compute metadata
```

This should be fixed by kubeflow/manifests#498

@Tabrizian  it looks like you just need to rebase again on master to pick up the fix.

/test all

**Pull request merged**
