### PR TITLE
CRDs should not have status field.

### PR DESCRIPTION
**Pull request by jlewi**
* kubeflow/manifests#1174 lots of CRDs have status fields which
  causes ACM to complain that the CRD is invalid.

* This PR cleans up those CRDs and adds an appropriate validation test.

* Fix typos in AWS application specs (kubeflow/testing#668)

### CODE REVIEW

**Comment by Jeffwan** [comment]
/lgtm

Thanks for the fix

**Comment by jlewi** [comment]
Not sure why tide isn't merging this.

/approve

**Pull request merged**
