### PR TITLE
Upgraded istio to v1.19.10

### PR DESCRIPTION
**Pull request by biswajit-9776**
# Pull Request Template for Kubeflow manifests Issues

- Please include a summary of changes and the related issue. 
- List any dependencies that are required for this change. 
- Please delete the options that are not relevant.
- The following checklist will help you to satisfy the requirements.

  
## ✅ Unit Test Checklist
  
  - [ ] 🛠️ Make sure you have installed kustomize == 5.2.1+     
  - [ ] ✍️ Have you written new tests for your core changes, as applicable?      
  - [ ] 🔄 Have you successfully run existing tests with your changes ?    
  - [ ] 🚀 Have you successfully run existing and new tests with your changes ?

## ✅ Contributor checklist
  - [ ] All the commits have been _signed-off_  (To pass the `DCO` check)
  - [ ] Submit the [Contributor License Agreements](https://cla.developers.google.com/clas) (To pass the `cla/google` check)

---     
 
>You can join our slack channel **wg-manifests** [here](https://www.kubeflow.org/docs/about/community/). This link also contains our meeting schedule.

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
Please also fix the Readme based on your experience with the upgrade for istio and istio-cni in this PR.

**Comment by biswajit-9776** [comment]
Let me upgrade istio-cni and push it in this same PR.

**Comment by biswajit-9776** [comment]
I pushed this PR with two scripts which I think could push after the v1.22.0 upgradation.

**Comment by juliusvonkohout** [comment]
> I pushed this PR with two scripts which I think could push after the v1.22.0 upgradation.

I do not see the two scripts in /hack
Please add them in the next PR

/lgtm
/approve

**Comment by biswajit-9776** [comment]
Yes I will push the two scripts in the upcoming PRs.

**Pull request merged**
