### PR TITLE
Cherry-picks: Manifest updates for 1.4 #2006 #2013 #2008 #2021#2020

### PR DESCRIPTION
**Pull request by kimwnasptd**
Cherry-pick commits from:
* #2006
* #2013
* #2008 
* #2021 
* #2020

With this we should be ready to cut the next RC.

/cc @elikatsis

### CODE REVIEW

**Comment by Jeffwan** [comment]
Please cherry-pick this one https://github.com/kubeflow/manifests/pull/2024 before next RC

**Comment by Jeffwan** [comment]
Feel free to cancel hold. cherry-picks looks good to me

/lgtm
/hold

**Review by Jeffwan — APPROVED** [review]

**Comment by kimwnasptd** [comment]
@Jeffwan thank you for helping with the Training Operator manifests!

@elikatsis this PR should be ready to merge and cut the next RC :tada:

**Pull request merged**
