### PR TITLE
Remove jupyterhub kustomize manifest

### LINKED ISSUE #116: Delete JupyterHub kustomize manifest
It looks like
https://github.com/kubeflow/manifests/tree/master/jupyter/jupyter

is providing a manifest for jupyterhub.

But jupyterhub was removed in 0.5.

I suggest deleting that manifest to avoid confusion about whether jupyterhub is supported or not.

@ashahba Interested?

### PR DESCRIPTION
**Pull request by whiletruelearn**
**Which issue is resolved by this Pull Request:** Fixes #116 
Resolves #

**Description of your changes:**
Removed `jupyter/jupyter`

**Checklist:**
- [ ] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate`
    3. `make test`

cc : @jlewi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/manifests/253)

### CODE REVIEW

**Comment by jlewi** [comment]
/ok-to-test
/lgtm
/approve

Thanks @whiletruelearn

**Comment by whiletruelearn** [comment]
@jlewi , I can see in the build that all the test has passed, but the build seems to be broken ?

**Comment by jlewi** [comment]
if you click details and expand you can find a link to the Argo workflow
http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-manifests-presubmit-e2e-253-6e7ec62-9376-b945?tab=workflow

From there you can see a test failure

```
--- FAIL: TestJupyterBase (0.02s)
   jupyter-base_test.go:1952: could not load kustomize loader: absolute path error in '../jupyter/jupyter/base' : evalsymlink failure on '../jupyter/jupyt
er/base' : lstat /mnt/test-data-volume/kubeflow-manifests-presubmit-e2e-253-6e7ec62-9376-b945/src/kubeflow/manifests/jupyter/jupyter: no such file or dire
ctory
```

Looks like you need to update the go tests to remove the test for the jupyter manifest.

**Comment by jlewi** [comment]
@whiletruelearn Any chance you could fix the test? Would be great to get this fixed and committed

**Comment by jlewi** [comment]
Ping?

**Comment by jlewi** [comment]
This has been fixed on master.

**Pull request closed without merging**
